import type { ExamPracticeTest } from '../../types';

export const inburgeringA2Reading4: ExamPracticeTest = {
  id: 'inburgering-a2-reading-4',
  examType: 'inburgering-a2',
  skill: 'reading',
  title: 'Inburgering A2 – Lezen (Oefening 4)',
  description:
    'Practice reading exam at A2 level. Read short, simple Dutch texts and answer basic comprehension questions. Topics: public transport, weather, shopping, school and children, healthcare appointments, and workplace communication.',
  timeLimitMinutes: 60,
  passingScore: 60,
  totalQuestions: 25,
  sections: [
    {
      id: 'a2-r4-s1',
      passageTitle: 'Een sms over de bus',
      passage:
        'Hoi Sara,\n\nIk kom een beetje later. De bus heeft vertraging. Hij rijdt nu om 14:20 in plaats van 14:05. Ik ben er om ongeveer kwart over twee.\n\nTot dan!\nLena',
      instructions: 'Lees het bericht en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q1',
          type: 'multiple-choice',
          question: 'Waarom komt Lena later?',
          options: ['Ze is ziek.', 'De bus heeft vertraging.', 'Ze is het adres vergeten.', 'Ze werkt nog.'],
          correctIndex: 1,
          explanation: '"De bus heeft vertraging."',
          topicArea: 'transport',
        },
        {
          id: 'a2-r4-q2',
          type: 'multiple-choice',
          question: 'Hoe laat komt de bus nu aan?',
          options: ['14:05', '14:15', '14:20', '14:30'],
          correctIndex: 2,
          explanation: '"Hij rijdt nu om 14:20 in plaats van 14:05."',
          topicArea: 'transport',
        },
        {
          id: 'a2-r4-q3',
          type: 'multiple-choice',
          question: 'Om hoe laat is Lena er ongeveer?',
          options: ['Kwart voor twee', 'Kwart over twee', 'Half twee', 'Drie uur'],
          correctIndex: 1,
          explanation: '"Ik ben er om ongeveer kwart over twee."',
          topicArea: 'transport',
        },
      ],
    },
    {
      id: 'a2-r4-s2',
      passageTitle: 'Het weerbericht',
      passage:
        'Weerbericht voor morgen, dinsdag 14 mei:\n\nVanochtend is het bewolkt met kans op regen. In de middag wordt het droger en kan de zon even doorbreken. De temperatuur is 14 graden. Er staat een matige wind uit het westen. Neem een regenjas mee voor de ochtend.',
      instructions: 'Lees het weerbericht en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q4',
          type: 'multiple-choice',
          question: 'Hoe is het weer in de ochtend?',
          options: ['Zonnig en warm.', 'Bewolkt met kans op regen.', 'Koud met sneeuw.', 'Winderig maar droog.'],
          correctIndex: 1,
          explanation: '"Vanochtend is het bewolkt met kans op regen."',
          topicArea: 'weather',
        },
        {
          id: 'a2-r4-q5',
          type: 'multiple-choice',
          question: 'Wat is de temperatuur morgen?',
          options: ['10 graden', '12 graden', '14 graden', '18 graden'],
          correctIndex: 2,
          explanation: '"De temperatuur is 14 graden."',
          topicArea: 'weather',
        },
        {
          id: 'a2-r4-q6',
          type: 'multiple-choice',
          question: 'Wat adviseert het weerbericht mee te nemen?',
          options: ['Een paraplu', 'Een zonnebril', 'Een regenjas', 'Een sjaal'],
          correctIndex: 2,
          explanation: '"Neem een regenjas mee voor de ochtend."',
          topicArea: 'weather',
        },
      ],
    },
    {
      id: 'a2-r4-s3',
      passageTitle: 'Aanbieding in de supermarkt',
      passage:
        'SUPER AANBIEDING – DEZE WEEK!\n\nVerse aardbeien – 400 gram – NU €1,99 (normaal €2,99)\nSinaasappelsap – 1 liter – NU €1,49\nVolkorenbrood – 800 gram – NU €2,25\n\nGeldig van maandag 12 mei t/m zaterdag 17 mei.\nNiet geldig op zondag. Maximaal 3 stuks per klant.',
      instructions: 'Lees de aanbieding en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q7',
          type: 'multiple-choice',
          question: 'Hoeveel kosten de aardbeien deze week?',
          options: ['€1,49', '€1,99', '€2,25', '€2,99'],
          correctIndex: 1,
          explanation: '"Verse aardbeien … NU €1,99"',
          topicArea: 'shopping',
        },
        {
          id: 'a2-r4-q8',
          type: 'multiple-choice',
          question: 'Tot welke dag is de aanbieding geldig?',
          options: ['Vrijdag 16 mei', 'Zaterdag 17 mei', 'Zondag 18 mei', 'Maandag 19 mei'],
          correctIndex: 1,
          explanation: '"Geldig van maandag 12 mei t/m zaterdag 17 mei."',
          topicArea: 'shopping',
        },
        {
          id: 'a2-r4-q9',
          type: 'multiple-choice',
          question: 'Hoeveel pakken sinaasappelsap mag een klant maximaal kopen voor de aanbiedingsprijs?',
          options: ['1', '2', '3', 'Onbeperkt'],
          correctIndex: 2,
          explanation: '"Maximaal 3 stuks per klant."',
          topicArea: 'shopping',
        },
      ],
    },
    {
      id: 'a2-r4-s4',
      passageTitle: 'Brief van de school',
      passage:
        'Beste ouders en verzorgers,\n\nOp woensdag 21 mei is er een ouderavond op school. De avond begint om 19:30 en is klaar om 21:00. U kunt dan praten met de leraar van uw kind.\n\nWilt u komen? Schrijf uw naam voor 15 mei op de lijst bij de receptie.\n\nOok op 21 mei is er geen school voor de kinderen van groep 5 en 6. Zij hebben die dag een schoolreisje naar de dierentuin.\n\nMet vriendelijke groet,\nDirectie basisschool De Regenboog',
      instructions: 'Lees de brief en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q10',
          type: 'multiple-choice',
          question: 'Wanneer is de ouderavond?',
          options: ['15 mei', '19 mei', '21 mei', '22 mei'],
          correctIndex: 2,
          explanation: '"Op woensdag 21 mei is er een ouderavond op school."',
          topicArea: 'school',
        },
        {
          id: 'a2-r4-q11',
          type: 'multiple-choice',
          question: 'Hoe laat begint de ouderavond?',
          options: ['18:00', '19:00', '19:30', '21:00'],
          correctIndex: 2,
          explanation: '"De avond begint om 19:30."',
          topicArea: 'school',
        },
        {
          id: 'a2-r4-q12',
          type: 'multiple-choice',
          question: 'Wat doen de kinderen van groep 5 en 6 op 21 mei?',
          options: ['Ze zitten op school.', 'Ze gaan naar de ouderavond.', 'Ze gaan op schoolreisje naar de dierentuin.', 'Ze hebben een vrije dag thuis.'],
          correctIndex: 2,
          explanation: '"Zij hebben die dag een schoolreisje naar de dierentuin."',
          topicArea: 'school',
        },
      ],
    },
    {
      id: 'a2-r4-s5',
      passageTitle: 'Afspraakbevestiging van de dokter',
      passage:
        'Beste meneer Dijk,\n\nU heeft een afspraak bij huisarts De Vries op:\n\nDonderdag 22 mei om 10:15\nAdres: Kerkstraat 4, Haarlem\n\nNeem uw zorgpas mee.\nAls u niet kunt komen, bel dan uiterlijk 24 uur van tevoren: 023-456 78 90.\n\nMet vriendelijke groet,\nHuisartsenpraktijk De Vries',
      instructions: 'Lees de bevestiging en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q13',
          type: 'multiple-choice',
          question: 'Wanneer is de afspraak bij de huisarts?',
          options: ['Woensdag 21 mei om 10:15', 'Donderdag 22 mei om 10:15', 'Vrijdag 23 mei om 10:15', 'Donderdag 22 mei om 11:15'],
          correctIndex: 1,
          explanation: '"Donderdag 22 mei om 10:15"',
          topicArea: 'healthcare',
        },
        {
          id: 'a2-r4-q14',
          type: 'multiple-choice',
          question: 'Wat moet meneer Dijk meenemen?',
          options: ['Zijn paspoort', 'Zijn zorgpas', 'Een foto', 'Zijn belastingformulier'],
          correctIndex: 1,
          explanation: '"Neem uw zorgpas mee."',
          topicArea: 'healthcare',
        },
        {
          id: 'a2-r4-q15',
          type: 'multiple-choice',
          question: 'Wat moet hij doen als hij niet kan komen?',
          options: [
            'Een e-mail sturen.',
            'Gewoon niet komen — dat is niet erg.',
            'Uiterlijk 24 uur van tevoren bellen.',
            'Op de dag zelf een sms sturen.',
          ],
          correctIndex: 2,
          explanation: '"Als u niet kunt komen, bel dan uiterlijk 24 uur van tevoren."',
          topicArea: 'healthcare',
        },
      ],
    },
    {
      id: 'a2-r4-s6',
      passageTitle: 'Memo van de werkgever',
      passage:
        'Aan: alle medewerkers\nVan: de manager\n\nVanaf volgende week maandag zijn de nieuwe werkroosters beschikbaar. U kunt uw rooster bekijken op de medewerkersportal.\n\nVergeet niet: het is verplicht om uw pauze van 30 minuten te nemen. De lunch is tussen 12:00 en 13:00.\n\nHeeft u vragen? Spreek mij aan of stuur een e-mail naar manager@bedrijf.nl.',
      instructions: 'Lees de memo en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q16',
          type: 'multiple-choice',
          question: 'Waar kunnen medewerkers het nieuwe rooster bekijken?',
          options: ['Op de prikbord in de kantine.', 'Op de medewerkersportal.', 'Bij de manager op kantoor.', 'Via een brief thuis.'],
          correctIndex: 1,
          explanation: '"U kunt uw rooster bekijken op de medewerkersportal."',
          topicArea: 'work',
        },
        {
          id: 'a2-r4-q17',
          type: 'multiple-choice',
          question: 'Hoe lang is de verplichte pauze?',
          options: ['15 minuten', '20 minuten', '30 minuten', '45 minuten'],
          correctIndex: 2,
          explanation: '"Het is verplicht om uw pauze van 30 minuten te nemen."',
          topicArea: 'work',
        },
        {
          id: 'a2-r4-q18',
          type: 'multiple-choice',
          question: 'Wanneer is de lunch?',
          options: ['11:00–12:00', '12:00–13:00', '13:00–14:00', '12:30–13:30'],
          correctIndex: 1,
          explanation: '"De lunch is tussen 12:00 en 13:00."',
          topicArea: 'work',
        },
      ],
    },
    {
      id: 'a2-r4-s7',
      passageTitle: 'Informatie over de bibliotheek',
      passage:
        'Welkom bij de Openbare Bibliotheek Utrecht!\n\nOpeningstijden:\nMaandag t/m vrijdag: 09:00–20:00\nZaterdag: 10:00–17:00\nZondag: gesloten\n\nLidmaatschap kost €35 per jaar voor volwassenen. Kinderen onder 18 jaar zijn gratis lid.\n\nU kunt boeken, dvd\'s en tijdschriften lenen. Een boek mag u 3 weken houden. Verlengen kan online of aan de balie.',
      instructions: 'Lees de informatie en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q19',
          type: 'multiple-choice',
          question: 'Hoe laat sluit de bibliotheek op zaterdag?',
          options: ['16:00', '17:00', '18:00', '20:00'],
          correctIndex: 1,
          explanation: '"Zaterdag: 10:00–17:00"',
          topicArea: 'daily-life',
        },
        {
          id: 'a2-r4-q20',
          type: 'multiple-choice',
          question: 'Hoeveel kost een lidmaatschap voor een volwassene per jaar?',
          options: ['Gratis', '€15', '€25', '€35'],
          correctIndex: 3,
          explanation: '"Lidmaatschap kost €35 per jaar voor volwassenen."',
          topicArea: 'daily-life',
        },
        {
          id: 'a2-r4-q21',
          type: 'multiple-choice',
          question: 'Hoe lang mag u een boek houden?',
          options: ['1 week', '2 weken', '3 weken', '4 weken'],
          correctIndex: 2,
          explanation: '"Een boek mag u 3 weken houden."',
          topicArea: 'daily-life',
        },
      ],
    },
    {
      id: 'a2-r4-s8',
      passageTitle: 'Kort artikel: sport in de buurt',
      passage:
        'In de wijk Oost is er een nieuwe sporthal geopend. Hier kunt u badminton, volleybal en yoga doen. De lessen zijn voor iedereen: kinderen, volwassenen en ouderen.\n\nDe sporthal is open van dinsdag tot en met zondag. Maandag is er geen les.\n\nEen losse les kost €5. Een abonnement voor een maand kost €30. Meer informatie? Ga naar www.sporthaloost.nl.',
      instructions: 'Lees het artikel en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q22',
          type: 'multiple-choice',
          question: 'Welke sporten kunt u doen in de nieuwe sporthal?',
          options: ['Voetbal, tennis en zwemmen.', 'Badminton, volleybal en yoga.', 'Basketbal, hardlopen en fietsen.', 'Boksen, judo en dans.'],
          correctIndex: 1,
          explanation: '"Hier kunt u badminton, volleybal en yoga doen."',
          topicArea: 'leisure',
        },
        {
          id: 'a2-r4-q23',
          type: 'multiple-choice',
          question: 'Op welke dag is de sporthal gesloten?',
          options: ['Zaterdag', 'Zondag', 'Maandag', 'Dinsdag'],
          correctIndex: 2,
          explanation: '"Maandag is er geen les."',
          topicArea: 'leisure',
        },
        {
          id: 'a2-r4-q24',
          type: 'multiple-choice',
          question: 'Wat kost een maandabonnement?',
          options: ['€5', '€15', '€25', '€30'],
          correctIndex: 3,
          explanation: '"Een abonnement voor een maand kost €30."',
          topicArea: 'leisure',
        },
      ],
    },
    {
      id: 'a2-r4-s9',
      passageTitle: 'Instructies: hoe betaalt u uw huur?',
      passage:
        'Beste huurder,\n\nUw huur kunt u op twee manieren betalen:\n\n1. Automatische incasso: wij schrijven het bedrag elke 1e van de maand af van uw rekening. U hoeft niets te doen.\n\n2. Zelf overmaken: maak het bedrag voor de 1e van de maand over naar rekeningnummer NL00 RABO 0123 4567 89. Vermeld uw naam en huurnummer.\n\nHeeft u vragen? Bel 030-123 45 67 (maandag–vrijdag 09:00–17:00).',
      instructions: 'Lees de instructies en beantwoord de vragen.',
      questions: [
        {
          id: 'a2-r4-q25',
          type: 'multiple-choice',
          question: 'Als u de huur zelf overmaakt, wat moet u dan vermelden?',
          options: ['Uw geboortedatum en adres.', 'Uw naam en huurnummer.', 'Uw BSN-nummer en telefoonnummer.', 'Alleen het bedrag.'],
          correctIndex: 1,
          explanation: '"Vermeld uw naam en huurnummer."',
          topicArea: 'housing',
        },
      ],
    },
  ],
};
