import { ExamPracticeTest } from '../../types';

export const inburgeringA2Reading3: ExamPracticeTest = {
  id: 'inburgering-a2-reading-3',
  examType: 'inburgering-a2',
  skill: 'reading',
  title: 'Inburgeringsexamen A2 – Lezen (Oefening 3)',
  description:
    'Practice reading exam at A2 level. Read short Dutch texts (signs, letters, notices, forms) and answer multiple-choice questions. Topics: public transport, appointments, neighbourhood, leisure.',
  timeLimitMinutes: 40,
  passingScore: 70,
  totalQuestions: 25,
  sections: [
    {
      id: 'a2r3-s1',
      title: 'Bordjes en korte mededelingen',
      instructions: 'Read each sign or short notice. Choose the best answer.',
      questions: [
        {
          id: 'a2r3-s1-q1',
          type: 'multiple-choice',
          question: 'A sign at the entrance of a building reads: "Ingang alleen voor medewerkers. Bezoekers melden zich bij de receptie." What should a visitor do?',
          options: ['Use the main entrance freely.', 'Report to the reception desk.', 'Wait outside until a staff member comes.', 'Use another entrance around the back.'],
          correctIndex: 1,
          explanation: '"Bezoekers melden zich bij de receptie" = visitors report to the reception.',
          topicArea: 'signs',
        },
        {
          id: 'a2r3-s1-q2',
          type: 'multiple-choice',
          question: 'A notice on a bus reads: "Geldig vervoerbewijs verplicht. Bij controle boete €100." What does this mean?',
          options: ['You may travel for free if you have a valid ID.', 'You need a valid ticket; a fine of €100 applies if you do not have one.', 'Inspectors can fine you up to €100 for any reason.', 'The bus is free for passengers with an OV-chipkaart.'],
          correctIndex: 1,
          explanation: '"Geldig vervoerbewijs verplicht" = a valid travel ticket is required; "boete €100" = fine of €100.',
          topicArea: 'transport',
        },
        {
          id: 'a2r3-s1-q3',
          type: 'multiple-choice',
          question: 'A sign at a pharmacy reads: "Gesloten op maandag 19 februari. Spoedgevallen: bel 112 of ga naar de huisartsenpost." What does this mean?',
          options: ['The pharmacy is permanently closed.', 'The pharmacy is closed on 19 February; in emergencies call 112 or go to the out-of-hours GP.', 'You can collect prescriptions on Mondays only.', 'The pharmacy opens late on 19 February.'],
          correctIndex: 1,
          explanation: '"Gesloten op maandag 19 februari" = closed on Monday 19 February. The rest gives emergency information.',
          topicArea: 'healthcare',
        },
        {
          id: 'a2r3-s1-q4',
          type: 'multiple-choice',
          question: 'A sign at a swimming pool reads: "Douchen verplicht voor het zwemmen. Geen eten of drinken in het zwembad." What are the two rules?',
          options: ['You must bring your own towel and no drinks are allowed.', 'You must shower before swimming and no food or drinks in the pool.', 'Swimming requires a ticket and you must shower afterward.', 'Children must be accompanied and no food is allowed.'],
          correctIndex: 1,
          explanation: '"Douchen verplicht voor het zwemmen" = shower required before swimming; "geen eten of drinken" = no food or drinks.',
          topicArea: 'leisure',
        },
      ],
    },
    {
      id: 'a2r3-s2',
      title: 'Brief van de tandarts',
      passageTitle: 'Herinnering: uw afspraak bij tandartspraktijk De Linde',
      passage:
        'Geachte mevrouw Arslan,\n\nWij schrijven u om u te herinneren aan uw afspraak bij onze praktijk:\n\nDatum: dinsdag 25 februari\nTijd: 14:30 uur\nBehandeling: periodieke controle\n\nWij vragen u om 5 minuten van tevoren aanwezig te zijn. Als u de afspraak niet kunt nakomen, verzoeken wij u dit minimaal 24 uur van tevoren te annuleren via telefoonnummer 020-5678912.\n\nBij het niet annuleren of meer dan 24 uur te laat annuleren, brengen wij €30,- in rekening.\n\nMet vriendelijke groet,\nTandartspraktijk De Linde',
      instructions: 'Read the letter and answer the questions.',
      questions: [
        {
          id: 'a2r3-s2-q1',
          type: 'multiple-choice',
          question: 'What is the appointment on Tuesday 25 February for?',
          options: ['A tooth extraction.', 'A routine check-up.', 'Fitting a crown.', 'A consultation about braces.'],
          correctIndex: 1,
          explanation: '"Periodieke controle" = routine/periodic check-up.',
          topicArea: 'appointments',
        },
        {
          id: 'a2r3-s2-q2',
          type: 'multiple-choice',
          question: 'How many minutes early should the patient arrive?',
          options: ['10 minutes.', '15 minutes.', '5 minutes.', '30 minutes.'],
          correctIndex: 2,
          explanation: '"5 minuten van tevoren aanwezig te zijn" = to be present 5 minutes early.',
          topicArea: 'appointments',
        },
        {
          id: 'a2r3-s2-q3',
          type: 'multiple-choice',
          question: 'How far in advance must the patient cancel to avoid a charge?',
          options: ['At least 48 hours in advance.', 'At least 24 hours in advance.', 'On the same day before 10:00.', 'No cancellation fee applies.'],
          correctIndex: 1,
          explanation: '"Minimaal 24 uur van tevoren te annuleren" = cancel at least 24 hours in advance.',
          topicArea: 'appointments',
        },
        {
          id: 'a2r3-s2-q4',
          type: 'multiple-choice',
          question: 'How much is the fee for missing the appointment without cancelling?',
          options: ['€20,-', '€50,-', '€30,-', 'Nothing — the first missed appointment is free.'],
          correctIndex: 2,
          explanation: '"Brengen wij €30,- in rekening" = we will charge €30,-.',
          topicArea: 'appointments',
        },
      ],
    },
    {
      id: 'a2r3-s3',
      title: 'OV-chipkaart informatie',
      passageTitle: 'Hoe werkt de OV-chipkaart?',
      passage:
        'De OV-chipkaart is een betaalkaart waarmee u in de bus, tram, metro en trein kunt reizen. U kunt de kaart kopen bij de NS-kassa en bij sommige supermarkten.\n\nVoor de trein moet u altijd in- en uitchecken bij de gele paaltjes. Vergeet u uit te checken? Dan betaalt u automatisch een hoog tarief.\n\nU kunt geld laden op uw kaart via een automaat, bij de kassa, of online. Het minimum saldo om in te checken is €0,20 voor bus, tram en metro en €2,00 voor de trein.\n\nBent u 65 jaar of ouder? Dan heeft u misschien recht op een korting met de Seniorenkorting. Vraag hiernaar bij de NS.',
      instructions: 'Read the information and answer the questions.',
      questions: [
        {
          id: 'a2r3-s3-q1',
          type: 'multiple-choice',
          question: 'Where can you buy an OV-chipkaart? (Choose the best answer)',
          options: ['Only at NS ticket offices.', 'At NS ticket offices and some supermarkets.', 'Only online.', 'At any bus stop.'],
          correctIndex: 1,
          explanation: '"U kunt de kaart kopen bij de NS-kassa en bij sommige supermarkten."',
          topicArea: 'transport',
        },
        {
          id: 'a2r3-s3-q2',
          type: 'multiple-choice',
          question: 'What happens if you forget to check out on the train?',
          options: ['You travel for free.', 'You are fined €50.', 'You automatically pay a high fare.', 'Nothing happens.'],
          correctIndex: 2,
          explanation: '"Vergeet u uit te checken? Dan betaalt u automatisch een hoog tarief."',
          topicArea: 'transport',
        },
        {
          id: 'a2r3-s3-q3',
          type: 'multiple-choice',
          question: 'What is the minimum balance needed to check in on a train?',
          options: ['€0,20', '€1,00', '€2,00', '€5,00'],
          correctIndex: 2,
          explanation: '"Het minimum saldo … €2,00 voor de trein."',
          topicArea: 'transport',
        },
        {
          id: 'a2r3-s3-q4',
          type: 'multiple-choice',
          question: 'Who may be entitled to a discount on the OV-chipkaart?',
          options: ['Students under 18.', 'People aged 65 or older.', 'People with a disability card.', 'Everyone automatically.'],
          correctIndex: 1,
          explanation: '"Bent u 65 jaar of ouder? Dan heeft u misschien recht op een korting met de Seniorenkorting."',
          topicArea: 'transport',
        },
      ],
    },
    {
      id: 'a2r3-s4',
      title: 'Prikbord: buurtberichten',
      passageTitle: 'Mededelingen op het prikbord van het buurtcentrum',
      passage:
        'BERICHT 1 – BUURTBARBECUE\nZaterdag 1 maart organiseert het buurtcomité een barbecue in het park. Aanvang: 15:00 uur. Iedereen is welkom. Breng uw eigen eten en drinken mee. Tafels en stoelen zijn aanwezig.\n\nBERICHT 2 – VERLOREN SLEUTELS\nOp 14 februari zijn bij de ingang van het buurtcentrum sleutels gevonden aan een rode sleutelhanger. Eigenaar: neem contact op met de beheerder.\n\nBERICHT 3 – CURSUS COMPUTERGEBRUIK\nDo u moeite met de computer? Gratis cursus voor beginners. Elke woensdag van 10:00–12:00. Aanmelden via info@buurtcentrum.nl.\n\nBERICHT 4 – RUIMTE TE HUUR\nVergaderruimte beschikbaar voor groepen van 5–20 personen. Kosten: €15 per uur. Reserveren: bel 06-12345678.',
      instructions: 'Read the notices and answer the questions.',
      questions: [
        {
          id: 'a2r3-s4-q1',
          type: 'multiple-choice',
          question: 'For the neighbourhood barbecue, what do attendees need to bring?',
          options: ['Tables and chairs.', 'Their own food and drinks.', 'A ticket purchased in advance.', 'A contribution of €5 per person.'],
          correctIndex: 1,
          explanation: '"Breng uw eigen eten en drinken mee. Tafels en stoelen zijn aanwezig." = bring your own food and drinks; tables and chairs are provided.',
          topicArea: 'neighbourhood',
        },
        {
          id: 'a2r3-s4-q2',
          type: 'multiple-choice',
          question: 'Someone found keys at the community centre. What should the owner do?',
          options: ['Call the police.', 'Post a message on the notice board.', 'Contact the building manager.', 'Check at the nearest supermarket.'],
          correctIndex: 2,
          explanation: '"Eigenaar: neem contact op met de beheerder." = the owner should contact the building manager.',
          topicArea: 'neighbourhood',
        },
        {
          id: 'a2r3-s4-q3',
          type: 'multiple-choice',
          question: 'The computer course is described as "gratis voor beginners". What does "gratis" mean?',
          options: ['Mandatory.', 'Free of charge.', 'Paid.', 'Advanced level.'],
          correctIndex: 1,
          explanation: '"Gratis" = free of charge.',
          topicArea: 'leisure',
        },
        {
          id: 'a2r3-s4-q4',
          type: 'multiple-choice',
          question: 'How much does it cost to hire the meeting room for 2 hours?',
          options: ['€15', '€30', '€20', 'It is free for community groups.'],
          correctIndex: 1,
          explanation: '"Kosten: €15 per uur" = €15 per hour. 2 hours = €30.',
          topicArea: 'neighbourhood',
        },
      ],
    },
    {
      id: 'a2r3-s5',
      title: 'Informatiebrief van de bibliotheek',
      passageTitle: 'Welkom bij de Bibliotheek – Uw lidmaatschap',
      passage:
        'Geachte heer Nguyen,\n\nWelkom als nieuw lid van de Stadsbibliotheek. Uw ledenpas is bijgevoegd.\n\nMet uw ledenpas kunt u:\n– Boeken, tijdschriften en dvd\'s lenen\n– Gratis gebruik maken van de computers\n– Meedoen aan activiteiten zoals leesclubs en taalcursussen\n\nLengtermijn: 3 weken. U kunt maximaal 10 items tegelijk lenen. Verlengen kan online, per telefoon of aan de balie.\n\nTe laat terugbrengen? We berekenen €0,10 per item per dag.\n\nOpeningstijden:\nMaandag–vrijdag: 10:00–19:00\nZaterdag: 10:00–17:00\nZondag: gesloten\n\nMet vriendelijke groet,\nStadsbibliotheek',
      instructions: 'Read the letter and answer the questions.',
      questions: [
        {
          id: 'a2r3-s5-q1',
          type: 'multiple-choice',
          question: 'What can the new member do with the library card? (Choose the best answer)',
          options: ['Only borrow books.', 'Borrow books, use computers for free, and join activities.', 'Buy books at a discount.', 'Access the internet anywhere in the city.'],
          correctIndex: 1,
          explanation: 'The letter lists: borrow books/magazines/DVDs, use computers for free, join activities.',
          topicArea: 'services',
        },
        {
          id: 'a2r3-s5-q2',
          type: 'multiple-choice',
          question: 'How long is the loan period for borrowed items?',
          options: ['1 week.', '2 weeks.', '3 weeks.', '1 month.'],
          correctIndex: 2,
          explanation: '"Lengtermijn: 3 weken" = loan period: 3 weeks.',
          topicArea: 'services',
        },
        {
          id: 'a2r3-s5-q3',
          type: 'multiple-choice',
          question: 'What is the late fee per item per day?',
          options: ['€0,05', '€0,10', '€0,50', '€1,00'],
          correctIndex: 1,
          explanation: '"€0,10 per item per dag" = €0.10 per item per day.',
          topicArea: 'services',
        },
        {
          id: 'a2r3-s5-q4',
          type: 'multiple-choice',
          question: 'Is the library open on Sundays?',
          options: ['Yes, from 12:00 to 17:00.', 'Yes, from 10:00 to 15:00.', 'No, it is closed on Sundays.', 'Only in summer.'],
          correctIndex: 2,
          explanation: '"Zondag: gesloten" = Sunday: closed.',
          topicArea: 'services',
        },
        {
          id: 'a2r3-s5-q5',
          type: 'multiple-choice',
          question: 'On which day does the library close latest in the evening?',
          options: ['Saturday.', 'Sunday.', 'Monday through Friday.', 'The same time every day.'],
          correctIndex: 2,
          explanation: 'Monday–Friday open until 19:00; Saturday until 17:00; Sunday closed.',
          topicArea: 'services',
        },
      ],
    },
    {
      id: 'a2r3-s6',
      title: 'Formulier: huurcontract informatie',
      passageTitle: 'Informatie over uw huurwoning',
      passage:
        'Geachte huurder,\n\nHieronder vindt u belangrijke informatie over uw huurwoning.\n\nHuurprijs: €875,- per maand (inclusief servicekosten)\nBetaaldatum: vóór de 1e van elke maand\nBetaling: automatische incasso van uw bankrekening\n\nUw woning is gelegen op de 3e verdieping. Er is geen lift aanwezig.\n\nReparaties: kleine reparaties (tot €100,-) zijn uw eigen verantwoordelijkheid. Grotere reparaties kunt u melden via 0800-1234567 (gratis).\n\nHuisdieren: één kat of één kleine hond is toegestaan. Grotere huisdieren zijn niet toegestaan zonder schriftelijke toestemming.',
      instructions: 'Read the information and answer the questions.',
      questions: [
        {
          id: 'a2r3-s6-q1',
          type: 'multiple-choice',
          question: 'How does the tenant pay the rent?',
          options: ['By bank transfer before the 15th.', 'By automatic direct debit from their bank account.', 'By cash at the housing corporation office.', 'By iDEAL online each month.'],
          correctIndex: 1,
          explanation: '"Automatische incasso van uw bankrekening" = automatic direct debit from your bank account.',
          topicArea: 'housing',
        },
        {
          id: 'a2r3-s6-q2',
          type: 'multiple-choice',
          question: 'Who is responsible for small repairs costing up to €100?',
          options: ['The housing corporation.', 'The building manager.', 'The tenant.', 'The municipality.'],
          correctIndex: 2,
          explanation: '"Kleine reparaties (tot €100,-) zijn uw eigen verantwoordelijkheid." = the tenant\'s responsibility.',
          topicArea: 'housing',
        },
        {
          id: 'a2r3-s6-q3',
          type: 'multiple-choice',
          question: 'Which pet is allowed in the apartment without special permission?',
          options: ['A large dog.', 'A cat or small dog.', 'Any animal is allowed.', 'No pets at all.'],
          correctIndex: 1,
          explanation: '"Één kat of één kleine hond is toegestaan." = one cat or one small dog is permitted.',
          topicArea: 'housing',
        },
      ],
    },
  ],
};
