import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IIListening1: ExamPracticeTest = {
  id: 'staatsexamen-nt2-ii-listening-1',
  examType: 'staatsexamen-nt2-ii',
  skill: 'listening',
  title: 'Staatsexamen NT2 Programma II – Luisteren (Oefening 1)',
  description:
    'Practice exam for the Luisteren (listening) component of the Staatsexamen NT2 Programma II (B2 level). Listen to spoken Dutch fragments — academic lectures, formal debates, news analyses, cultural discussions, and professional presentations — and answer comprehension questions. Each fragment can be played up to 2 times. All passages are read aloud using Dutch text-to-speech.',
  timeLimitMinutes: 50,
  passingScore: 60,
  totalQuestions: 25,
  sections: [
    // ── Fragment 1: Academische lezing over klimaatbeleid ──
    {
      id: 'nt2-ii-l1-s1',
      passageTitle: 'Fragment 1: Academische lezing – Klimaatbeleid en de rol van de overheid',
      passage:
        'Dames en heren, in deze lezing bespreek ik de vraag in hoeverre de overheid een sturende rol moet spelen bij de energietransitie. Er zijn twee dominante stromingen in het debat. De eerste stroming betoogt dat marktwerking onvoldoende is om de klimaatdoelen te halen, en dat de overheid via regelgeving en subsidies een actieve rol moet spelen. De tweede stroming stelt dat overheidsinterventie leidt tot inefficiëntie en verstoringen van de markt, en dat technologische innovatie het beste gedijt in een vrije markt. Empirisch onderzoek laat echter zien dat landen met een combinatie van strikte milieuregelgeving en gerichte innovatiesubsidies gemiddeld sneller hun CO2-uitstoot reduceren dan landen die volledig op marktwerking vertrouwen. Dit suggereert dat een hybride aanpak — waarbij de overheid kaders stelt maar bedrijven de vrijheid houdt om oplossingen te vinden — mogelijk de meest effectieve strategie is. Toch zijn er kritische kanttekeningen: wie bepaalt welke technologieën worden gesubsidieerd, en hoe voorkom je politieke beïnvloeding van die keuzes?',
      instructions: 'Luister naar de academische lezing en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l1-q1',
          type: 'multiple-choice',
          question: 'Wat is het centrale onderwerp van deze lezing?',
          options: [
            'De technologische ontwikkelingen in de energiesector',
            'De mate waarin de overheid een rol moet spelen bij de energietransitie',
            'De economische gevolgen van klimaatverandering',
            'De samenwerking tussen bedrijven en universiteiten',
          ],
          correctIndex: 1,
          explanation: '"in hoeverre de overheid een sturende rol moet spelen bij de energietransitie."',
          topicArea: 'climate-policy',
        },
        {
          id: 'nt2-ii-l1-q2',
          type: 'multiple-choice',
          question: 'Wat beweert de eerste stroming in het debat?',
          options: [
            'Dat technologische innovatie het beste gedijt in een vrije markt.',
            'Dat marktwerking onvoldoende is en de overheid actief moet ingrijpen.',
            'Dat internationale samenwerking de enige oplossing is.',
            'Dat bedrijven zelf verantwoordelijk zijn voor hun CO2-uitstoot.',
          ],
          correctIndex: 1,
          explanation: '"marktwerking onvoldoende is om de klimaatdoelen te halen, en dat de overheid via regelgeving en subsidies een actieve rol moet spelen."',
          topicArea: 'climate-policy',
        },
        {
          id: 'nt2-ii-l1-q3',
          type: 'multiple-choice',
          question: 'Wat blijkt uit het empirisch onderzoek dat in de lezing wordt aangehaald?',
          options: [
            'Landen met alleen marktwerking reduceren hun uitstoot het snelst.',
            'Er is geen verschil tussen landen met en zonder overheidsbeleid.',
            'Landen met strikte regelgeving én innovatiesubsidies reduceren hun uitstoot gemiddeld sneller.',
            'Subsidies leiden altijd tot verspilling van overheidsgeld.',
          ],
          correctIndex: 2,
          explanation: '"landen met een combinatie van strikte milieuregelgeving en gerichte innovatiesubsidies gemiddeld sneller hun CO2-uitstoot reduceren."',
          topicArea: 'climate-policy',
        },
        {
          id: 'nt2-ii-l1-q4',
          type: 'multiple-choice',
          question: 'Welke aanpak noemt de spreker als mogelijk de meest effectieve strategie?',
          options: [
            'Volledige nationalisatie van de energiesector',
            'Volledige vrijheid van de markt zonder overheidsbemoeienis',
            'Een hybride aanpak waarbij de overheid kaders stelt maar bedrijven vrij blijven',
            'Internationale wetgeving die alle landen gelijk behandelt',
          ],
          correctIndex: 2,
          explanation: '"een hybride aanpak — waarbij de overheid kaders stelt maar bedrijven de vrijheid houdt om oplossingen te vinden — mogelijk de meest effectieve strategie is."',
          topicArea: 'climate-policy',
        },
        {
          id: 'nt2-ii-l1-q5',
          type: 'true-false',
          question: 'De spreker presenteert de hybride aanpak als een volledig probleemloze oplossing.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Toch zijn er kritische kanttekeningen: wie bepaalt welke technologieën worden gesubsidieerd, en hoe voorkom je politieke beïnvloeding?" — the speaker raises critical concerns.',
          topicArea: 'climate-policy',
        },
      ],
    },

    // ── Fragment 2: Radiopanel over arbeidsmigratie ──
    {
      id: 'nt2-ii-l1-s2',
      passageTitle: 'Fragment 2: Radiopaneldiscussie – Arbeidsmigratie en de Nederlandse arbeidsmarkt',
      passage:
        'Presentator: Goedemiddag. In ons panel vandaag: econoom Pieter van Dam en socioloog Anke Brouwer. Pieter, u pleit voor een ruimhartiger beleid ten aanzien van arbeidsmigranten. Waarom? Van Dam: Simpel gezegd: zonder arbeidsmigranten functioneert onze economie niet. In de logistiek, de landbouw en de zorg zijn er structurele tekorten die we met de huidige beroepsbevolking niet kunnen opvullen. Brouwer: Maar Pieter, je abstraheert hier van de sociale kosten. Druk op de woningmarkt, verdringing van lager opgeleide Nederlanders en integratieproblemen zijn reële gevolgen die je niet zomaar kunt wegcijferen. Van Dam: Die zorgen snap ik, maar de oplossing is betere regulering, niet minder migratie. Je moet de schijnconstructies aanpakken waarbij arbeidsmigranten onderbetaald worden en in slechte omstandigheden leven. Brouwer: Daarin zijn we het eens: handhaving schiet tekort. Maar ik zou willen investeren in de mensen die hier al zijn — betere opleidingen en activering van inactieven — voordat je de grenzen verder openzet. Presentator: Een genuanceerd debat, zoals we dat van u beiden gewend zijn.',
      instructions: 'Luister naar de paneldiscussie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l1-q6',
          type: 'multiple-choice',
          question: 'Welk standpunt verdedigt econoom Van Dam?',
          options: [
            'Nederland moet de grenzen sluiten voor arbeidsmigranten.',
            'Arbeidsmigranten zijn onmisbaar voor de economie en het beleid moet ruimhartiger.',
            'Arbeidsmigranten moeten beter worden opgeleid voordat ze mogen werken.',
            'De lonen in Nederland zijn te hoog door arbeidsmigratie.',
          ],
          correctIndex: 1,
          explanation: '"zonder arbeidsmigranten functioneert onze economie niet" and "pleit voor een ruimhartiger beleid."',
          topicArea: 'labour-migration',
        },
        {
          id: 'nt2-ii-l1-q7',
          type: 'multiple-choice',
          question: 'Welke sociale kosten noemt socioloog Brouwer als bezwaar?',
          options: [
            'Hogere belastingen en minder overheidsuitgaven',
            'Druk op de woningmarkt, verdringing van lager opgeleiden en integratieproblemen',
            'Meer criminaliteit en sociale onrust',
            'Verlies van nationale identiteit en cultuur',
          ],
          correctIndex: 1,
          explanation: '"Druk op de woningmarkt, verdringing van lager opgeleide Nederlanders en integratieproblemen zijn reële gevolgen."',
          topicArea: 'labour-migration',
        },
        {
          id: 'nt2-ii-l1-q8',
          type: 'multiple-choice',
          question: 'Waarover zijn Van Dam en Brouwer het met elkaar eens?',
          options: [
            'Dat er minder arbeidsmigranten naar Nederland moeten komen',
            'Dat de overheid meer moet investeren in onderwijs',
            'Dat de handhaving tegen schijnconstructies tekortschiet',
            'Dat arbeidsmigratie de woningmarkt niet beïnvloedt',
          ],
          correctIndex: 2,
          explanation: '"Daarin zijn we het eens: handhaving schiet tekort."',
          topicArea: 'labour-migration',
        },
        {
          id: 'nt2-ii-l1-q9',
          type: 'multiple-choice',
          question: 'Wat stelt Brouwer voor als alternatief voor meer arbeidsmigratie?',
          options: [
            'Investeren in mensen die er al zijn via opleidingen en activering van inactieven',
            'Automatisering van werk in de landbouw en logistiek',
            'Samenwerking met andere EU-landen om arbeidsmigranten te verdelen',
            'Het verhogen van de minimumlonen om werk aantrekkelijker te maken',
          ],
          correctIndex: 0,
          explanation: '"ik zou willen investeren in de mensen die hier al zijn — betere opleidingen en activering van inactieven."',
          topicArea: 'labour-migration',
        },
        {
          id: 'nt2-ii-l1-q10',
          type: 'true-false',
          question: 'Van Dam vindt dat minder migratie de juiste oplossing is voor de gesignaleerde problemen.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"de oplossing is betere regulering, niet minder migratie." — Van Dam explicitly rejects reducing migration as the answer.',
          topicArea: 'labour-migration',
        },
      ],
    },

    // ── Fragment 3: Nieuwsanalyse over de volksgezondheidszorg ──
    {
      id: 'nt2-ii-l1-s3',
      passageTitle: 'Fragment 3: Nieuwsanalyse – De toekomst van de Nederlandse gezondheidszorg',
      passage:
        'In een uitgebreide analyse bespreekt verslaggever Nathalie Smit de uitdagingen waarmee de Nederlandse gezondheidszorg wordt geconfronteerd. Het stelsel staat onder druk door een combinatie van factoren: een vergrijzende bevolking, een toenemend personeelstekort en stijgende zorgkosten. Het CBS schat dat in 2040 één op de vier Nederlanders ouder is dan 65 jaar. Dit betekent een aanzienlijke toename van de vraag naar zorg, terwijl het aanbod van zorgprofessionals structureel achterblijft. Een recent rapport van het Rijksinstituut voor Volksgezondheid en Milieu, het RIVM, concludeert dat technologische innovaties zoals AI-diagnostiek en telegeneeskunde potentieel hebben om de druk op de sector te verlichten, maar dat de implementatie ervan traag verloopt vanwege regelgeving en weerstand binnen de sector zelf. Smit wijst er ook op dat de ongelijkheid in gezondheid toeneemt: mensen met een lagere sociaaleconomische status leven gemiddeld twaalf jaar minder in goede gezondheid dan mensen met een hoge status, een kloof die de afgelopen decennia nauwelijks is verkleind.',
      instructions: 'Luister naar de nieuwsanalyse en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l1-q11',
          type: 'multiple-choice',
          question: 'Welke drie factoren zetten de gezondheidszorg onder druk?',
          options: [
            'Vergrijzing, bezuinigingen en politieke onenigheid',
            'Vergrijzing, personeelstekort en stijgende zorgkosten',
            'Migratie, vergrijzing en bureaucratie',
            'Personeelstekort, bezuinigingen en technologische achterstand',
          ],
          correctIndex: 1,
          explanation: '"een vergrijzende bevolking, een toenemend personeelstekort en stijgende zorgkosten."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-ii-l1-q12',
          type: 'multiple-choice',
          question: 'Wat schat het CBS voor het jaar 2040?',
          options: [
            'Dat de bevolking met tien procent is gegroeid',
            'Dat één op de vier Nederlanders ouder is dan 65 jaar',
            'Dat het personeelstekort in de zorg is opgelost',
            'Dat de zorgkosten zijn verdubbeld',
          ],
          correctIndex: 1,
          explanation: '"in 2040 één op de vier Nederlanders ouder is dan 65 jaar."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-ii-l1-q13',
          type: 'multiple-choice',
          question: 'Waarom verloopt de implementatie van technologische innovaties traag?',
          options: [
            'Omdat de overheid er geen geld voor uittrekt',
            'Omdat de technologie nog niet goed genoeg werkt',
            'Vanwege regelgeving en weerstand binnen de sector zelf',
            'Omdat patiënten er geen vertrouwen in hebben',
          ],
          correctIndex: 2,
          explanation: '"de implementatie ervan traag verloopt vanwege regelgeving en weerstand binnen de sector zelf."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-ii-l1-q14',
          type: 'true-false',
          question: 'De kloof in gezondheid tussen hoge en lage sociaaleconomische groepen is de afgelopen decennia sterk verkleind.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"een kloof die de afgelopen decennia nauwelijks is verkleind" — the gap has barely narrowed.',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-ii-l1-q15',
          type: 'multiple-choice',
          question: 'Hoeveel jaar minder leven mensen met een lage sociaaleconomische status in goede gezondheid?',
          options: ['Vijf jaar', 'Acht jaar', 'Tien jaar', 'Twaalf jaar'],
          correctIndex: 3,
          explanation: '"mensen met een lagere sociaaleconomische status leven gemiddeld twaalf jaar minder in goede gezondheid."',
          topicArea: 'healthcare',
        },
      ],
    },

    // ── Fragment 4: Culturele discussie over de Nederlandse identiteit ──
    {
      id: 'nt2-ii-l1-s4',
      passageTitle: 'Fragment 4: Cultureel programma – Wat betekent het om Nederlands te zijn?',
      passage:
        'Presentatrice: In dit programma verkennen we de vraag: wat betekent het vandaag de dag om Nederlands te zijn? Historicus Kees Dijkstra, u heeft hier onderzoek naar gedaan. Dijkstra: Nederlandsheid is geen vaststaand concept. Het heeft door de eeuwen heen steeds een andere invulling gekregen. In de Gouden Eeuw was het sterk verbonden met handelsgeest en religieuze tolerantie. In de twintigste eeuw werd het gesymboliseerd door de verzorgingsstaat en poldermodel. Nu zien we een discussie over normen en waarden, over wat er van nieuwkomers verwacht mag worden en wat de kern is van de Nederlandse cultuur. Presentatrice: Is dat een gezonde discussie? Dijkstra: Absoluut, als die maar genuanceerd wordt gevoerd. Het gevaar is polarisatie: dat men óf een exclusief, etnisch gedefinieerde identiteit claimt, óf elke gedeelde identiteit ontkent. De kracht van Nederland is altijd geweest dat het een open, meervoudige identiteit heeft weten te combineren met een sterk gevoel van gemeenschappelijke waarden — zoals gelijkwaardigheid, vrijheid van meningsuiting en de rechtsstaat.',
      instructions: 'Luister naar de culturele discussie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l1-q16',
          type: 'multiple-choice',
          question: 'Met welke kenmerken werd Nederlandsheid in de Gouden Eeuw geassocieerd?',
          options: [
            'Sociale zekerheid en democratie',
            'Handelsgeest en religieuze tolerantie',
            'Militaire kracht en koloniale expansie',
            'Onderwijs en wetenschappelijke vooruitgang',
          ],
          correctIndex: 1,
          explanation: '"In de Gouden Eeuw was het sterk verbonden met handelsgeest en religieuze tolerantie."',
          topicArea: 'dutch-identity',
        },
        {
          id: 'nt2-ii-l1-q17',
          type: 'multiple-choice',
          question: 'Waarmee werd Nederlandsheid in de twintigste eeuw gesymboliseerd?',
          options: [
            'Handelsgeest en koloniale geschiedenis',
            'Religieuze tolerantie en multicultuur',
            'De verzorgingsstaat en het poldermodel',
            'Technologische innovatie en duurzaamheid',
          ],
          correctIndex: 2,
          explanation: '"In de twintigste eeuw werd het gesymboliseerd door de verzorgingsstaat en poldermodel."',
          topicArea: 'dutch-identity',
        },
        {
          id: 'nt2-ii-l1-q18',
          type: 'multiple-choice',
          question: 'Welk gevaar noemt Dijkstra bij de huidige discussie over identiteit?',
          options: [
            'Dat jongeren zich niet meer betrokken voelen bij de samenleving',
            'Dat nieuwkomers de Nederlandse cultuur niet willen overnemen',
            'Dat men óf een exclusief etnische identiteit claimt, óf elke gedeelde identiteit ontkent',
            'Dat politici te weinig aandacht besteden aan culturele vraagstukken',
          ],
          correctIndex: 2,
          explanation: '"Het gevaar is polarisatie: dat men óf een exclusief, etnisch gedefinieerde identiteit claimt, óf elke gedeelde identiteit ontkent."',
          topicArea: 'dutch-identity',
        },
        {
          id: 'nt2-ii-l1-q19',
          type: 'multiple-choice',
          question: 'Welke waarden noemt Dijkstra als kern van de gemeenschappelijke Nederlandse identiteit?',
          options: [
            'Plichtsbesef, zuinigheid en nuchterheid',
            'Gelijkwaardigheid, vrijheid van meningsuiting en de rechtsstaat',
            'Samenwerking, pragmatisme en handelsgeest',
            'Solidariteit, duurzaamheid en innovatie',
          ],
          correctIndex: 1,
          explanation: '"gelijkwaardigheid, vrijheid van meningsuiting en de rechtsstaat."',
          topicArea: 'dutch-identity',
        },
        {
          id: 'nt2-ii-l1-q20',
          type: 'true-false',
          question: 'Volgens Dijkstra is Nederlandsheid altijd een vaststaand en onveranderlijk concept geweest.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Nederlandsheid is geen vaststaand concept. Het heeft door de eeuwen heen steeds een andere invulling gekregen."',
          topicArea: 'dutch-identity',
        },
      ],
    },

    // ── Fragment 5: Professionele presentatie over duurzaamheid in het bedrijfsleven ──
    {
      id: 'nt2-ii-l1-s5',
      passageTitle: 'Fragment 5: Bedrijfspresentatie – Duurzaam ondernemen als strategisch voordeel',
      passage:
        'Goedemiddag. Als hoofd duurzaamheid van een middelgroot productiebedrijf wil ik vandaag een case study presenteren over hoe wij duurzaamheid hebben omgezet van een kostenpost naar een strategisch voordeel. Vijf jaar geleden waren onze duurzaamheidsinitiatieven voornamelijk gedreven door regulering en reputatiemanagement. Wij investeerden in zonnepanelen en energiebesparing om te voldoen aan wetgeving en om negatieve publiciteit te vermijden. De omslag kwam toen wij begonnen te meten wat duurzaamheid ons daadwerkelijk opleverde. Onze energierekening daalde met veertig procent in drie jaar. Door circulaire productieprocessen verminderden we onze grondstoffenkosten met vijfentwintig procent. Maar het meest verrassende resultaat was het effect op onze medewerkers en klanten. Onderzoek onder ons personeel liet zien dat werknemers die duurzaamheid als kernwaarde herkennen in hun werkgever, gemiddeld dertig procent langer in dienst blijven. En onze B2B-klanten — met name grote retailers — stellen steeds vaker duurzaamheidseisen als voorwaarde voor samenwerking. De conclusie is duidelijk: duurzaam ondernemen is niet langer een luxe, maar een randvoorwaarde voor langetermijnsucces.',
      instructions: 'Luister naar de bedrijfspresentatie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l1-q21',
          type: 'multiple-choice',
          question: 'Wat was vijf jaar geleden de voornaamste drijfveer voor duurzaamheidsinitiatieven bij dit bedrijf?',
          options: [
            'Het willen bijdragen aan een betere wereld',
            'Regelgeving en reputatiemanagement',
            'Druk van aandeelhouders en investeerders',
            'Vraag van klanten naar duurzame producten',
          ],
          correctIndex: 1,
          explanation: '"voornamelijk gedreven door regulering en reputatiemanagement."',
          topicArea: 'sustainability-business',
        },
        {
          id: 'nt2-ii-l1-q22',
          type: 'multiple-choice',
          question: 'Waardoor veranderde de kijk van het bedrijf op duurzaamheid?',
          options: [
            'Doordat de overheid nieuwe subsidies beschikbaar stelde',
            'Doordat concurrenten duurzamer werden',
            'Doordat men begon te meten wat duurzaamheid daadwerkelijk opleverde',
            'Doordat klanten klaagden over de producten',
          ],
          correctIndex: 2,
          explanation: '"De omslag kwam toen wij begonnen te meten wat duurzaamheid ons daadwerkelijk opleverde."',
          topicArea: 'sustainability-business',
        },
        {
          id: 'nt2-ii-l1-q23',
          type: 'multiple-choice',
          question: 'Met hoeveel procent daalden de grondstoffenkosten door circulaire productieprocessen?',
          options: ['Tien procent', 'Vijftien procent', 'Vijfentwintig procent', 'Veertig procent'],
          correctIndex: 2,
          explanation: '"Door circulaire productieprocessen verminderden we onze grondstoffenkosten met vijfentwintig procent."',
          topicArea: 'sustainability-business',
        },
        {
          id: 'nt2-ii-l1-q24',
          type: 'multiple-choice',
          question: 'Wat bleek het meest verrassende resultaat van de duurzaamheidsinvesteringen?',
          options: [
            'De daling van de energierekening',
            'De verlaging van de grondstoffenkosten',
            'Het effect op medewerkers en klanten',
            'De positieve aandacht van de media',
          ],
          correctIndex: 2,
          explanation: '"Maar het meest verrassende resultaat was het effect op onze medewerkers en klanten."',
          topicArea: 'sustainability-business',
        },
        {
          id: 'nt2-ii-l1-q25',
          type: 'true-false',
          question: 'Werknemers die duurzaamheid als kernwaarde herkennen bij hun werkgever blijven gemiddeld langer in dienst.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 0,
          explanation: '"werknemers die duurzaamheid als kernwaarde herkennen in hun werkgever, gemiddeld dertig procent langer in dienst blijven."',
          topicArea: 'sustainability-business',
        },
      ],
    },
  ],
};
