import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IIListening2: ExamPracticeTest = {
  id: 'staatsexamen-nt2-ii-listening-2',
  examType: 'staatsexamen-nt2-ii',
  skill: 'listening',
  title: 'Staatsexamen NT2 Programma II – Luisteren (Oefening 2)',
  description:
    'Practice exam for the Luisteren (listening) component of the Staatsexamen NT2 Programma II (B2 level). Listen to spoken Dutch fragments — academic lectures, formal debates, news analyses, cultural discussions, and professional presentations — and answer comprehension questions. Each fragment can be played up to 2 times. All passages are read aloud using Dutch text-to-speech.',
  timeLimitMinutes: 50,
  passingScore: 60,
  totalQuestions: 25,
  sections: [
    // ── Fragment 1: Academische lezing over migratie ──
    {
      id: 'nt2-ii-l2-s1',
      passageTitle: 'Fragment 1: Academische lezing – Migratie en economische groei',
      passage:
        'Geachte aanwezigen, in deze lezing wil ik een nuancering aanbrengen op het publieke debat over arbeidsmigratie. Vaak wordt migratie gepresenteerd als een last voor de samenleving, maar het empirische bewijs wijst in een andere richting. Economen van het CPB hebben vastgesteld dat arbeidsmigranten per saldo netto bijdragen aan de Nederlandse economie: zij vullen tekorten in sectoren zoals de zorg, de landbouw en de bouw, betalen belasting en sociale premies, en stimuleren als consument de binnenlandse vraag. De netto-bijdrage hangt echter sterk af van het opleidingsniveau en de mate van arbeidsmarktintegratie. Hoogopgeleide migranten dragen significant meer bij dan laagopgeleide migranten, waarbij de laatste groep vaker een beroep doet op sociale voorzieningen. Een doeltreffend migratiebeleid zou zich dus moeten richten op snelle integratie in de arbeidsmarkt, ongeacht het opleidingsniveau. De vraag is dan ook niet óf migratie economisch wenselijk is, maar welk type migratie en welk integratiebeleid de beste maatschappelijke uitkomsten genereert.',
      instructions: 'Luister naar de academische lezing en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l2-q1',
          type: 'multiple-choice',
          question: 'Wat is de centrale stelling van de spreker over arbeidsmigratie?',
          options: [
            'Migratie is een zware last voor de Nederlandse samenleving.',
            'Arbeidsmigranten dragen per saldo netto bij aan de Nederlandse economie.',
            'Migratie moet worden beperkt vanwege de druk op sociale voorzieningen.',
            'Alleen hoogopgeleide migranten zouden welkom moeten zijn.',
          ],
          correctIndex: 1,
          explanation: '"arbeidsmigranten per saldo netto bijdragen aan de Nederlandse economie."',
          topicArea: 'society',
        },
        {
          id: 'nt2-ii-l2-q2',
          type: 'multiple-choice',
          question: 'In welke sectoren vullen arbeidsmigranten tekorten op, volgens de lezing?',
          options: [
            'Financiën, IT en onderwijs',
            'Zorg, landbouw en bouw',
            'Transport, media en toerisme',
            'Overheid, juridische diensten en politie',
          ],
          correctIndex: 1,
          explanation: '"zij vullen tekorten in sectoren zoals de zorg, de landbouw en de bouw."',
          topicArea: 'society',
        },
        {
          id: 'nt2-ii-l2-q3',
          type: 'multiple-choice',
          question: 'Waarvan hangt de netto-bijdrage van migranten sterk af?',
          options: [
            'Het land van herkomst en de religie',
            'Het opleidingsniveau en de mate van arbeidsmarktintegratie',
            'De leeftijd bij aankomst en de gezinsgrootte',
            'De verblijfsduur en het inkomen',
          ],
          correctIndex: 1,
          explanation: '"De netto-bijdrage hangt echter sterk af van het opleidingsniveau en de mate van arbeidsmarktintegratie."',
          topicArea: 'society',
        },
        {
          id: 'nt2-ii-l2-q4',
          type: 'true-false',
          question: 'Laagopgeleide migranten doen vaker een beroep op sociale voorzieningen dan hoogopgeleide migranten.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 0,
          explanation: '"waarbij de laatste groep vaker een beroep doet op sociale voorzieningen" — the last group refers to laagopgeleide migranten.',
          topicArea: 'society',
        },
        {
          id: 'nt2-ii-l2-q5',
          type: 'multiple-choice',
          question: 'Wat concludeert de spreker over de centrale vraag in het migratiedebat?',
          options: [
            'De vraag is of migratie economisch wenselijk is.',
            'De vraag is welk type migratie en welk integratiebeleid de beste uitkomsten geeft.',
            'De vraag is hoe migratie beperkt kan worden.',
            'De vraag is hoe migranten sneller kunnen worden teruggestuurd.',
          ],
          correctIndex: 1,
          explanation: '"De vraag is dan ook niet óf migratie economisch wenselijk is, maar welk type migratie en welk integratiebeleid de beste maatschappelijke uitkomsten genereert."',
          topicArea: 'society',
        },
      ],
    },

    // ── Fragment 2: Radiopanel over sociale media ──
    {
      id: 'nt2-ii-l2-s2',
      passageTitle: 'Fragment 2: Radiopaneldiscussie – Sociale media en democratie',
      passage:
        'Presentator: We bespreken vandaag de invloed van sociale media op de democratie. Ik heb twee gasten: mediawetenschapper Annelies de Vries en politicoloog Marc Janssen. Annelies, u bent kritisch. De Vries: Ja. Sociale media versterken polarisatie door gebruikers in een filterbubbel te plaatsen — een omgeving waar ze alleen informatie zien die hun bestaande overtuigingen bevestigt. Dit bevordert extreme standpunten en bemoeilijkt genuanceerd debat. Janssen: Ik ben het daar niet mee eens. Sociale media bieden ook ongekende mogelijkheden voor politieke participatie. Burgers die voorheen geen stem hadden, kunnen nu mobiliseren, petities starten en rechtstreeks met politici communiceren. De Vries: Maar desinformatie verspreidt zich op sociale media veel sneller dan correcties. Onderzoek toont aan dat nepnieuws zes keer sneller viraal gaat dan correcte informatie. Dat is een fundamenteel probleem voor de kwaliteit van het democratisch debat. Janssen: Eens dat desinformatie een probleem is. Maar de oplossing is betere mediawijsheid, niet het beperken van platforms. Presentator: Dank u beiden.',
      instructions: 'Luister naar de discussie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l2-q6',
          type: 'multiple-choice',
          question: 'Wat bedoelt De Vries met een "filterbubbel"?',
          options: [
            'Een technisch filter dat ongepaste content blokkeert.',
            'Een omgeving waar gebruikers alleen informatie zien die hun bestaande overtuigingen bevestigt.',
            'Een algoritme dat nepnieuws detecteert.',
            'Een privacyinstelling op sociale media.',
          ],
          correctIndex: 1,
          explanation: '"een omgeving waar ze alleen informatie zien die hun bestaande overtuigingen bevestigt."',
          topicArea: 'media-society',
        },
        {
          id: 'nt2-ii-l2-q7',
          type: 'multiple-choice',
          question: 'Welk positief aspect van sociale media noemt Janssen?',
          options: [
            'Sociale media maken nieuws sneller en betrouwbaarder.',
            'Burgers zonder politieke stem kunnen nu mobiliseren en petities starten.',
            'Sociale media verminderen de polarisatie in de samenleving.',
            'Politici worden beter gecontroleerd door journalisten op sociale media.',
          ],
          correctIndex: 1,
          explanation: '"Burgers die voorheen geen stem hadden, kunnen nu mobiliseren, petities starten en rechtstreeks met politici communiceren."',
          topicArea: 'media-society',
        },
        {
          id: 'nt2-ii-l2-q8',
          type: 'multiple-choice',
          question: 'Hoe veel sneller verspreidt nepnieuws zich dan correcte informatie?',
          options: ['Twee keer', 'Vier keer', 'Zes keer', 'Tien keer'],
          correctIndex: 2,
          explanation: '"nepnieuws zes keer sneller viraal gaat dan correcte informatie."',
          topicArea: 'media-society',
        },
        {
          id: 'nt2-ii-l2-q9',
          type: 'multiple-choice',
          question: 'Wat stelt Janssen voor als oplossing voor desinformatie?',
          options: [
            'Sociale mediaplatforms verbieden.',
            'Strengere wetgeving voor techbedrijven.',
            'Betere mediawijsheid bij gebruikers.',
            'Meer controle door journalisten.',
          ],
          correctIndex: 2,
          explanation: '"de oplossing is betere mediawijsheid, niet het beperken van platforms."',
          topicArea: 'media-society',
        },
        {
          id: 'nt2-ii-l2-q10',
          type: 'true-false',
          question: 'Janssen is het volledig oneens met De Vries dat desinformatie een probleem is.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Eens dat desinformatie een probleem is." — Janssen agrees desinformation is a problem, but disagrees on the solution.',
          topicArea: 'media-society',
        },
      ],
    },

    // ── Fragment 3: Culturele lezing over Nederlandse identiteit ──
    {
      id: 'nt2-ii-l2-s3',
      passageTitle: 'Fragment 3: Culturele lezing – Nederlandse identiteit in verandering',
      passage:
        'De Nederlandse identiteit is altijd meervoudig en dynamisch geweest. Nederland is historisch een handelsland, gewend aan contact met andere culturen. Toch zien we de afgelopen decennia een groeiende spanning tussen de open, pluralistische zelfopvatting van Nederland als tolerant land en een toenemend verlangen naar culturele homogeniteit. Socioloog Rineke van Daalen stelt dat dit geen typisch Nederlands verschijnsel is, maar een brede westerse reactie op globalisering en immigratie. Wanneer de samenleving snel verandert, zoeken mensen houvast in een geïdealiseerde versie van het verleden. Dit wordt soms "nostalgisch nationalisme" genoemd. Van Daalen benadrukt echter dat identiteit altijd in beweging is. De Nederlandse taal, normen en tradities zijn zelf het product van eeuwen van culturele uitwisseling. Het idee van een statische, oorspronkelijke Nederlandse cultuur is dan ook een historische constructie. De uitdaging voor de samenleving is hoe men een gedeeld fundament kan creëren dat ruimte biedt aan diversiteit zonder de sociale cohesie te ondermijnen.',
      instructions: 'Luister naar de lezing en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l2-q11',
          type: 'multiple-choice',
          question: 'Welke spanning beschrijft de lezing over de Nederlandse identiteit?',
          options: [
            'Tussen jong en oud in de Nederlandse samenleving.',
            'Tussen de open, pluralistische zelfopvatting en een verlangen naar culturele homogeniteit.',
            'Tussen de rijke en de arme bevolking.',
            'Tussen stedelijke en landelijke gebieden.',
          ],
          correctIndex: 1,
          explanation: '"een groeiende spanning tussen de open, pluralistische zelfopvatting van Nederland als tolerant land en een toenemend verlangen naar culturele homogeniteit."',
          topicArea: 'culture-identity',
        },
        {
          id: 'nt2-ii-l2-q12',
          type: 'multiple-choice',
          question: 'Wat bedoelt Van Daalen met "nostalgisch nationalisme"?',
          options: [
            'Trots op historische militaire overwinningen.',
            'Het zoeken naar houvast in een geïdealiseerde versie van het verleden bij snelle maatschappelijke verandering.',
            'Het promoten van de Nederlandse taal in het buitenland.',
            'Verzet tegen Europese integratie.',
          ],
          correctIndex: 1,
          explanation: '"Wanneer de samenleving snel verandert, zoeken mensen houvast in een geïdealiseerde versie van het verleden. Dit wordt soms \'nostalgisch nationalisme\' genoemd."',
          topicArea: 'culture-identity',
        },
        {
          id: 'nt2-ii-l2-q13',
          type: 'true-false',
          question: 'Volgens Van Daalen is de Nederlandse cultuur altijd statisch en onveranderd geweest.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"De Nederlandse taal, normen en tradities zijn zelf het product van eeuwen van culturele uitwisseling." — the opposite is true.',
          topicArea: 'culture-identity',
        },
        {
          id: 'nt2-ii-l2-q14',
          type: 'multiple-choice',
          question: 'Wat is de uitdaging voor de samenleving volgens de lezing?',
          options: [
            'Immigratie stoppen om de Nederlandse cultuur te beschermen.',
            'Een gedeeld fundament creëren dat ruimte biedt aan diversiteit zonder de cohesie te ondermijnen.',
            'De Nederlandse taal verplicht stellen voor alle inwoners.',
            'Meer investeren in culturele instellingen.',
          ],
          correctIndex: 1,
          explanation: '"De uitdaging voor de samenleving is hoe men een gedeeld fundament kan creëren dat ruimte biedt aan diversiteit zonder de sociale cohesie te ondermijnen."',
          topicArea: 'culture-identity',
        },
        {
          id: 'nt2-ii-l2-q15',
          type: 'multiple-choice',
          question: 'Hoe omschrijft Van Daalen het idee van een "oorspronkelijke Nederlandse cultuur"?',
          options: [
            'Als een waardevolle erfenis die beschermd moet worden.',
            'Als een historische constructie.',
            'Als een realiteit die dreigt te verdwijnen.',
            'Als een begrip dat alleen door nationalisten wordt gebruikt.',
          ],
          correctIndex: 1,
          explanation: '"Het idee van een statische, oorspronkelijke Nederlandse cultuur is dan ook een historische constructie."',
          topicArea: 'culture-identity',
        },
      ],
    },

    // ── Fragment 4: Nieuwsanalyse over de woningmarkt ──
    {
      id: 'nt2-ii-l2-s4',
      passageTitle: 'Fragment 4: Nieuwsanalyse – Oplossingen voor de woningcrisis',
      passage:
        'De Nederlandse woningmarkt staat al jaren onder druk. Het woningtekort wordt geraamd op zo\'n driehonderdnegentigduizend woningen. Verschillende partijen bieden oplossingen, maar economen zijn het onderling niet eens. De bouwlobby pleit voor snellere vergunningverlening en minder regelgeving, zodat marktpartijen sneller kunnen bouwen. Critici wijzen erop dat de markt zich primair richt op dure koopwoningen en dat de sociale woningbouwsector structureel ondergefinancierd is. Een tweede debat gaat over tijdelijke huurcontracten. Voorstanders stellen dat flexibele contracten de doorstroming bevorderen; tegenstanders zeggen dat ze huurders in een onzekere positie brengen. Een derde discussiepunt is de grond: gemeenten die grond verkopen aan de hoogste bieder, maken betaalbare woningbouw moeilijker. Sommige gemeenten experimenteren met erfpachtconstructies, waarbij de grond eigendom blijft van de gemeente. Breed gedragen is de conclusie dat geen enkele maatregel op zichzelf voldoende is — een integrale aanpak is noodzakelijk.',
      instructions: 'Luister naar de analyse en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l2-q16',
          type: 'multiple-choice',
          question: 'Hoe groot is het woningtekort in Nederland?',
          options: [
            'Zo\'n honderdduizend woningen',
            'Zo\'n tweehonderdduizend woningen',
            'Zo\'n driehonderdnegentigduizend woningen',
            'Zo\'n vijfhonderdduizend woningen',
          ],
          correctIndex: 2,
          explanation: '"Het woningtekort wordt geraamd op zo\'n driehonderdnegentigduizend woningen."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-ii-l2-q17',
          type: 'multiple-choice',
          question: 'Wat is het bezwaar van critici tegen de bouwlobby?',
          options: [
            'De bouwlobby wil te veel sociale woningen bouwen.',
            'De markt richt zich primair op dure koopwoningen en de sociale sector is ondergefinancierd.',
            'Snellere vergunningverlening leidt tot slechte bouwkwaliteit.',
            'De bouwlobby heeft te veel politieke invloed.',
          ],
          correctIndex: 1,
          explanation: '"de markt zich primair richt op dure koopwoningen en dat de sociale woningbouwsector structureel ondergefinancierd is."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-ii-l2-q18',
          type: 'multiple-choice',
          question: 'Wat is een erfpachtconstructie?',
          options: [
            'Een hypotheekvorm waarbij de rente lager is.',
            'Een constructie waarbij de gemeente eigenaar blijft van de grond.',
            'Een subsidie voor sociale huurwoningen.',
            'Een tijdelijk huurcontract voor starters.',
          ],
          correctIndex: 1,
          explanation: '"waarbij de grond eigendom blijft van de gemeente."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-ii-l2-q19',
          type: 'true-false',
          question: 'Alle economen zijn het eens over de beste oplossing voor de woningcrisis.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"maar economen zijn het onderling niet eens."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-ii-l2-q20',
          type: 'multiple-choice',
          question: 'Wat is de breed gedragen conclusie in de analyse?',
          options: [
            'Alleen meer bouwen lost het probleem op.',
            'De huurmarkt moet volledig worden geliberaliseerd.',
            'Geen enkele maatregel op zichzelf is voldoende — een integrale aanpak is noodzakelijk.',
            'De overheid moet alle woningbouw overnemen.',
          ],
          correctIndex: 2,
          explanation: '"Breed gedragen is de conclusie dat geen enkele maatregel op zichzelf voldoende is — een integrale aanpak is noodzakelijk."',
          topicArea: 'housing',
        },
      ],
    },

    // ── Fragment 5: Debat over de rol van kunst in de samenleving ──
    {
      id: 'nt2-ii-l2-s5',
      passageTitle: 'Fragment 5: Debat – Publieke financiering van kunst en cultuur',
      passage:
        'Debatleider: Vanavond debatteren we over de stelling: "De overheid moet stoppen met het subsidiëren van elitaire kunst." Ik geef eerst het woord aan voorstander Hanna Berg. Berg: Wij leven in een tijd van grote bezuinigingen op publieke voorzieningen. Het is moeilijk te verantwoorden dat belastinggeld gaat naar opera en ballet, terwijl de toegang tot deze kunstvorm beperkt blijft tot een kleine, welgestelde groep. Tegenstander Ibrahim Musa, uw reactie? Musa: Ik ben het fundamenteel oneens. Ten eerste is het label "elitair" misleidend: veel theaterproducties en musea richten zich actief op nieuwe en diverse publieksgroepen. Ten tweede heeft cultuur een maatschappelijke functie die verder gaat dan entertainment — het stimuleert kritisch denken, versterkt identiteit en bevordert sociale cohesie. Ten derde zijn culturele instellingen economisch belangrijk voor steden: ze trekken toeristen en versterken het vestigingsklimaat voor bedrijven. Berg: Maar waarom moet de belastingbetaler daarvoor betalen? Particuliere sponsors en ticketverkoop kunnen dat ook financieren. Musa: De ervaring in landen waar de overheidssteun sterk is teruggelopen, laat zien dat artistieke diversiteit en experimenten verdwijnen ten gunste van commercieel aantrekkelijke producties.',
      instructions: 'Luister naar het debat en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-ii-l2-q21',
          type: 'multiple-choice',
          question: 'Wat is het standpunt van Hanna Berg?',
          options: [
            'De overheid moet meer geld besteden aan kunst en cultuur.',
            'De overheid moet stoppen met het subsidiëren van elitaire kunst.',
            'Kunst moet alleen gefinancierd worden door de gemeente.',
            'Opera en ballet moeten gratis toegankelijk zijn voor iedereen.',
          ],
          correctIndex: 1,
          explanation: 'Berg is the "voorstander" of the stelling: "De overheid moet stoppen met het subsidiëren van elitaire kunst."',
          topicArea: 'culture-society',
        },
        {
          id: 'nt2-ii-l2-q22',
          type: 'multiple-choice',
          question: 'Waarom noemt Musa het label "elitair" misleidend?',
          options: [
            'Omdat opera en ballet altijd goedkoop zijn.',
            'Omdat veel theaterproducties en musea zich actief richten op nieuwe en diverse publieksgroepen.',
            'Omdat rijke mensen ook belasting betalen.',
            'Omdat cultuur altijd voor iedereen toegankelijk is.',
          ],
          correctIndex: 1,
          explanation: '"veel theaterproducties en musea richten zich actief op nieuwe en diverse publieksgroepen."',
          topicArea: 'culture-society',
        },
        {
          id: 'nt2-ii-l2-q23',
          type: 'multiple-choice',
          question: 'Welk economisch argument geeft Musa voor subsidies aan cultuur?',
          options: [
            'Cultuur zorgt voor meer werkgelegenheid dan industrie.',
            'Culturele instellingen trekken toeristen en versterken het vestigingsklimaat voor bedrijven.',
            'Gesubsidieerde kunst is goedkoper te produceren.',
            'Cultuur vermindert de zorgkosten in de samenleving.',
          ],
          correctIndex: 1,
          explanation: '"ze trekken toeristen en versterken het vestigingsklimaat voor bedrijven."',
          topicArea: 'culture-society',
        },
        {
          id: 'nt2-ii-l2-q24',
          type: 'multiple-choice',
          question: 'Wat gebeurt er volgens Musa in landen waar overheidssteun sterk is teruggelopen?',
          options: [
            'Kunst wordt populairder bij het grote publiek.',
            'Artistieke diversiteit en experimenten verdwijnen ten gunste van commerciële producties.',
            'Particuliere sponsors nemen de financiering volledig over.',
            'De kwaliteit van kunst verbetert door marktwerking.',
          ],
          correctIndex: 1,
          explanation: '"artistieke diversiteit en experimenten verdwijnen ten gunste van commercieel aantrekkelijke producties."',
          topicArea: 'culture-society',
        },
        {
          id: 'nt2-ii-l2-q25',
          type: 'true-false',
          question: 'Hanna Berg stelt dat kunstsubsidies kunnen worden vervangen door particuliere sponsoring en ticketverkoop.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 0,
          explanation: '"Particuliere sponsors en ticketverkoop kunnen dat ook financieren."',
          topicArea: 'culture-society',
        },
      ],
    },
  ],
};
