import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IIReading4: ExamPracticeTest = {
  id: 'staatsexamen-nt2-ii-reading-4',
  examType: 'staatsexamen-nt2-ii',
  skill: 'reading',
  title: 'Staatsexamen NT2 Programma II – Lezen (Oefening 4)',
  description:
    'Practice reading exam at B2 level. Read complex analytical, academic and formal Dutch texts and answer detailed comprehension questions. Topics: artificial intelligence and the labour market, judicial independence, demographic change, food system sustainability, and corporate governance.',
  timeLimitMinutes: 100,
  passingScore: 60,
  totalQuestions: 35,
  sections: [
    {
      id: 'nt2-ii-r4-s1',
      passageTitle: 'Opinie: Kunstmatige intelligentie en de toekomst van werk',
      passage:
        'De opkomst van kunstmatige intelligentie (AI) roept fundamentele vragen op over de toekomst van de arbeidsmarkt. Optimisten wijzen erop dat technologische revoluties in het verleden — van de stoommachine tot de computer — uiteindelijk meer banen creëerden dan ze vernietigden. Critici stellen echter dat AI van een andere orde is: het vervangt niet alleen fysieke arbeid, maar ook cognitieve taken die voorheen als mensenwerk golden.\n\nRecent onderzoek van het Centraal Planbureau (CPB) suggereert dat ongeveer 30% van de Nederlandse banen een hoog risico loopt op automatisering in de komende twintig jaar. Beroepen met routinematige taken — in de administratie, logistiek en financiële dienstverlening — zijn het meest kwetsbaar. Tegelijkertijd ontstaan nieuwe functies in AI-ontwikkeling, data-analyse en mensgerichte diensten.\n\nVanuit beleidsoogpunt zijn er twee centrale uitdagingen. Ten eerste: hoe zorgen we dat de voordelen van AI breed worden gedeeld in plaats van geconcentreerd bij aandeelhouders en technologiebedrijven? Ten tweede: hoe kunnen we werknemers tijdig omscholen zodat zij kunnen meebewegen met de veranderende arbeidsmarkt? Het antwoord op beide vragen vereist een actieve rol van zowel de overheid als werkgevers en vakbonden.',
      instructions: 'Read the opinion article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s1-q1',
          type: 'multiple-choice',
          question: 'What argument do optimists make about AI and employment?',
          options: [
            'AI will only affect low-skilled jobs, leaving most workers safe.',
            'Past technological revolutions ultimately created more jobs than they destroyed.',
            'AI will reduce inequality because everyone will benefit equally.',
            'The Netherlands is too small to be significantly affected by AI.',
          ],
          correctIndex: 1,
          explanation: '"Technologische revoluties in het verleden … uiteindelijk meer banen creëerden dan ze vernietigden."',
          topicArea: 'ai-labour',
        },
        {
          id: 'nt2-ii-r4-s1-q2',
          type: 'multiple-choice',
          question: 'Why do critics consider AI different from previous technological revolutions?',
          options: [
            'AI is much more expensive to implement.',
            'AI replaces not only physical labour but also cognitive tasks previously considered human work.',
            'AI develops too slowly to have a real impact.',
            'AI is only used in large multinationals.',
          ],
          correctIndex: 1,
          explanation: '"AI … vervangt niet alleen fysieke arbeid, maar ook cognitieve taken die voorheen als mensenwerk golden."',
          topicArea: 'ai-labour',
        },
        {
          id: 'nt2-ii-r4-s1-q3',
          type: 'multiple-choice',
          question: 'According to CPB research, what percentage of Dutch jobs face high risk of automation?',
          options: ['About 10%', 'About 20%', 'About 30%', 'About 50%'],
          correctIndex: 2,
          explanation: '"Ongeveer 30% van de Nederlandse banen een hoog risico loopt op automatisering."',
          topicArea: 'ai-labour',
        },
        {
          id: 'nt2-ii-r4-s1-q4',
          type: 'multiple-choice',
          question: 'What is identified as one of the two central policy challenges?',
          options: [
            'How to prevent companies from using AI at all.',
            'How to ensure the benefits of AI are widely shared rather than concentrated at shareholders.',
            'How to slow the development of AI technology.',
            'How to attract more AI companies to the Netherlands.',
          ],
          correctIndex: 1,
          explanation: '"Hoe zorgen we dat de voordelen van AI breed worden gedeeld in plaats van geconcentreerd bij aandeelhouders en technologiebedrijven?"',
          topicArea: 'ai-labour',
        },
        {
          id: 'nt2-ii-r4-s1-q5',
          type: 'multiple-choice',
          question: 'What does the article say about new jobs emerging from AI?',
          options: [
            'No new jobs will be created — only existing ones will be lost.',
            'New roles will emerge in AI development, data analysis and people-focused services.',
            'Only highly educated people will find new jobs.',
            'New jobs will only appear abroad, not in the Netherlands.',
          ],
          correctIndex: 1,
          explanation: '"Tegelijkertijd ontstaan nieuwe functies in AI-ontwikkeling, data-analyse en mensgerichte diensten."',
          topicArea: 'ai-labour',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s2',
      passageTitle: 'Academisch artikel: De onafhankelijkheid van de rechterlijke macht',
      passage:
        'Een onafhankelijke rechterlijke macht is een hoeksteen van de rechtsstaat. In een democratie is het essentieel dat rechters vrij zijn van politieke beïnvloeding bij het doen van uitspraken. Dit principe is verankerd in de Nederlandse Grondwet en in internationale verdragen als het Europees Verdrag voor de Rechten van de Mens (EVRM).\n\nDe benoeming van rechters in Nederland verloopt via een onafhankelijke selectieprocedure. Rechters worden benoemd bij koninklijk besluit op voordracht van de Hoge Raad, niet door de politiek gekozen overheid. Dit verschilt van landen waar rechters door de wetgevende macht worden benoemd, wat risico op politisering met zich meebrengt.\n\nToch zijn er ook in Nederland discussies over de verhouding tussen rechter en politiek. Wanneer rechters uitspraken doen die overheidsbeleid terugdraaien — zoals bij het Urgenda-klimaatvonnis — spreken critici van rechterlijk activisme. Voorstanders stellen dat dit juist de rechtsstaat in werking toont: een onafhankelijke rechter die de overheid aan haar eigen normen houdt.\n\nInternationale organisaties als de Venetiëcommissie van de Raad van Europa bewaken de rechtsstaatnormen in de EU-lidstaten. Recente zorgen betreffen landen waar politieke partijen de samenstelling van de rechterlijke macht proberen te beïnvloeden.',
      instructions: 'Read the academic article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s2-q1',
          type: 'multiple-choice',
          question: 'Why is judicial independence considered essential in a democracy?',
          options: [
            'Because judges need to earn high salaries without political interference.',
            'Because judges must be free from political influence when making rulings.',
            'Because courts must be more powerful than the government.',
            'Because international treaties require judges to be appointed by the EU.',
          ],
          correctIndex: 1,
          explanation: '"Het is essentieel dat rechters vrij zijn van politieke beïnvloeding bij het doen van uitspraken."',
          topicArea: 'rule-of-law',
        },
        {
          id: 'nt2-ii-r4-s2-q2',
          type: 'multiple-choice',
          question: 'How are judges appointed in the Netherlands?',
          options: [
            'By direct election by citizens.',
            'By the parliament.',
            'By royal decree on the recommendation of the Hoge Raad, not by elected politicians.',
            'By the Prime Minister and the Minister of Justice.',
          ],
          correctIndex: 2,
          explanation: '"Rechters worden benoemd bij koninklijk besluit op voordracht van de Hoge Raad, niet door de politiek gekozen overheid."',
          topicArea: 'rule-of-law',
        },
        {
          id: 'nt2-ii-r4-s2-q3',
          type: 'multiple-choice',
          question: 'What is meant by "rechterlijk activisme" in the context of the article?',
          options: [
            'Judges who campaign for political parties.',
            'Judges who physically protest against government policy.',
            'Critics\' term for when courts overturn government policy through rulings.',
            'A movement within the Dutch judiciary to speed up court proceedings.',
          ],
          correctIndex: 2,
          explanation: '"Wanneer rechters uitspraken doen die overheidsbeleid terugdraaien … spreken critici van rechterlijk activisme."',
          topicArea: 'rule-of-law',
        },
        {
          id: 'nt2-ii-r4-s2-q4',
          type: 'multiple-choice',
          question: 'What do supporters of judicial rulings against the government argue?',
          options: [
            'That courts should have more power than the government.',
            'That this demonstrates the rule of law working — an independent judge holding the government to its own standards.',
            'That governments should always follow judicial advice.',
            'That the EVRM must be revised to give judges more powers.',
          ],
          correctIndex: 1,
          explanation: '"Dit juist de rechtsstaat in werking toont: een onafhankelijke rechter die de overheid aan haar eigen normen houdt."',
          topicArea: 'rule-of-law',
        },
        {
          id: 'nt2-ii-r4-s2-q5',
          type: 'multiple-choice',
          question: 'What concern does the article raise regarding some EU member states?',
          options: [
            'That they are leaving the European Court of Human Rights.',
            'That political parties are trying to influence the composition of the judiciary.',
            'That courts in some countries are too slow and inefficient.',
            'That judges in some countries are not sufficiently educated.',
          ],
          correctIndex: 1,
          explanation: '"Recente zorgen betreffen landen waar politieke partijen de samenstelling van de rechterlijke macht proberen te beïnvloeden."',
          topicArea: 'rule-of-law',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s3',
      passageTitle: 'Rapport: Demografische verandering en de gevolgen voor de samenleving',
      passage:
        'Nederland verandert demografisch ingrijpend. Drie trends staan centraal: vergrijzing, bevolkingsgroei door migratie, en de groei van eenpersoonshuishoudens.\n\nDe vergrijzing is het meest structurele vraagstuk. In 2050 is naar verwachting bijna een kwart van de bevolking 65 jaar of ouder. Dit heeft verstrekkende gevolgen voor de arbeidsmarkt, de zorg, en de sociale zekerheid. De zogeheten grijze druk — de verhouding tussen ouderen en de werkende bevolking — neemt toe, wat betekent dat steeds minder werkenden de collectieve voorzieningen moeten financieren.\n\nDe bevolkingsgroei door migratie compenseert deels de vergrijzing op de arbeidsmarkt, maar leidt tegelijkertijd tot druk op woningmarkt en infrastructuur. De Rijksoverheid en gemeenten zoeken naar wegen om de ruimtelijke ordening hierop aan te passen.\n\nDe toename van eenpersoonshuishoudens — inmiddels meer dan 40% van alle huishoudens — heeft gevolgen voor de woningbehoefte (meer, kleinere woningen), maar ook voor zorg en welzijn. Alleenstaanden zijn vaker kwetsbaar voor eenzaamheid en hebben minder informele zorgnetwerken.\n\nEen coherent demografisch beleid vereist afstemming tussen meerdere ministeries en bestuurslagen, wat de beleidsvorming complex maakt.',
      instructions: 'Read the report and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s3-q1',
          type: 'multiple-choice',
          question: 'What are the three central demographic trends identified in the report?',
          options: [
            'Population decline, urbanisation, and emigration.',
            'Ageing, population growth through migration, and the rise of single-person households.',
            'Youth growth, declining birth rates, and increasing student populations.',
            'Suburbanisation, ageing, and declining immigration.',
          ],
          correctIndex: 1,
          explanation: '"Vergrijzing, bevolkingsgroei door migratie, en de groei van eenpersoonshuishoudens."',
          topicArea: 'demographics',
        },
        {
          id: 'nt2-ii-r4-s3-q2',
          type: 'multiple-choice',
          question: 'What is the "grijze druk"?',
          options: [
            'The proportion of grey (polluted) areas in Dutch cities.',
            'The ratio between elderly people and the working population.',
            'The financial burden of pension fund deficits.',
            'The pressure on the healthcare system from chronic diseases.',
          ],
          correctIndex: 1,
          explanation: '"De grijze druk — de verhouding tussen ouderen en de werkende bevolking — neemt toe."',
          topicArea: 'demographics',
        },
        {
          id: 'nt2-ii-r4-s3-q3',
          type: 'multiple-choice',
          question: 'What proportion of Dutch households are single-person households?',
          options: ['About 20%', 'About 30%', 'More than 40%', 'About 50%'],
          correctIndex: 2,
          explanation: '"De toename van eenpersoonshuishoudens — inmiddels meer dan 40% van alle huishoudens."',
          topicArea: 'demographics',
        },
        {
          id: 'nt2-ii-r4-s3-q4',
          type: 'multiple-choice',
          question: 'What social risk is mentioned in relation to people living alone?',
          options: [
            'Higher rates of unemployment.',
            'Vulnerability to loneliness and fewer informal care networks.',
            'A greater risk of financial fraud.',
            'Lower educational attainment.',
          ],
          correctIndex: 1,
          explanation: '"Alleenstaanden zijn vaker kwetsbaar voor eenzaamheid en hebben minder informele zorgnetwerken."',
          topicArea: 'demographics',
        },
        {
          id: 'nt2-ii-r4-s3-q5',
          type: 'multiple-choice',
          question: 'Why does the report describe coherent demographic policy as complex?',
          options: [
            'Because the Netherlands lacks the data needed to make good policy.',
            'Because there is no political will to address demographic change.',
            'Because it requires coordination across multiple ministries and levels of government.',
            'Because migration policy is determined at EU level, not nationally.',
          ],
          correctIndex: 2,
          explanation: '"Een coherent demografisch beleid vereist afstemming tussen meerdere ministeries en bestuurslagen."',
          topicArea: 'demographics',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s4',
      passageTitle: 'Analytisch artikel: Duurzaamheid van het voedselsysteem',
      passage:
        'Het mondiale voedselsysteem staat voor een paradox: terwijl wereldwijd bijna 800 miljoen mensen ondervoed zijn, leidt voedselverspilling in rijke landen tot enorme milieuschade. In Nederland wordt jaarlijks naar schatting 1,4 miljard kilo voedsel verspild.\n\nHet voedselsysteem draagt ook substantieel bij aan de uitstoot van broeikasgassen: wereldwijd is de voedselproductie verantwoordelijk voor ongeveer een kwart van de totale emissies. De productie van dierlijke eiwitten — vlees en zuivel — is daarin de grootste bijdrage.\n\nOvereenkomstig de aanbevelingen van de Gezondheidsraad en internationale organen als de FAO, wijzen onderzoekers op de noodzaak van een transitie naar meer plantaardige voedingspatronen. Dit is zowel uit gezondheids- als milieuperspectief verdedigbaar.\n\nEen complicerende factor is de betaalbaarheid. Gezond en duurzaam voedsel is duurder dan sterk bewerkte alternatieven, waardoor mensen met lage inkomens structureel minder toegang hebben tot duurzame keuzes. Beleidsinterventies — zoals btw-verlaging op groenten en fruit of subsidies op plantaardige eiwitten — kunnen dit deels compenseren, maar stuiten op politieke en budgettaire weerstand.\n\nDe Nederlandse overheid heeft in het Nationaal Programma Landelijk Gebied (NPLG) een reeks maatregelen opgenomen om de landbouw te verduurzamen, maar de implementatie is omstreden vanwege de belangen van de agrarische sector.',
      instructions: 'Read the analytical article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s4-q1',
          type: 'multiple-choice',
          question: 'What "paradox" does the article describe in the global food system?',
          options: [
            'Food is becoming more expensive but also lower in quality.',
            'Nearly 800 million people are undernourished while food waste in rich countries causes enormous environmental damage.',
            'The Netherlands produces enough food to feed the world but exports most of it.',
            'Organic food is healthier but causes more emissions.',
          ],
          correctIndex: 1,
          explanation: '"Terwijl wereldwijd bijna 800 miljoen mensen ondervoed zijn, leidt voedselverspilling in rijke landen tot enorme milieuschade."',
          topicArea: 'food-sustainability',
        },
        {
          id: 'nt2-ii-r4-s4-q2',
          type: 'multiple-choice',
          question: 'What share of global greenhouse gas emissions does food production account for?',
          options: ['About 10%', 'About 15%', 'About 25%', 'About 40%'],
          correctIndex: 2,
          explanation: '"Wereldwijd is de voedselproductie verantwoordelijk voor ongeveer een kwart van de totale emissies."',
          topicArea: 'food-sustainability',
        },
        {
          id: 'nt2-ii-r4-s4-q3',
          type: 'multiple-choice',
          question: 'What transition do researchers say is necessary, and on what grounds?',
          options: [
            'A shift to fully organic farming, for health reasons only.',
            'A transition to more plant-based diets, for both health and environmental reasons.',
            'A move to lab-grown meat, because it is cheaper.',
            'A return to traditional farming methods, for cultural reasons.',
          ],
          correctIndex: 1,
          explanation: '"Transitie naar meer plantaardige voedingspatronen … zowel uit gezondheids- als milieuperspectief verdedigbaar."',
          topicArea: 'food-sustainability',
        },
        {
          id: 'nt2-ii-r4-s4-q4',
          type: 'multiple-choice',
          question: 'What is the affordability problem described in the article?',
          options: [
            'Organic food is only available in expensive specialty shops.',
            'Healthy and sustainable food is more expensive than heavily processed alternatives, limiting access for lower-income people.',
            'Supermarkets refuse to sell plant-based products at affordable prices.',
            'The government taxes healthy food more heavily than processed food.',
          ],
          correctIndex: 1,
          explanation: '"Gezond en duurzaam voedsel is duurder dan sterk bewerkte alternatieven, waardoor mensen met lage inkomens structureel minder toegang hebben."',
          topicArea: 'food-sustainability',
        },
        {
          id: 'nt2-ii-r4-s4-q5',
          type: 'multiple-choice',
          question: 'Why is the implementation of the NPLG measures described as "omstreden"?',
          options: [
            'Because the measures are too expensive for the government to fund.',
            'Because of the interests of the agricultural sector.',
            'Because scientists disagree about the effectiveness of the measures.',
            'Because the EU has objected to the Dutch approach.',
          ],
          correctIndex: 1,
          explanation: '"De implementatie is omstreden vanwege de belangen van de agrarische sector."',
          topicArea: 'food-sustainability',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s5',
      passageTitle: 'Bestuurlijk document: Corporate governance en maatschappelijke verantwoordelijkheid',
      passage:
        'De rol van bedrijven in de samenleving is de afgelopen decennia onderwerp van debat. Het klassieke shareholder-model — waarbij het maximaliseren van aandeelhouderswaarde het primaire doel is — wordt toenemend uitgedaagd door het stakeholder-model, waarbij bedrijven rekening houden met alle belanghebbenden: werknemers, klanten, leveranciers, de samenleving en het milieu.\n\nIn Europa heeft deze verschuiving geleid tot nieuwe wetgeving. De EU Corporate Sustainability Reporting Directive (CSRD) verplicht grote bedrijven om transparant te rapporteren over hun ecologische en sociale impact. In Nederland zijn beursgenoteerde bedrijven bovendien gebonden aan de Nederlandse Corporate Governance Code, die normen stelt voor bestuur, toezicht en transparantie.\n\nEen specifiek debat betreft de beloning van bestuurders. In Nederland is de verhouding tussen het salaris van de hoogst betaalde bestuurder en het gemiddelde medewerkerssalaris bij grote bedrijven de afgelopen jaren sterk gestegen. Critici stellen dat dit de sociale cohesie ondermijnt en het vertrouwen in het bedrijfsleven schaadt. Voorstanders betogen dat markttarieven voor toptalent internationaal worden bepaald en dat Nederland concurrerend moet blijven.\n\nVanuit de overheid zijn er pogingen gedaan om via fiscale maatregelen excessen in beloningen te beperken, maar het effect is beperkt gebleven. De discussie over de grenzen van corporate vrijheid en maatschappelijke verantwoordelijkheid is daarmee actueel en onafgesloten.',
      instructions: 'Read the governance document and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s5-q1',
          type: 'multiple-choice',
          question: 'What is the core difference between the shareholder model and the stakeholder model?',
          options: [
            'The shareholder model focuses on employees; the stakeholder model focuses on profits.',
            'The shareholder model prioritises maximising shareholder value; the stakeholder model considers all parties including employees, society and the environment.',
            'The stakeholder model is used in the public sector; the shareholder model in private companies.',
            'There is no practical difference — both models aim for profit.',
          ],
          correctIndex: 1,
          explanation: '"Shareholder-model … maximaliseren van aandeelhouderswaarde … stakeholder-model … alle belanghebbenden: werknemers, klanten, leveranciers, de samenleving en het milieu."',
          topicArea: 'corporate-governance',
        },
        {
          id: 'nt2-ii-r4-s5-q2',
          type: 'multiple-choice',
          question: 'What does the EU Corporate Sustainability Reporting Directive (CSRD) require?',
          options: [
            'Companies to reduce their carbon emissions by 50% by 2030.',
            'Large companies to report transparently on their ecological and social impact.',
            'All companies to adopt the stakeholder model.',
            'Companies to donate 1% of profits to environmental causes.',
          ],
          correctIndex: 1,
          explanation: '"De CSRD verplicht grote bedrijven om transparant te rapporteren over hun ecologische en sociale impact."',
          topicArea: 'corporate-governance',
        },
        {
          id: 'nt2-ii-r4-s5-q3',
          type: 'multiple-choice',
          question: 'What trend in executive pay does the article describe?',
          options: [
            'Executive pay has declined significantly in the Netherlands.',
            'The ratio between the highest-paid executive and the average employee salary has risen sharply.',
            'The Netherlands now has a legal cap on executive salaries.',
            'Executive pay is now determined by law, not the market.',
          ],
          correctIndex: 1,
          explanation: '"De verhouding tussen het salaris van de hoogst betaalde bestuurder en het gemiddelde medewerkerssalaris … sterk gestegen."',
          topicArea: 'corporate-governance',
        },
        {
          id: 'nt2-ii-r4-s5-q4',
          type: 'multiple-choice',
          question: 'What argument do proponents of high executive pay make?',
          options: [
            'That executives work harder than ordinary employees and deserve more.',
            'That market rates for top talent are set internationally and the Netherlands must remain competitive.',
            'That high pay creates economic growth that benefits everyone.',
            'That executive pay is a private matter between company and individual.',
          ],
          correctIndex: 1,
          explanation: '"Markttarieven voor toptalent internationaal worden bepaald en dat Nederland concurrerend moet blijven."',
          topicArea: 'corporate-governance',
        },
        {
          id: 'nt2-ii-r4-s5-q5',
          type: 'multiple-choice',
          question: 'What does the article conclude about the debate on corporate freedom and social responsibility?',
          options: [
            'The debate has been resolved by the CSRD legislation.',
            'The debate is current and unresolved.',
            'The Netherlands has found the right balance between the two.',
            'The debate is only relevant for large multinationals.',
          ],
          correctIndex: 1,
          explanation: '"De discussie over de grenzen van corporate vrijheid en maatschappelijke verantwoordelijkheid is daarmee actueel en onafgesloten."',
          topicArea: 'corporate-governance',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s6',
      passageTitle: 'Wetenschappelijke samenvatting: Taalverwerving bij volwassen immigranten',
      passage:
        'De verwerving van een tweede taal op volwassen leeftijd is een complex proces dat wordt beïnvloed door een veelheid aan factoren. Taallinguïstisch onderzoek onderscheidt doorgaans drie clusters van variabelen: cognitieve factoren (zoals werkgeheugen en taalaptitude), omgevingsfactoren (zoals blootstelling aan de doeltaal en sociale netwerken), en motivationele factoren (zoals de wil tot integratie en instrumentele motivatie).\n\nEen robuuste bevinding in de literatuur is het bestaan van een "kritieke periode" in taalverwerving: kinderen verwerven een tweede taal met meer gemak en accenter dan volwassenen, met name op het gebied van fonologie (klankleer). Volwassen leerders compenseren dit gedeeltelijk met bewust leerstrategieën en metacognitieve vaardigheden.\n\nVoor beleid relevant is de bevinding dat kwaliteit van taalonderwijs en de mogelijkheid tot oefening in authentieke communicatieve contexten doorslaggevend zijn. Cursussen die uitsluitend gericht zijn op grammatica, zonder voldoende communicatieve oefening, blijken minder effectief dan geïntegreerde benaderingen.\n\nDe mate van contact met moedertaalsprekers is een sterke predictor voor taalvaardigheid. Sociale netwerken die uitsluitend uit taalgenoten bestaan, vertragen de taalverwerving aanzienlijk — wat beleidsmatige aandacht rechtvaardigt voor het bevorderen van sociale integratie naast taalcursussen.',
      instructions: 'Read the scientific summary and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s6-q1',
          type: 'multiple-choice',
          question: 'What three clusters of variables does language acquisition research distinguish?',
          options: [
            'Age, nationality, and education level.',
            'Cognitive factors, environmental factors, and motivational factors.',
            'Grammar knowledge, vocabulary, and pronunciation.',
            'Classroom learning, home practice, and social contact.',
          ],
          correctIndex: 1,
          explanation: '"Cognitieve factoren … omgevingsfactoren … en motivationele factoren."',
          topicArea: 'language-acquisition',
        },
        {
          id: 'nt2-ii-r4-s6-q2',
          type: 'multiple-choice',
          question: 'What is the "kritieke periode" in language acquisition?',
          options: [
            'The period during which adults can still learn a language efficiently.',
            'A window in childhood during which second language acquisition is easier, especially for pronunciation.',
            'A critical moment when a learner decides to give up learning.',
            'The first three months of a language course.',
          ],
          correctIndex: 1,
          explanation: '"Kinderen verwerven een tweede taal met meer gemak en accenter dan volwassenen, met name op het gebied van fonologie."',
          topicArea: 'language-acquisition',
        },
        {
          id: 'nt2-ii-r4-s6-q3',
          type: 'multiple-choice',
          question: 'What type of language course is shown to be less effective?',
          options: [
            'Courses that focus entirely on spoken communication.',
            'Courses focused solely on grammar without sufficient communicative practice.',
            'Online language courses without a teacher.',
            'Courses for beginners rather than advanced learners.',
          ],
          correctIndex: 1,
          explanation: '"Cursussen die uitsluitend gericht zijn op grammatica, zonder voldoende communicatieve oefening, blijken minder effectief."',
          topicArea: 'language-acquisition',
        },
        {
          id: 'nt2-ii-r4-s6-q4',
          type: 'multiple-choice',
          question: 'What effect do social networks made up exclusively of fellow native speakers have on language acquisition?',
          options: [
            'They accelerate language acquisition through shared cultural understanding.',
            'They have no effect on language acquisition speed.',
            'They significantly slow language acquisition.',
            'They improve pronunciation but slow grammar learning.',
          ],
          correctIndex: 2,
          explanation: '"Sociale netwerken die uitsluitend uit taalgenoten bestaan, vertragen de taalverwerving aanzienlijk."',
          topicArea: 'language-acquisition',
        },
        {
          id: 'nt2-ii-r4-s6-q5',
          type: 'multiple-choice',
          question: 'What policy implication does the article draw from its findings on social networks?',
          options: [
            'Language courses should be shortened to make room for social activities.',
            'Immigrants should be required to live in mixed neighbourhoods.',
            'Policy attention for promoting social integration alongside language courses is justified.',
            'Language acquisition funding should be reduced in favour of social integration programmes.',
          ],
          correctIndex: 2,
          explanation: '"Wat beleidsmatige aandacht rechtvaardigt voor het bevorderen van sociale integratie naast taalcursussen."',
          topicArea: 'language-acquisition',
        },
      ],
    },
    {
      id: 'nt2-ii-r4-s7',
      passageTitle: 'Opiniestuk: De wooncrisis — oorzaken en uitwegen',
      passage:
        'De Nederlandse woningmarkt verkeert in een structurele crisis. De wachtlijsten voor sociale huurwoningen zijn in sommige steden opgelopen tot meer dan twintig jaar. Koopwoningen zijn voor starters onbereikbaar geworden door een combinatie van lage rente (die de vraag opjoeg), beperkt aanbod en speculatief investeringsgedrag.\n\nDe oorzaken liggen gedeeltelijk in het verleden: decennia van beperkte woningbouw, de verkoop van sociale huurwoningen aan particulieren, en de liberalisering van de private huurmarkt. Tegelijkertijd heeft de scheiding tussen zorg en wonen geleid tot meer mensen die zelfstandig wonen en daarmee de vraag verder vergroot.\n\nVoorgestelde oplossingen variëren breed. Economen pleiten voor meer woningbouw — ook op locaties waar gemeenten traditioneel terughoudend zijn, zoals in het groen. Volkshuisvestingsdeskundigen bepleiten de versterking van de sociale huursector en strengere regulering van de particuliere huur. Anderen wijzen op de rol van investeerders en stellen voor om aankopen als derde woning te belasten of zelfs te verbieden.\n\nGemeenten en het Rijk worstelen met tegenstrijdige belangen. Bouwen is milieubelastend; niet bouwen vergroot de woningnood. De wooncrisis illustreert hoe complexe beleidsuitdagingen nooit één afdoende oplossing kennen, maar een mix van maatregelen vereisen — en daarvoor bovenal politieke moed.',
      instructions: 'Read the opinion piece and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r4-s7-q1',
          type: 'multiple-choice',
          question: 'What factors drove up housing prices for buyers according to the article?',
          options: [
            'High wages and a large influx of foreign buyers.',
            'Low interest rates driving up demand, limited supply, and speculative investment behaviour.',
            'Government policies deliberately keeping prices high.',
            'The construction of too many luxury apartments.',
          ],
          correctIndex: 1,
          explanation: '"Lage rente (die de vraag opjoeg), beperkt aanbod en speculatief investeringsgedrag."',
          topicArea: 'housing-crisis',
        },
        {
          id: 'nt2-ii-r4-s7-q2',
          type: 'multiple-choice',
          question: 'What historical policy decision contributed to the current social housing shortage?',
          options: [
            'The construction of too many social housing units in the 1980s.',
            'The sale of social housing to private individuals over the decades.',
            'The ban on building new social housing after 2000.',
            'The introduction of rent subsidies that reduced housing supply.',
          ],
          correctIndex: 1,
          explanation: '"De verkoop van sociale huurwoningen aan particulieren" is named as a historical contributing factor.',
          topicArea: 'housing-crisis',
        },
        {
          id: 'nt2-ii-r4-s7-q3',
          type: 'multiple-choice',
          question: 'What do economists advocate as a solution?',
          options: [
            'Reducing migration to lower housing demand.',
            'Building more homes, including on locations where municipalities have traditionally been reluctant.',
            'Nationalising the entire housing market.',
            'Introducing a maximum house price.',
          ],
          correctIndex: 1,
          explanation: '"Economen pleiten voor meer woningbouw — ook op locaties waar gemeenten traditioneel terughoudend zijn."',
          topicArea: 'housing-crisis',
        },
        {
          id: 'nt2-ii-r4-s7-q4',
          type: 'multiple-choice',
          question: 'What measure do some propose against investors buying multiple properties?',
          options: [
            'Requiring investors to rent out properties below market rate.',
            'Taxing or even prohibiting the purchase of a third home.',
            'Requiring investors to pay a special licence fee.',
            'Limiting foreign investors only.',
          ],
          correctIndex: 1,
          explanation: '"Stellen voor om aankopen als derde woning te belasten of zelfs te verbieden."',
          topicArea: 'housing-crisis',
        },
        {
          id: 'nt2-ii-r4-s7-q5',
          type: 'multiple-choice',
          question: 'What does the article say is ultimately needed to solve the housing crisis?',
          options: [
            'A single comprehensive law covering all aspects of housing.',
            'A mix of measures and, above all, political courage.',
            'More funding from the European Union.',
            'A complete transfer of housing policy to municipalities.',
          ],
          correctIndex: 1,
          explanation: '"Een mix van maatregelen vereisen — en daarvoor bovenal politieke moed."',
          topicArea: 'housing-crisis',
        },
      ],
    },
  ],
};
