import { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IIReading3: ExamPracticeTest = {
  id: 'staatsexamen-nt2-ii-reading-3',
  examType: 'staatsexamen-nt2-ii',
  skill: 'reading',
  title: 'Staatsexamen NT2 Programma II – Lezen (Oefening 3)',
  description:
    'Practice reading exam at B2 level. Read complex analytical, academic and formal Dutch texts and answer detailed comprehension questions. Topics: education policy, healthcare reform, digital transformation, urban planning, social inequality.',
  timeLimitMinutes: 100,
  passingScore: 60,
  totalQuestions: 35,
  sections: [
    {
      id: 'nt2-ii-r3-s1',
      passageTitle: 'Opinie: De toekomst van het hoger onderwijs in Nederland',
      passage:
        'De toegankelijkheid van het Nederlandse hoger onderwijs staat ter discussie. Hoewel Nederland internationaal bekend staat om zijn hoge kwaliteit van universiteiten en hogescholen, signaleren onderzoekers een groeiende kloof tussen studenten uit hogere en lagere inkomensgroepen.\n\nHet leenstelsel, dat in 2015 de basisbeurs verving, heeft volgens critici een drempelverhogende werking. Studenten uit minder draagkrachtige gezinnen studeren minder lang of kiezen vaker voor een mbo-opleiding in plaats van een hbo of universiteit, uit angst voor schulden. Voorstanders van het stelsel stellen dat investeren in jezelf loont en dat de aanvullende beurs voldoende bescherming biedt.\n\nEen andere discussie betreft het numerus fixus: sommige populaire opleidingen hanteren een maximale toelating vanwege beperkte capaciteit of arbeidsmarktoverwegingen. Critici stellen dat dit ongelijkheid in de hand werkt, omdat kinderen uit hoger opgeleide gezinnen beter zijn voorbereid op de selectieprocedures.\n\nDe overheid heeft aangekondigd de basisbeurs gedeeltelijk te herstellen. Of dit de toegankelijkheid structureel verbetert, is echter onderwerp van voortdurend debat onder beleidsmakers en onderwijsdeskundigen.',
      instructions: 'Read the opinion article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s1-q1',
          type: 'multiple-choice',
          question: 'What is the main concern raised about Dutch higher education in this article?',
          options: [
            'The declining quality of Dutch universities internationally.',
            'A growing gap in access between students from higher and lower income groups.',
            'The shortage of study places in the Netherlands.',
            'The high cost of international students attending Dutch universities.',
          ],
          correctIndex: 1,
          explanation: '"Onderzoekers signaleren een groeiende kloof tussen studenten uit hogere en lagere inkomensgroepen."',
          topicArea: 'education-policy',
        },
        {
          id: 'nt2-ii-r3-s1-q2',
          type: 'multiple-choice',
          question: 'What is the criticism of the "leenstelsel"?',
          options: [
            'It forces all students to take out large loans with high interest.',
            'It discourages students from lower-income families due to fear of debt.',
            'It only applies to HBO students, not university students.',
            'It was introduced too recently to evaluate properly.',
          ],
          correctIndex: 1,
          explanation: '"Studenten uit minder draagkrachtige gezinnen studeren minder lang … uit angst voor schulden."',
          topicArea: 'education-policy',
        },
        {
          id: 'nt2-ii-r3-s1-q3',
          type: 'multiple-choice',
          question: 'What is a "numerus fixus"?',
          options: [
            'A scholarship for talented students.',
            'A maximum admission limit for popular study programmes.',
            'A rule preventing foreign students from enrolling.',
            'A fixed grant amount regardless of income.',
          ],
          correctIndex: 1,
          explanation: '"Numerus fixus: sommige populaire opleidingen hanteren een maximale toelating."',
          topicArea: 'education-policy',
        },
        {
          id: 'nt2-ii-r3-s1-q4',
          type: 'multiple-choice',
          question: 'What has the government announced regarding the basisbeurs?',
          options: [
            'It will be completely abolished.',
            'It will be partially restored.',
            'It will be available only for low-income students.',
            'It will be replaced by a new voucher system.',
          ],
          correctIndex: 1,
          explanation: '"De overheid heeft aangekondigd de basisbeurs gedeeltelijk te herstellen."',
          topicArea: 'education-policy',
        },
        {
          id: 'nt2-ii-r3-s1-q5',
          type: 'multiple-choice',
          question: 'The article describes the debate over access to education as "voortdurend". What does this suggest?',
          options: [
            'The debate has been conclusively resolved.',
            'The debate is ongoing and not yet settled.',
            'The debate is limited to academic circles.',
            'The debate is expected to be resolved by 2026.',
          ],
          correctIndex: 1,
          explanation: '"Voortdurend debat" = ongoing/continuous debate — the issue remains unresolved.',
          topicArea: 'education-policy',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s2',
      passageTitle: 'Academisch artikel: Preventieve gezondheidszorg in een vergrijzende samenleving',
      passage:
        'De Nederlandse gezondheidszorg staat voor een structurele uitdaging. Door de vergrijzing neemt het aantal chronisch zieken toe, terwijl de arbeidsmarkt voor zorgpersoneel kampt met ernstige tekorten. Beleidsmakers zoeken naar manieren om de zorg betaalbaar en toegankelijk te houden.\n\nEén van de meest besproken oplossingsrichtingen is preventie: het voorkomen van ziekte in plaats van het behandelen ervan. Uit onderzoek blijkt dat leefstijlinterventies — zoals begeleiding bij stoppen met roken, bewegen en gezonde voeding — op lange termijn aanzienlijk kosten besparen. Toch blijft de financiering van preventie achter bij die van curatieve zorg.\n\nEen complicerende factor is de zogenaamde "preventieparadox": de grootste gezondheidswinst wordt behaald bij risicogroepen die het moeilijkst te bereiken zijn — mensen met een lage sociaaleconomische status, laaggeletterden, en mensen met een migratieachtergrond. Gerichte interventies voor deze groepen vereisen extra middelen en cultureel sensitieve communicatie.\n\nDe Gezondheidsraad beveelt aan dat preventie meer structureel wordt ingebed in het basispakket van de zorgverzekering. Critici vrezen echter dat verzekeraars weinig prikkels hebben om te investeren in preventie, omdat de financiële vruchten pas jaren later worden geplukt.',
      instructions: 'Read the academic article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s2-q1',
          type: 'multiple-choice',
          question: 'What structural challenge does the Dutch healthcare system face according to the article?',
          options: [
            'A rapidly growing population that overwhelms infrastructure.',
            'An ageing population increasing chronic illness combined with staff shortages.',
            'A lack of modern medical technology.',
            'An oversupply of healthcare workers with no positions available.',
          ],
          correctIndex: 1,
          explanation: '"Door de vergrijzing neemt het aantal chronisch zieken toe, terwijl de arbeidsmarkt voor zorgpersoneel kampt met ernstige tekorten."',
          topicArea: 'healthcare-policy',
        },
        {
          id: 'nt2-ii-r3-s2-q2',
          type: 'multiple-choice',
          question: 'What does the article say about preventive care financing?',
          options: [
            'Prevention receives more funding than curative care.',
            'Prevention financing lags behind curative care funding.',
            'Prevention is now the main focus of the health insurance package.',
            'Prevention is fully covered by the basic health insurance.',
          ],
          correctIndex: 1,
          explanation: '"De financiering van preventie blijft achter bij die van curatieve zorg."',
          topicArea: 'healthcare-policy',
        },
        {
          id: 'nt2-ii-r3-s2-q3',
          type: 'multiple-choice',
          question: 'What is the "preventieparadox"?',
          options: [
            'That prevention is cheaper but receives less funding.',
            'That those who benefit most from prevention are the hardest to reach.',
            'That healthy people are more expensive to insure.',
            'That prevention programmes work in trials but fail in practice.',
          ],
          correctIndex: 1,
          explanation: '"De grootste gezondheidswinst wordt behaald bij risicogroepen die het moeilijkst te bereiken zijn."',
          topicArea: 'healthcare-policy',
        },
        {
          id: 'nt2-ii-r3-s2-q4',
          type: 'multiple-choice',
          question: 'Why do critics say insurers have little incentive to invest in prevention?',
          options: [
            'Because prevention programmes are too expensive to implement.',
            'Because the financial benefits only materialise years later.',
            'Because prevention is the responsibility of the government, not insurers.',
            'Because patients refuse to participate in prevention programmes.',
          ],
          correctIndex: 1,
          explanation: '"Verzekeraars weinig prikkels hebben om te investeren in preventie, omdat de financiële vruchten pas jaren later worden geplukt."',
          topicArea: 'healthcare-policy',
        },
        {
          id: 'nt2-ii-r3-s2-q5',
          type: 'multiple-choice',
          question: 'What does the Gezondheidsraad recommend?',
          options: [
            'That prevention be removed from the basic insurance package.',
            'That prevention be more structurally embedded in the basic health insurance.',
            'That all prevention programmes be handled by municipalities.',
            'That private insurers take over all preventive healthcare.',
          ],
          correctIndex: 1,
          explanation: '"De Gezondheidsraad beveelt aan dat preventie meer structureel wordt ingebed in het basispakket van de zorgverzekering."',
          topicArea: 'healthcare-policy',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s3',
      passageTitle: 'Beleidsdocument: Digitale overheid — kansen en risico\'s',
      passage:
        'De Nederlandse overheid investeert fors in de digitalisering van overheidsdiensten. Het doel is burgers efficiënter te bedienen en administratieve lasten te verminderen. Via portalen als MijnOverheid.nl en DigiD kunnen burgers hun belastingaangifte doen, uitkeringen aanvragen en correspondentie met de overheid afhandelen.\n\nToch roept de digitalisering van de overheid ook vragen op. Ten eerste de kwestie van digitale uitsluiting: niet alle burgers zijn even vaardig in het gebruik van digitale middelen. Ouderen, laaggeletterden en mensen met een beperking lopen het risico hun recht op diensten niet te kunnen uitoefenen als digitale alternatieven de enige optie worden.\n\nTen tweede zijn er zorgen over de veiligheid van persoonsgegevens. Datalekken bij overheidsinstellingen kunnen verstrekkende gevolgen hebben voor burgers. De Autoriteit Persoonsgegevens (AP) houdt toezicht op de naleving van de AVG (Algemene Verordening Gegevensbescherming).\n\nEen derde punt van zorg betreft algoritmische besluitvorming. De overheid maakt in toenemende mate gebruik van algoritmen bij de beoordeling van aanvragen en uitkeringen. Fouten in dergelijke systemen — zoals bij het kinderopvangtoeslagschandaal bleek — kunnen desastreuze gevolgen hebben voor individuele burgers.\n\nHet kabinet heeft toegezegd dat er altijd een menselijke route beschikbaar blijft voor burgers die dat wensen.',
      instructions: 'Read the policy document and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s3-q1',
          type: 'multiple-choice',
          question: 'What is the stated goal of the government\'s digitalisation programme?',
          options: [
            'To replace all civil servants with automated systems.',
            'To serve citizens more efficiently and reduce administrative burdens.',
            'To save money by eliminating paper-based services entirely.',
            'To collect more data on citizens for policy development.',
          ],
          correctIndex: 1,
          explanation: '"Het doel is burgers efficiënter te bedienen en administratieve lasten te verminderen."',
          topicArea: 'government-digital',
        },
        {
          id: 'nt2-ii-r3-s3-q2',
          type: 'multiple-choice',
          question: 'What is "digitale uitsluiting"?',
          options: [
            'The government blocking access to certain online services.',
            'The risk that citizens who cannot use digital tools are excluded from services.',
            'A criminal offence involving hacking government systems.',
            'A policy to reduce paper waste by moving everything online.',
          ],
          correctIndex: 1,
          explanation: '"Niet alle burgers zijn even vaardig in het gebruik van digitale middelen … lopen het risico hun recht op diensten niet te kunnen uitoefenen."',
          topicArea: 'government-digital',
        },
        {
          id: 'nt2-ii-r3-s3-q3',
          type: 'multiple-choice',
          question: 'What does the Autoriteit Persoonsgegevens (AP) do?',
          options: [
            'It manages the DigiD system.',
            'It oversees compliance with the AVG (GDPR).',
            'It investigates cybercrime against individuals.',
            'It provides digital training for elderly citizens.',
          ],
          correctIndex: 1,
          explanation: '"De AP houdt toezicht op de naleving van de AVG."',
          topicArea: 'government-digital',
        },
        {
          id: 'nt2-ii-r3-s3-q4',
          type: 'multiple-choice',
          question: 'What does the kinderopvangtoeslagschandaal illustrate in this context?',
          options: [
            'The importance of digitalising the childcare allowance system.',
            'That algorithmic decision-making errors can have devastating consequences for citizens.',
            'That the government should abolish digital processes entirely.',
            'That the AP needs more powers to protect citizens.',
          ],
          correctIndex: 1,
          explanation: '"Fouten in dergelijke systemen — zoals bij het kinderopvangtoeslagschandaal bleek — kunnen desastreuze gevolgen hebben voor individuele burgers."',
          topicArea: 'government-digital',
        },
        {
          id: 'nt2-ii-r3-s3-q5',
          type: 'multiple-choice',
          question: 'What commitment has the government made regarding citizens who cannot use digital services?',
          options: [
            'They will receive a paper form by post automatically.',
            'A human (non-digital) route will always remain available for those who want it.',
            'They will be assigned a personal civil servant to assist them.',
            'They will pay a reduced service fee.',
          ],
          correctIndex: 1,
          explanation: '"Het kabinet heeft toegezegd dat er altijd een menselijke route beschikbaar blijft voor burgers die dat wensen."',
          topicArea: 'government-digital',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s4',
      passageTitle: 'Analytisch artikel: De stikstofcrisis en ruimtelijke ordening',
      passage:
        'De stikstofcrisis heeft de Nederlandse ruimtelijke ordening in een impasse gebracht. Door strenge Europese regels ter bescherming van Natura 2000-gebieden mag de stikstofdepositie op beschermde natuur niet toenemen. Dit raakt direct aan bouwprojecten, infrastructuurwerken en de agrarische sector.\n\nDe Raad van State oordeelde in 2019 dat het Programma Aanpak Stikstof (PAS) onrechtmatig was, omdat het vooruit liep op toekomstige stikstofruimte die nog niet beschikbaar was. Dit leidde tot het stilleggen van duizenden vergunningaanvragen voor woningbouw en wegenaanleg.\n\nDe woningbouwcrisis werd hierdoor verergerd. Nederland heeft een tekort van circa 390.000 woningen, maar de vergunningverlening stokt. Gemeenten zoeken naar creatieve oplossingen: tijdelijke woningen, transformatie van kantoorpanden en bouw verder van Natura 2000-gebieden.\n\nVanuit de agrarische sector is er forse weerstand tegen de stikstofmaatregelen. Boeren vrezen gedwongen uitkoop en het verlies van generatielange bedrijven. De overheid heeft een nationaal stikstoffonds van 25 miljard euro opgericht voor uitkoop en omschakeling, maar de implementatie verloopt moeizaam.\n\nEconomen wijzen op de spanningsverhouding tussen economische groei, woningbouw en ecologische duurzaamheid die dit dossier exemplarisch illustreert.',
      instructions: 'Read the analytical article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s4-q1',
          type: 'multiple-choice',
          question: 'Why does the nitrogen crisis affect construction projects in the Netherlands?',
          options: [
            'Because nitrogen causes structural damage to buildings.',
            'Because European rules protect Natura 2000 areas from increased nitrogen deposition.',
            'Because the government decided to stop all construction to reduce pollution.',
            'Because nitrogen shortages are needed for the building materials industry.',
          ],
          correctIndex: 1,
          explanation: '"Door strenge Europese regels … mag de stikstofdepositie op beschermde natuur niet toenemen. Dit raakt direct aan bouwprojecten."',
          topicArea: 'urban-environment',
        },
        {
          id: 'nt2-ii-r3-s4-q2',
          type: 'multiple-choice',
          question: 'What did the Raad van State rule in 2019?',
          options: [
            'That the nitrogen rules were too strict and should be relaxed.',
            'That the PAS programme was unlawful.',
            'That all housing construction should be halted indefinitely.',
            'That farmers must be compensated immediately.',
          ],
          correctIndex: 1,
          explanation: '"De Raad van State oordeelde … dat het Programma Aanpak Stikstof (PAS) onrechtmatig was."',
          topicArea: 'urban-environment',
        },
        {
          id: 'nt2-ii-r3-s4-q3',
          type: 'multiple-choice',
          question: 'What is the housing shortfall mentioned in the article?',
          options: ['100,000 homes.', '250,000 homes.', '390,000 homes.', '500,000 homes.'],
          correctIndex: 2,
          explanation: '"Nederland heeft een tekort van circa 390.000 woningen."',
          topicArea: 'urban-environment',
        },
        {
          id: 'nt2-ii-r3-s4-q4',
          type: 'multiple-choice',
          question: 'What is the purpose of the national nitrogen fund of €25 billion?',
          options: [
            'To build new nature reserves.',
            'To compensate farmers who are bought out and to support transition.',
            'To fund scientific research into nitrogen reduction techniques.',
            'To pay municipalities for delays in permit processing.',
          ],
          correctIndex: 1,
          explanation: '"Een nationaal stikstoffonds van 25 miljard euro … voor uitkoop en omschakeling."',
          topicArea: 'urban-environment',
        },
        {
          id: 'nt2-ii-r3-s4-q5',
          type: 'multiple-choice',
          question: 'What "spanningsverhouding" do economists point to in this article?',
          options: [
            'The tension between urban and rural voters.',
            'The tension between economic growth, housing and ecological sustainability.',
            'The tension between national and EU legislation.',
            'The tension between large and small agricultural businesses.',
          ],
          correctIndex: 1,
          explanation: '"De spanningsverhouding tussen economische groei, woningbouw en ecologische duurzaamheid."',
          topicArea: 'urban-environment',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s5',
      passageTitle: 'Bestuurlijke brief: jaarverslag en strategische koers',
      passage:
        'Aan: de leden van de Raad van Toezicht\nVan: de Raad van Bestuur\nBetreft: Jaarverslag 2024 en strategische prioriteiten 2025–2027\n\nGeachte leden,\n\nHierbij bieden wij u het jaarverslag 2024 aan, vergezeld van een toelichting op de strategische koers voor de komende periode.\n\nFinancieel resultaat\nHet boekjaar 2024 sloot met een positief saldo van €2,3 miljoen, een verbetering ten opzichte van het neutrale resultaat van 2023. De verbetering is toe te schrijven aan efficiëntiewinst in de bedrijfsvoering en een toename van projectsubsidies.\n\nStrategische prioriteiten 2025–2027\nDe organisatie focust op drie pijlers:\n1. Duurzame dienstverlening: vermindering van de ecologische voetafdruk van onze activiteiten met 30% in 2027.\n2. Inclusie: uitbreiding van diensten voor kwetsbare groepen, met bijzondere aandacht voor laaggeletterden en mensen met een beperking.\n3. Digitale transitie: volledige migratie naar cloudgebaseerde systemen per eind 2026.\n\nRisico\'s\nDe organisatie signaleert twee hoofdrisico\'s: toenemende personeelskrapte in de sector en onzekerheid over subsidiestromen als gevolg van bezuinigingen bij de rijksoverheid.\n\nWij verzoeken de Raad van Toezicht het jaarverslag goed te keuren en de strategische koers te bekrachtigen in de vergadering van 15 maart.',
      instructions: 'Read the board letter and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s5-q1',
          type: 'multiple-choice',
          question: 'How did the 2024 financial year close compared to 2023?',
          options: [
            'With a loss of €2.3 million, worse than 2023.',
            'With a profit of €2.3 million, an improvement on the neutral result in 2023.',
            'With the same neutral result as 2023.',
            'With a profit of €23 million, significantly better than 2023.',
          ],
          correctIndex: 1,
          explanation: '"Het boekjaar 2024 sloot met een positief saldo van €2,3 miljoen, een verbetering ten opzichte van het neutrale resultaat van 2023."',
          topicArea: 'formal-correspondence',
        },
        {
          id: 'nt2-ii-r3-s5-q2',
          type: 'multiple-choice',
          question: 'What is the target for reducing the ecological footprint by 2027?',
          options: ['10%', '20%', '30%', '50%'],
          correctIndex: 2,
          explanation: '"Vermindering van de ecologische voetafdruk van onze activiteiten met 30% in 2027."',
          topicArea: 'formal-correspondence',
        },
        {
          id: 'nt2-ii-r3-s5-q3',
          type: 'multiple-choice',
          question: 'What are the two main risks identified by the organisation?',
          options: [
            'Increasing staff shortages and uncertainty about subsidies due to government cuts.',
            'Rising energy costs and new European regulations.',
            'Loss of key clients and increasing competition.',
            'IT security risks and changing legislation.',
          ],
          correctIndex: 1,
          explanation: '"Toenemende personeelskrapte in de sector en onzekerheid over subsidiestromen als gevolg van bezuinigingen bij de rijksoverheid."',
          topicArea: 'formal-correspondence',
        },
        {
          id: 'nt2-ii-r3-s5-q4',
          type: 'multiple-choice',
          question: 'What is the organisation asking the Supervisory Board to do?',
          options: [
            'To approve additional funding for the digital transition.',
            'To approve the annual report and endorse the strategic direction at the 15 March meeting.',
            'To replace the current Board of Directors.',
            'To reduce the organisation\'s ambitions for 2025–2027.',
          ],
          correctIndex: 1,
          explanation: '"Wij verzoeken de Raad van Toezicht het jaarverslag goed te keuren en de strategische koers te bekrachtigen in de vergadering van 15 maart."',
          topicArea: 'formal-correspondence',
        },
        {
          id: 'nt2-ii-r3-s5-q5',
          type: 'multiple-choice',
          question: 'What does the "inclusie" pillar focus on?',
          options: [
            'Including more international staff in the organisation.',
            'Expanding services for vulnerable groups, particularly low-literacy individuals and people with disabilities.',
            'Making all digital services multilingual.',
            'Increasing the diversity of the Board of Directors.',
          ],
          correctIndex: 1,
          explanation: '"Inclusie: uitbreiding van diensten voor kwetsbare groepen, met bijzondere aandacht voor laaggeletterden en mensen met een beperking."',
          topicArea: 'formal-correspondence',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s6',
      passageTitle: 'Sociaal artikel: Sociale ongelijkheid en kansengelijkheid in Nederland',
      passage:
        'Nederland scoort internationaal goed op welvaart en levenskwaliteit, maar de kansengelijkheid — de mate waarin iemands achtergrond zijn of haar toekomst bepaalt — staat onder druk. Onderzoekers constateren dat het postcodelot, het doorslaggevend belang van sociale afkomst en het onderwijssysteem grote invloed hebben op iemands levensloopkansen.\n\nHet onderwijssysteem speelt hierin een cruciale rol. Vroege selectie — al op twaalfjarige leeftijd — beslist mede over iemands toekomst. Kinderen van hoogopgeleide ouders stromen vaker door naar het vwo, ook bij vergelijkbare cognitieve capaciteiten. Dit fenomeen heet het "sociaal-cultureel kapitaal" van de ouders.\n\nArbeidsmarktonderzoekers wijzen op discriminatie bij sollicitatieprocedures: mensen met een migratieachtergrond, of met een "buitenlandse klingende naam", krijgen significant minder uitnodigingen voor gesprekken. Anoniem solliciteren is in sommige gemeenten als pilot ingevoerd om dit tegen te gaan.\n\nDe overheid heeft via het Nationaal Programma Onderwijs (NPO) extra middelen vrijgemaakt om leerachterstanden te compenseren die ontstonden door de coronacrisis, met nadruk op kwetsbare groepen. De effectiviteit hiervan wordt de komende jaren gemonitord.\n\nEconomisten benadrukken dat investeren in gelijke kansen niet alleen rechtvaardig is, maar ook economisch lonend: onbenut talent is een maatschappelijke kostenpost.',
      instructions: 'Read the social article and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s6-q1',
          type: 'multiple-choice',
          question: 'What does "kansengelijkheid" refer to?',
          options: [
            'The legal right of all citizens to vote.',
            'The degree to which a person\'s background determines their future opportunities.',
            'Equal pay for equal work.',
            'The chance of winning a lottery based on your postal code.',
          ],
          correctIndex: 1,
          explanation: '"De mate waarin iemands achtergrond zijn of haar toekomst bepaalt."',
          topicArea: 'social-inequality',
        },
        {
          id: 'nt2-ii-r3-s6-q2',
          type: 'multiple-choice',
          question: 'What does "sociaal-cultureel kapitaal" mean in the context of the Dutch education system?',
          options: [
            'The amount of money a family has to invest in education.',
            'The advantage that children of highly-educated parents have due to their cultural and social background.',
            'Government subsidies for cultural activities.',
            'The cultural knowledge tested in the NT2 examination.',
          ],
          correctIndex: 1,
          explanation: '"Kinderen van hoogopgeleide ouders stromen vaker door naar het vwo … Dit fenomeen heet het \'sociaal-cultureel kapitaal\' van de ouders."',
          topicArea: 'social-inequality',
        },
        {
          id: 'nt2-ii-r3-s6-q3',
          type: 'multiple-choice',
          question: 'What is "anoniem solliciteren" and what problem does it aim to address?',
          options: [
            'Applying for jobs without revealing your age — to combat age discrimination.',
            'Applying for jobs without revealing your name or background — to address discrimination against people with a migrant background.',
            'Online job applications without a cover letter.',
            'A system where employers do not know the salary expectations of applicants.',
          ],
          correctIndex: 1,
          explanation: '"Mensen met een migratieachtergrond … krijgen significant minder uitnodigingen … Anoniem solliciteren … om dit tegen te gaan."',
          topicArea: 'social-inequality',
        },
        {
          id: 'nt2-ii-r3-s6-q4',
          type: 'multiple-choice',
          question: 'What was the Nationaal Programma Onderwijs (NPO) created for?',
          options: [
            'To introduce a new curriculum for all Dutch schools.',
            'To compensate for learning delays caused by the COVID-19 crisis, particularly for vulnerable groups.',
            'To fund new school buildings in underprivileged areas.',
            'To provide university scholarships for first-generation students.',
          ],
          correctIndex: 1,
          explanation: '"Extra middelen vrijgemaakt om leerachterstanden te compenseren die ontstonden door de coronacrisis, met nadruk op kwetsbare groepen."',
          topicArea: 'social-inequality',
        },
        {
          id: 'nt2-ii-r3-s6-q5',
          type: 'multiple-choice',
          question: 'What economic argument do economists make for investing in equal opportunities?',
          options: [
            'It reduces government spending on benefits.',
            'Unused talent is a social cost, making equal opportunity both just and economically beneficial.',
            'It attracts foreign investment.',
            'It reduces crime rates which in turn lowers policing costs.',
          ],
          correctIndex: 1,
          explanation: '"Onbenut talent is een maatschappelijke kostenpost" — investing in equal chances is "economisch lonend".',
          topicArea: 'social-inequality',
        },
      ],
    },
    {
      id: 'nt2-ii-r3-s7',
      passageTitle: 'Rapport: Energietransitie in de gebouwde omgeving',
      passage:
        'Het verduurzamen van de gebouwde omgeving — gebouwen en woningen — is een van de grootste opgaven van de Nederlandse energietransitie. Gebouwen zijn verantwoordelijk voor circa 40% van het totale energieverbruik in Nederland.\n\nDe Klimaatwet verplicht Nederland om in 2050 klimaatneutraal te zijn. Voor de gebouwde omgeving betekent dit dat alle woningen van het aardgas af moeten en overgeschakeld moeten worden op duurzame verwarmingsalternatieven, zoals warmtepompen, stadsverwarming of waterstof.\n\nEen belangrijk knelpunt is de financiering. Woningeigenaren kunnen aanspraak maken op subsidies via het ISDE (Investeringssubsidie Duurzame Energie) en leningen via het Warmtefonds. Huurders zijn afhankelijk van de inspanningen van woningcorporaties.\n\nDe ongelijkheid in de energietransitie is een groeiende zorg. Eigenaar-bewoners met hogere inkomens kunnen eerder investeren en profiteren van lagere energiekosten, terwijl lagere inkomensgroepen — met name huurders in oudere woningen — hogere energielasten blijven dragen.\n\nGemeenten spelen een sleutelrol via de Transitievisie Warmte: zij bepalen per wijk welke duurzame warmtebron leidend zal zijn, en wanneer de overgang gepland staat.',
      instructions: 'Read the report and answer the questions.',
      questions: [
        {
          id: 'nt2-ii-r3-s7-q1',
          type: 'multiple-choice',
          question: 'What percentage of Dutch total energy consumption do buildings account for?',
          options: ['20%', '30%', '40%', '60%'],
          correctIndex: 2,
          explanation: '"Gebouwen zijn verantwoordelijk voor circa 40% van het totale energieverbruik in Nederland."',
          topicArea: 'energy-environment',
        },
        {
          id: 'nt2-ii-r3-s7-q2',
          type: 'multiple-choice',
          question: 'What does the Klimaatwet require the Netherlands to achieve by 2050?',
          options: [
            '50% reduction in CO₂ emissions.',
            'Climate neutrality.',
            'Fully renewable electricity generation.',
            'Elimination of all private car use.',
          ],
          correctIndex: 1,
          explanation: '"De Klimaatwet verplicht Nederland om in 2050 klimaatneutraal te zijn."',
          topicArea: 'energy-environment',
        },
        {
          id: 'nt2-ii-r3-s7-q3',
          type: 'multiple-choice',
          question: 'What can homeowners use to fund their sustainable energy investments?',
          options: [
            'ISDE subsidies and loans via the Warmtefonds.',
            'Tax deductions and government grants only.',
            'European Union structural funds.',
            'The housing corporation will pay for it.',
          ],
          correctIndex: 1,
          explanation: '"Woningeigenaren kunnen aanspraak maken op subsidies via het ISDE en leningen via het Warmtefonds."',
          topicArea: 'energy-environment',
        },
        {
          id: 'nt2-ii-r3-s7-q4',
          type: 'multiple-choice',
          question: 'Why is inequality in the energy transition a concern?',
          options: [
            'Because large companies can avoid sustainability requirements.',
            'Because higher-income homeowners can invest earlier and save on energy costs, while lower-income renters bear higher energy bills.',
            'Because rural areas do not have access to renewable energy networks.',
            'Because subsidies are only available for new buildings, not existing ones.',
          ],
          correctIndex: 1,
          explanation: '"Eigenaar-bewoners met hogere inkomens kunnen eerder investeren … terwijl lagere inkomensgroepen … hogere energielasten blijven dragen."',
          topicArea: 'energy-environment',
        },
        {
          id: 'nt2-ii-r3-s7-q5',
          type: 'multiple-choice',
          question: 'What role do municipalities play in the energy transition for buildings?',
          options: [
            'They directly fund all insulation work.',
            'They determine per neighbourhood which sustainable heat source will be leading, via the Transitievisie Warmte.',
            'They enforce the Klimaatwet through fines.',
            'They replace housing corporations as the main body responsible for social housing.',
          ],
          correctIndex: 1,
          explanation: '"Gemeenten spelen een sleutelrol via de Transitievisie Warmte: zij bepalen per wijk welke duurzame warmtebron leidend zal zijn."',
          topicArea: 'energy-environment',
        },
      ],
    },
  ],
};
