import { NextRequest, NextResponse } from 'next/server';
import { stripe } from '@/lib/stripe';
import { createAdminClient } from '@/lib/supabase-admin';

/**
 * GET /api/stripe/gift-session?session_id=xxx
 * Called by /gift/success to retrieve the gift code after a successful payment.
 */
export async function GET(request: NextRequest) {
  const sessionId = request.nextUrl.searchParams.get('session_id');
  if (!sessionId) {
    return NextResponse.json({ error: 'Missing session_id' }, { status: 400 });
  }

  // Verify the session with Stripe
  const session = await stripe.checkout.sessions.retrieve(sessionId);
  if (session.payment_status !== 'paid') {
    return NextResponse.json({ error: 'Payment not completed' }, { status: 402 });
  }

  if (session.metadata?.type !== 'gift') {
    return NextResponse.json({ error: 'Not a gift session' }, { status: 400 });
  }

  const paymentIntent = session.payment_intent as string;
  const supabaseAdmin = createAdminClient();

  // Look up the gift code generated by the webhook
  const { data: gift } = await supabaseAdmin
    .from('gift_codes')
    .select('code, redeemed_at, purchased_by_email')
    .eq('stripe_payment_intent', paymentIntent)
    .maybeSingle();

  if (!gift) {
    // Webhook may not have fired yet — return pending
    return NextResponse.json({ pending: true });
  }

  return NextResponse.json({
    code: gift.code,
    redeemed: !!gift.redeemed_at,
    purchasedByEmail: gift.purchased_by_email,
  });
}
