import type { VerbConjugation } from './types';

// ---------------------------------------------------------------------------
// Complete verb conjugation data for all verbs appearing in grammar tables
// ---------------------------------------------------------------------------

const verbs: VerbConjugation[] = [
  // ===== CORE VERBS =====
  {
    infinitive: 'hebben',
    translation: 'to have',
    auxiliary: 'hebben',
    pastParticiple: 'gehad',
    isRegular: false,
    present: { ik: 'heb', jij: 'hebt', u: 'hebt / heeft', hijZijHet: 'heeft', wij: 'hebben', jullie: 'hebben', zij: 'hebben' },
    pastSimple: { ik: 'had', jij: 'had', u: 'had', hijZijHet: 'had', wij: 'hadden', jullie: 'hadden', zij: 'hadden' },
    imperative: 'heb!',
    examples: [
      { dutch: 'Ik heb een hond.', english: 'I have a dog.' },
      { dutch: 'Zij heeft twee kinderen.', english: 'She has two children.' },
    ],
    notes: 'Irregular. Inversion with jij: "Heb jij?" (not "Hebt jij?").',
  },
  {
    infinitive: 'zijn',
    translation: 'to be',
    auxiliary: 'zijn',
    pastParticiple: 'geweest',
    isRegular: false,
    present: { ik: 'ben', jij: 'bent', u: 'bent / is', hijZijHet: 'is', wij: 'zijn', jullie: 'zijn', zij: 'zijn' },
    pastSimple: { ik: 'was', jij: 'was', u: 'was', hijZijHet: 'was', wij: 'waren', jullie: 'waren', zij: 'waren' },
    imperative: 'wees!',
    examples: [
      { dutch: 'Ik ben student.', english: 'I am a student.' },
      { dutch: 'Wij zijn op kantoor.', english: 'We are at the office.' },
    ],
    notes: 'Completely irregular. Inversion: "Ben jij?" (not "Bent jij?").',
  },

  // ===== REGULAR VERBS (present tense topic) =====
  {
    infinitive: 'werken',
    translation: 'to work',
    auxiliary: 'hebben',
    pastParticiple: 'gewerkt',
    isRegular: true,
    present: { ik: 'werk', jij: 'werkt', u: 'werkt', hijZijHet: 'werkt', wij: 'werken', jullie: 'werken', zij: 'werken' },
    pastSimple: { ik: 'werkte', jij: 'werkte', u: 'werkte', hijZijHet: 'werkte', wij: 'werkten', jullie: 'werkten', zij: 'werkten' },
    imperative: 'werk!',
    examples: [
      { dutch: 'Ik werk elke dag.', english: 'I work every day.' },
      { dutch: 'Zij werkt bij een groot bedrijf.', english: 'She works at a large company.' },
    ],
  },
  {
    infinitive: 'wonen',
    translation: 'to live (reside)',
    auxiliary: 'hebben',
    pastParticiple: 'gewoond',
    isRegular: true,
    present: { ik: 'woon', jij: 'woont', u: 'woont', hijZijHet: 'woont', wij: 'wonen', jullie: 'wonen', zij: 'wonen' },
    pastSimple: { ik: 'woonde', jij: 'woonde', u: 'woonde', hijZijHet: 'woonde', wij: 'woonden', jullie: 'woonden', zij: 'woonden' },
    imperative: 'woon!',
    examples: [
      { dutch: 'Jij woont in Amsterdam.', english: 'You live in Amsterdam.' },
      { dutch: 'Wij woonden vroeger in Rotterdam.', english: 'We used to live in Rotterdam.' },
    ],
  },
  {
    infinitive: 'fietsen',
    translation: 'to cycle',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gefietst',
    isRegular: true,
    present: { ik: 'fiets', jij: 'fietst', u: 'fietst', hijZijHet: 'fietst', wij: 'fietsen', jullie: 'fietsen', zij: 'fietsen' },
    pastSimple: { ik: 'fietste', jij: 'fietste', u: 'fietste', hijZijHet: 'fietste', wij: 'fietsten', jullie: 'fietsten', zij: 'fietsten' },
    imperative: 'fiets!',
    examples: [
      { dutch: 'Ik fiets elke dag naar kantoor.', english: 'I cycle to the office every day.' },
      { dutch: 'Hij is naar school gefietst.', english: 'He cycled to school.' },
    ],
    notes: 'Uses "zijn" when movement from A to B; "hebben" otherwise.',
  },
  {
    infinitive: 'leven',
    translation: 'to live (be alive)',
    auxiliary: 'hebben',
    pastParticiple: 'geleefd',
    isRegular: true,
    present: { ik: 'leef', jij: 'leeft', u: 'leeft', hijZijHet: 'leeft', wij: 'leven', jullie: 'leven', zij: 'leven' },
    pastSimple: { ik: 'leefde', jij: 'leefde', u: 'leefde', hijZijHet: 'leefde', wij: 'leefden', jullie: 'leefden', zij: 'leefden' },
    imperative: 'leef!',
    examples: [
      { dutch: 'Hij leeft gezond.', english: 'He lives healthily.' },
    ],
    notes: 'Stem: leef (v becomes f). Past participle: geleefd (original v -> -d ending).',
  },
  {
    infinitive: 'reizen',
    translation: 'to travel',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gereisd',
    isRegular: true,
    present: { ik: 'reis', jij: 'reist', u: 'reist', hijZijHet: 'reist', wij: 'reizen', jullie: 'reizen', zij: 'reizen' },
    pastSimple: { ik: 'reisde', jij: 'reisde', u: 'reisde', hijZijHet: 'reisde', wij: 'reisden', jullie: 'reisden', zij: 'reisden' },
    imperative: 'reis!',
    examples: [
      { dutch: 'Zij reist naar Belgie.', english: 'She travels to Belgium.' },
    ],
    notes: 'Stem: reis (z becomes s). Past participle: gereisd (original z -> -d ending).',
  },
  {
    infinitive: 'maken',
    translation: 'to make',
    auxiliary: 'hebben',
    pastParticiple: 'gemaakt',
    isRegular: true,
    present: { ik: 'maak', jij: 'maakt', u: 'maakt', hijZijHet: 'maakt', wij: 'maken', jullie: 'maken', zij: 'maken' },
    pastSimple: { ik: 'maakte', jij: 'maakte', u: 'maakte', hijZijHet: 'maakte', wij: 'maakten', jullie: 'maakten', zij: 'maakten' },
    imperative: 'maak!',
    examples: [
      { dutch: 'Wij maken een rapport.', english: 'We make a report.' },
    ],
  },
  {
    infinitive: 'schrijven',
    translation: 'to write',
    auxiliary: 'hebben',
    pastParticiple: 'geschreven',
    isRegular: false,
    present: { ik: 'schrijf', jij: 'schrijft', u: 'schrijft', hijZijHet: 'schrijft', wij: 'schrijven', jullie: 'schrijven', zij: 'schrijven' },
    pastSimple: { ik: 'schreef', jij: 'schreef', u: 'schreef', hijZijHet: 'schreef', wij: 'schreven', jullie: 'schreven', zij: 'schreven' },
    imperative: 'schrijf!',
    examples: [
      { dutch: 'Zij schrijft een e-mail.', english: 'She writes an email.' },
      { dutch: 'Hij heeft een brief geschreven.', english: 'He wrote a letter.' },
    ],
  },
  {
    infinitive: 'leren',
    translation: 'to learn / to teach',
    auxiliary: 'hebben',
    pastParticiple: 'geleerd',
    isRegular: true,
    present: { ik: 'leer', jij: 'leert', u: 'leert', hijZijHet: 'leert', wij: 'leren', jullie: 'leren', zij: 'leren' },
    pastSimple: { ik: 'leerde', jij: 'leerde', u: 'leerde', hijZijHet: 'leerde', wij: 'leerden', jullie: 'leerden', zij: 'leerden' },
    imperative: 'leer!',
    examples: [
      { dutch: 'Wij leren Nederlands.', english: 'We learn Dutch.' },
    ],
  },
  {
    infinitive: 'praten',
    translation: 'to talk',
    auxiliary: 'hebben',
    pastParticiple: 'gepraat',
    isRegular: true,
    present: { ik: 'praat', jij: 'praat', u: 'praat', hijZijHet: 'praat', wij: 'praten', jullie: 'praten', zij: 'praten' },
    pastSimple: { ik: 'praatte', jij: 'praatte', u: 'praatte', hijZijHet: 'praatte', wij: 'praatten', jullie: 'praatten', zij: 'praatten' },
    imperative: 'praat!',
    examples: [
      { dutch: 'Jullie praten te hard.', english: 'You all talk too loudly.' },
    ],
  },
  {
    infinitive: 'bellen',
    translation: 'to call (phone)',
    auxiliary: 'hebben',
    pastParticiple: 'gebeld',
    isRegular: true,
    present: { ik: 'bel', jij: 'belt', u: 'belt', hijZijHet: 'belt', wij: 'bellen', jullie: 'bellen', zij: 'bellen' },
    pastSimple: { ik: 'belde', jij: 'belde', u: 'belde', hijZijHet: 'belde', wij: 'belden', jullie: 'belden', zij: 'belden' },
    imperative: 'bel!',
    examples: [
      { dutch: 'Hij belt de leverancier.', english: 'He calls the supplier.' },
    ],
  },
  {
    infinitive: 'vergaderen',
    translation: 'to have a meeting',
    auxiliary: 'hebben',
    pastParticiple: 'vergaderd',
    isRegular: true,
    present: { ik: 'vergader', jij: 'vergadert', u: 'vergadert', hijZijHet: 'vergadert', wij: 'vergaderen', jullie: 'vergaderen', zij: 'vergaderen' },
    pastSimple: { ik: 'vergaderde', jij: 'vergaderde', u: 'vergaderde', hijZijHet: 'vergaderde', wij: 'vergaderden', jullie: 'vergaderden', zij: 'vergaderden' },
    imperative: 'vergader!',
    examples: [
      { dutch: 'Wij vergaderen elke maandag.', english: 'We meet every Monday.' },
    ],
  },
  {
    infinitive: 'komen',
    translation: 'to come',
    auxiliary: 'zijn',
    pastParticiple: 'gekomen',
    isRegular: false,
    present: { ik: 'kom', jij: 'komt', u: 'komt', hijZijHet: 'komt', wij: 'komen', jullie: 'komen', zij: 'komen' },
    pastSimple: { ik: 'kwam', jij: 'kwam', u: 'kwam', hijZijHet: 'kwam', wij: 'kwamen', jullie: 'kwamen', zij: 'kwamen' },
    imperative: 'kom!',
    examples: [
      { dutch: 'Hij komt morgen.', english: 'He comes tomorrow.' },
      { dutch: 'Zij is laat gekomen.', english: 'She arrived late.' },
    ],
  },
  {
    infinitive: 'spreken',
    translation: 'to speak',
    auxiliary: 'hebben',
    pastParticiple: 'gesproken',
    isRegular: false,
    present: { ik: 'spreek', jij: 'spreekt', u: 'spreekt', hijZijHet: 'spreekt', wij: 'spreken', jullie: 'spreken', zij: 'spreken' },
    pastSimple: { ik: 'sprak', jij: 'sprak', u: 'sprak', hijZijHet: 'sprak', wij: 'spraken', jullie: 'spraken', zij: 'spraken' },
    imperative: 'spreek!',
    examples: [
      { dutch: 'Ik heb met de baas gesproken.', english: 'I spoke with the boss.' },
    ],
  },
  {
    infinitive: 'stoppen',
    translation: 'to stop',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gestopt',
    isRegular: true,
    present: { ik: 'stop', jij: 'stopt', u: 'stopt', hijZijHet: 'stopt', wij: 'stoppen', jullie: 'stoppen', zij: 'stoppen' },
    pastSimple: { ik: 'stopte', jij: 'stopte', u: 'stopte', hijZijHet: 'stopte', wij: 'stopten', jullie: 'stopten', zij: 'stopten' },
    imperative: 'stop!',
    examples: [
      { dutch: 'De bus stopt hier.', english: 'The bus stops here.' },
    ],
  },
  {
    infinitive: 'bouwen',
    translation: 'to build',
    auxiliary: 'hebben',
    pastParticiple: 'gebouwd',
    isRegular: true,
    present: { ik: 'bouw', jij: 'bouwt', u: 'bouwt', hijZijHet: 'bouwt', wij: 'bouwen', jullie: 'bouwen', zij: 'bouwen' },
    pastSimple: { ik: 'bouwde', jij: 'bouwde', u: 'bouwde', hijZijHet: 'bouwde', wij: 'bouwden', jullie: 'bouwden', zij: 'bouwden' },
    imperative: 'bouw!',
    examples: [
      { dutch: 'Zij hebben het huis gebouwd.', english: 'They built the house.' },
    ],
  },
  {
    infinitive: 'studeren',
    translation: 'to study',
    auxiliary: 'hebben',
    pastParticiple: 'gestudeerd',
    isRegular: true,
    present: { ik: 'studeer', jij: 'studeert', u: 'studeert', hijZijHet: 'studeert', wij: 'studeren', jullie: 'studeren', zij: 'studeren' },
    pastSimple: { ik: 'studeerde', jij: 'studeerde', u: 'studeerde', hijZijHet: 'studeerde', wij: 'studeerden', jullie: 'studeerden', zij: 'studeerden' },
    imperative: 'studeer!',
    examples: [
      { dutch: 'Hij studeert medicijnen.', english: 'He studies medicine.' },
    ],
  },

  // ===== IRREGULAR VERBS (perfect / imperfect topics) =====
  {
    infinitive: 'gaan',
    translation: 'to go',
    auxiliary: 'zijn',
    pastParticiple: 'gegaan',
    isRegular: false,
    present: { ik: 'ga', jij: 'gaat', u: 'gaat', hijZijHet: 'gaat', wij: 'gaan', jullie: 'gaan', zij: 'gaan' },
    pastSimple: { ik: 'ging', jij: 'ging', u: 'ging', hijZijHet: 'ging', wij: 'gingen', jullie: 'gingen', zij: 'gingen' },
    imperative: 'ga!',
    examples: [
      { dutch: 'Hij ging naar de winkel.', english: 'He went to the store.' },
      { dutch: 'Zij is naar huis gegaan.', english: 'She went home.' },
    ],
  },
  {
    infinitive: 'doen',
    translation: 'to do',
    auxiliary: 'hebben',
    pastParticiple: 'gedaan',
    isRegular: false,
    present: { ik: 'doe', jij: 'doet', u: 'doet', hijZijHet: 'doet', wij: 'doen', jullie: 'doen', zij: 'doen' },
    pastSimple: { ik: 'deed', jij: 'deed', u: 'deed', hijZijHet: 'deed', wij: 'deden', jullie: 'deden', zij: 'deden' },
    imperative: 'doe!',
    examples: [
      { dutch: 'Wat deed hij gisteren?', english: 'What did he do yesterday?' },
    ],
  },
  {
    infinitive: 'zien',
    translation: 'to see',
    auxiliary: 'hebben',
    pastParticiple: 'gezien',
    isRegular: false,
    present: { ik: 'zie', jij: 'ziet', u: 'ziet', hijZijHet: 'ziet', wij: 'zien', jullie: 'zien', zij: 'zien' },
    pastSimple: { ik: 'zag', jij: 'zag', u: 'zag', hijZijHet: 'zag', wij: 'zagen', jullie: 'zagen', zij: 'zagen' },
    imperative: 'zie!',
    examples: [
      { dutch: 'Ik zag hem gisteren.', english: 'I saw him yesterday.' },
    ],
  },
  {
    infinitive: 'nemen',
    translation: 'to take',
    auxiliary: 'hebben',
    pastParticiple: 'genomen',
    isRegular: false,
    present: { ik: 'neem', jij: 'neemt', u: 'neemt', hijZijHet: 'neemt', wij: 'nemen', jullie: 'nemen', zij: 'nemen' },
    pastSimple: { ik: 'nam', jij: 'nam', u: 'nam', hijZijHet: 'nam', wij: 'namen', jullie: 'namen', zij: 'namen' },
    imperative: 'neem!',
    examples: [
      { dutch: 'Hij nam de trein.', english: 'He took the train.' },
    ],
  },
  {
    infinitive: 'geven',
    translation: 'to give',
    auxiliary: 'hebben',
    pastParticiple: 'gegeven',
    isRegular: false,
    present: { ik: 'geef', jij: 'geeft', u: 'geeft', hijZijHet: 'geeft', wij: 'geven', jullie: 'geven', zij: 'geven' },
    pastSimple: { ik: 'gaf', jij: 'gaf', u: 'gaf', hijZijHet: 'gaf', wij: 'gaven', jullie: 'gaven', zij: 'gaven' },
    imperative: 'geef!',
    examples: [
      { dutch: 'De manager gaf een presentatie.', english: 'The manager gave a presentation.' },
    ],
  },
  {
    infinitive: 'lezen',
    translation: 'to read',
    auxiliary: 'hebben',
    pastParticiple: 'gelezen',
    isRegular: false,
    present: { ik: 'lees', jij: 'leest', u: 'leest', hijZijHet: 'leest', wij: 'lezen', jullie: 'lezen', zij: 'lezen' },
    pastSimple: { ik: 'las', jij: 'las', u: 'las', hijZijHet: 'las', wij: 'lazen', jullie: 'lazen', zij: 'lazen' },
    imperative: 'lees!',
    examples: [
      { dutch: 'Ik heb de krant gelezen.', english: 'I read the newspaper.' },
    ],
  },
  {
    infinitive: 'eten',
    translation: 'to eat',
    auxiliary: 'hebben',
    pastParticiple: 'gegeten',
    isRegular: false,
    present: { ik: 'eet', jij: 'eet', u: 'eet', hijZijHet: 'eet', wij: 'eten', jullie: 'eten', zij: 'eten' },
    pastSimple: { ik: 'at', jij: 'at', u: 'at', hijZijHet: 'at', wij: 'aten', jullie: 'aten', zij: 'aten' },
    imperative: 'eet!',
    examples: [
      { dutch: 'Wij hebben pasta gegeten.', english: 'We ate pasta.' },
    ],
  },
  {
    infinitive: 'drinken',
    translation: 'to drink',
    auxiliary: 'hebben',
    pastParticiple: 'gedronken',
    isRegular: false,
    present: { ik: 'drink', jij: 'drinkt', u: 'drinkt', hijZijHet: 'drinkt', wij: 'drinken', jullie: 'drinken', zij: 'drinken' },
    pastSimple: { ik: 'dronk', jij: 'dronk', u: 'dronk', hijZijHet: 'dronk', wij: 'dronken', jullie: 'dronken', zij: 'dronken' },
    imperative: 'drink!',
    examples: [
      { dutch: 'Hij heeft water gedronken.', english: 'He drank water.' },
    ],
  },
  {
    infinitive: 'rijden',
    translation: 'to drive / to ride',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gereden',
    isRegular: false,
    present: { ik: 'rijd', jij: 'rijdt', u: 'rijdt', hijZijHet: 'rijdt', wij: 'rijden', jullie: 'rijden', zij: 'rijden' },
    pastSimple: { ik: 'reed', jij: 'reed', u: 'reed', hijZijHet: 'reed', wij: 'reden', jullie: 'reden', zij: 'reden' },
    imperative: 'rijd!',
    examples: [
      { dutch: 'Ik ben naar Utrecht gereden.', english: 'I drove to Utrecht.' },
    ],
    notes: 'Uses "zijn" for movement A to B; "hebben" for driving in general.',
  },
  {
    infinitive: 'slapen',
    translation: 'to sleep',
    auxiliary: 'hebben',
    pastParticiple: 'geslapen',
    isRegular: false,
    present: { ik: 'slaap', jij: 'slaapt', u: 'slaapt', hijZijHet: 'slaapt', wij: 'slapen', jullie: 'slapen', zij: 'slapen' },
    pastSimple: { ik: 'sliep', jij: 'sliep', u: 'sliep', hijZijHet: 'sliep', wij: 'sliepen', jullie: 'sliepen', zij: 'sliepen' },
    imperative: 'slaap!',
    examples: [
      { dutch: 'Het kind heeft goed geslapen.', english: 'The child slept well.' },
    ],
  },
  {
    infinitive: 'beginnen',
    translation: 'to begin',
    auxiliary: 'zijn',
    pastParticiple: 'begonnen',
    isRegular: false,
    present: { ik: 'begin', jij: 'begint', u: 'begint', hijZijHet: 'begint', wij: 'beginnen', jullie: 'beginnen', zij: 'beginnen' },
    pastSimple: { ik: 'begon', jij: 'begon', u: 'begon', hijZijHet: 'begon', wij: 'begonnen', jullie: 'begonnen', zij: 'begonnen' },
    imperative: 'begin!',
    examples: [
      { dutch: 'De vergadering is begonnen.', english: 'The meeting has started.' },
    ],
  },
  {
    infinitive: 'vinden',
    translation: 'to find',
    auxiliary: 'hebben',
    pastParticiple: 'gevonden',
    isRegular: false,
    present: { ik: 'vind', jij: 'vindt', u: 'vindt', hijZijHet: 'vindt', wij: 'vinden', jullie: 'vinden', zij: 'vinden' },
    pastSimple: { ik: 'vond', jij: 'vond', u: 'vond', hijZijHet: 'vond', wij: 'vonden', jullie: 'vonden', zij: 'vonden' },
    imperative: 'vind!',
    examples: [
      { dutch: 'Hij heeft de sleutels gevonden.', english: 'He found the keys.' },
    ],
  },

  // ===== MODAL VERBS =====
  {
    infinitive: 'kunnen',
    translation: 'can / to be able to',
    auxiliary: 'hebben',
    pastParticiple: 'gekund',
    isRegular: false,
    present: { ik: 'kan', jij: 'kunt / kan', u: 'kunt / kan', hijZijHet: 'kan', wij: 'kunnen', jullie: 'kunnen', zij: 'kunnen' },
    pastSimple: { ik: 'kon', jij: 'kon', u: 'kon', hijZijHet: 'kon', wij: 'konden', jullie: 'konden', zij: 'konden' },
    imperative: '-',
    examples: [
      { dutch: 'Ik kan goed zwemmen.', english: 'I can swim well.' },
    ],
    notes: 'Modal verb. "Kan" is increasingly used for all singular persons in spoken Dutch.',
  },
  {
    infinitive: 'moeten',
    translation: 'must / to have to',
    auxiliary: 'hebben',
    pastParticiple: 'gemoeten',
    isRegular: false,
    present: { ik: 'moet', jij: 'moet', u: 'moet', hijZijHet: 'moet', wij: 'moeten', jullie: 'moeten', zij: 'moeten' },
    pastSimple: { ik: 'moest', jij: 'moest', u: 'moest', hijZijHet: 'moest', wij: 'moesten', jullie: 'moesten', zij: 'moesten' },
    imperative: '-',
    examples: [
      { dutch: 'Zij moet morgen werken.', english: 'She has to work tomorrow.' },
    ],
    notes: 'Modal verb expressing obligation or necessity.',
  },
  {
    infinitive: 'mogen',
    translation: 'may / to be allowed to',
    auxiliary: 'hebben',
    pastParticiple: 'gemogen',
    isRegular: false,
    present: { ik: 'mag', jij: 'mag', u: 'mag', hijZijHet: 'mag', wij: 'mogen', jullie: 'mogen', zij: 'mogen' },
    pastSimple: { ik: 'mocht', jij: 'mocht', u: 'mocht', hijZijHet: 'mocht', wij: 'mochten', jullie: 'mochten', zij: 'mochten' },
    imperative: '-',
    examples: [
      { dutch: 'Mag ik hier zitten?', english: 'May I sit here?' },
    ],
    notes: 'Modal verb expressing permission.',
  },
  {
    infinitive: 'willen',
    translation: 'to want to',
    auxiliary: 'hebben',
    pastParticiple: 'gewild',
    isRegular: false,
    present: { ik: 'wil', jij: 'wilt / wil', u: 'wilt', hijZijHet: 'wil', wij: 'willen', jullie: 'willen', zij: 'willen' },
    pastSimple: { ik: 'wilde / wou', jij: 'wilde / wou', u: 'wilde / wou', hijZijHet: 'wilde / wou', wij: 'wilden / wouden', jullie: 'wilden / wouden', zij: 'wilden / wouden' },
    imperative: '-',
    examples: [
      { dutch: 'Wij willen een huis kopen.', english: 'We want to buy a house.' },
    ],
    notes: 'Modal verb. "Wil" is common for all singular in spoken Dutch.',
  },
  {
    infinitive: 'zullen',
    translation: 'shall / will',
    auxiliary: 'hebben',
    pastParticiple: '-',
    isRegular: false,
    present: { ik: 'zal', jij: 'zult / zal', u: 'zult', hijZijHet: 'zal', wij: 'zullen', jullie: 'zullen', zij: 'zullen' },
    pastSimple: { ik: 'zou', jij: 'zou', u: 'zou', hijZijHet: 'zou', wij: 'zouden', jullie: 'zouden', zij: 'zouden' },
    imperative: '-',
    examples: [
      { dutch: 'Het zal morgen regenen.', english: 'It will rain tomorrow.' },
      { dutch: 'Zullen we vanavond uit eten gaan?', english: 'Shall we eat out tonight?' },
    ],
    notes: 'Modal verb used for future and suggestions.',
  },
  {
    infinitive: 'hoeven',
    translation: 'to need to (negative only)',
    auxiliary: 'hebben',
    pastParticiple: 'gehoeven',
    isRegular: false,
    present: { ik: 'hoef', jij: 'hoeft', u: 'hoeft', hijZijHet: 'hoeft', wij: 'hoeven', jullie: 'hoeven', zij: 'hoeven' },
    pastSimple: { ik: 'hoefde', jij: 'hoefde', u: 'hoefde', hijZijHet: 'hoefde', wij: 'hoefden', jullie: 'hoefden', zij: 'hoefden' },
    imperative: '-',
    examples: [
      { dutch: 'Je hoeft niet te komen.', english: "You don't need to come." },
    ],
    notes: 'Only used in negative sentences with "niet" or "geen", followed by "te" + infinitive.',
  },

  // ===== SEPARABLE VERBS =====
  {
    infinitive: 'aankomen',
    translation: 'to arrive',
    auxiliary: 'zijn',
    pastParticiple: 'aangekomen',
    separablePrefix: 'aan',
    isRegular: false,
    present: { ik: 'kom aan', jij: 'komt aan', u: 'komt aan', hijZijHet: 'komt aan', wij: 'komen aan', jullie: 'komen aan', zij: 'komen aan' },
    pastSimple: { ik: 'kwam aan', jij: 'kwam aan', u: 'kwam aan', hijZijHet: 'kwam aan', wij: 'kwamen aan', jullie: 'kwamen aan', zij: 'kwamen aan' },
    imperative: 'kom aan!',
    examples: [
      { dutch: 'De trein komt om 9 uur aan.', english: 'The train arrives at 9 o\'clock.' },
    ],
  },
  {
    infinitive: 'afspreken',
    translation: 'to arrange / to agree',
    auxiliary: 'hebben',
    pastParticiple: 'afgesproken',
    separablePrefix: 'af',
    isRegular: false,
    present: { ik: 'spreek af', jij: 'spreekt af', u: 'spreekt af', hijZijHet: 'spreekt af', wij: 'spreken af', jullie: 'spreken af', zij: 'spreken af' },
    pastSimple: { ik: 'sprak af', jij: 'sprak af', u: 'sprak af', hijZijHet: 'sprak af', wij: 'spraken af', jullie: 'spraken af', zij: 'spraken af' },
    imperative: 'spreek af!',
    examples: [
      { dutch: 'Wij spreken een tijd af.', english: 'We arrange a time.' },
    ],
  },
  {
    infinitive: 'opbellen',
    translation: 'to call (phone)',
    auxiliary: 'hebben',
    pastParticiple: 'opgebeld',
    separablePrefix: 'op',
    isRegular: true,
    present: { ik: 'bel op', jij: 'belt op', u: 'belt op', hijZijHet: 'belt op', wij: 'bellen op', jullie: 'bellen op', zij: 'bellen op' },
    pastSimple: { ik: 'belde op', jij: 'belde op', u: 'belde op', hijZijHet: 'belde op', wij: 'belden op', jullie: 'belden op', zij: 'belden op' },
    imperative: 'bel op!',
    examples: [
      { dutch: 'Ik bel je morgen op.', english: 'I will call you tomorrow.' },
    ],
  },
  {
    infinitive: 'invullen',
    translation: 'to fill in',
    auxiliary: 'hebben',
    pastParticiple: 'ingevuld',
    separablePrefix: 'in',
    isRegular: true,
    present: { ik: 'vul in', jij: 'vult in', u: 'vult in', hijZijHet: 'vult in', wij: 'vullen in', jullie: 'vullen in', zij: 'vullen in' },
    pastSimple: { ik: 'vulde in', jij: 'vulde in', u: 'vulde in', hijZijHet: 'vulde in', wij: 'vulden in', jullie: 'vulden in', zij: 'vulden in' },
    imperative: 'vul in!',
    examples: [
      { dutch: 'Ik vul het formulier in.', english: 'I fill in the form.' },
    ],
  },
  {
    infinitive: 'meenemen',
    translation: 'to take along',
    auxiliary: 'hebben',
    pastParticiple: 'meegenomen',
    separablePrefix: 'mee',
    isRegular: false,
    present: { ik: 'neem mee', jij: 'neemt mee', u: 'neemt mee', hijZijHet: 'neemt mee', wij: 'nemen mee', jullie: 'nemen mee', zij: 'nemen mee' },
    pastSimple: { ik: 'nam mee', jij: 'nam mee', u: 'nam mee', hijZijHet: 'nam mee', wij: 'namen mee', jullie: 'namen mee', zij: 'namen mee' },
    imperative: 'neem mee!',
    examples: [
      { dutch: 'Ik heb mijn laptop meegenomen.', english: 'I took my laptop along.' },
    ],
  },
  {
    infinitive: 'uitnodigen',
    translation: 'to invite',
    auxiliary: 'hebben',
    pastParticiple: 'uitgenodigd',
    separablePrefix: 'uit',
    isRegular: true,
    present: { ik: 'nodig uit', jij: 'nodigt uit', u: 'nodigt uit', hijZijHet: 'nodigt uit', wij: 'nodigen uit', jullie: 'nodigen uit', zij: 'nodigen uit' },
    pastSimple: { ik: 'nodigde uit', jij: 'nodigde uit', u: 'nodigde uit', hijZijHet: 'nodigde uit', wij: 'nodigden uit', jullie: 'nodigden uit', zij: 'nodigden uit' },
    imperative: 'nodig uit!',
    examples: [
      { dutch: 'Zij nodigt haar vrienden uit.', english: 'She invites her friends.' },
    ],
  },
  {
    infinitive: 'terugkomen',
    translation: 'to come back',
    auxiliary: 'zijn',
    pastParticiple: 'teruggekomen',
    separablePrefix: 'terug',
    isRegular: false,
    present: { ik: 'kom terug', jij: 'komt terug', u: 'komt terug', hijZijHet: 'komt terug', wij: 'komen terug', jullie: 'komen terug', zij: 'komen terug' },
    pastSimple: { ik: 'kwam terug', jij: 'kwam terug', u: 'kwam terug', hijZijHet: 'kwam terug', wij: 'kwamen terug', jullie: 'kwamen terug', zij: 'kwamen terug' },
    imperative: 'kom terug!',
    examples: [
      { dutch: 'Ik kom om vijf uur terug.', english: 'I come back at five o\'clock.' },
    ],
  },
  {
    infinitive: 'doorgaan',
    translation: 'to continue',
    auxiliary: 'zijn',
    pastParticiple: 'doorgegaan',
    separablePrefix: 'door',
    isRegular: false,
    present: { ik: 'ga door', jij: 'gaat door', u: 'gaat door', hijZijHet: 'gaat door', wij: 'gaan door', jullie: 'gaan door', zij: 'gaan door' },
    pastSimple: { ik: 'ging door', jij: 'ging door', u: 'ging door', hijZijHet: 'ging door', wij: 'gingen door', jullie: 'gingen door', zij: 'gingen door' },
    imperative: 'ga door!',
    examples: [
      { dutch: 'De les gaat door tot zes uur.', english: 'The lesson continues until six.' },
    ],
  },
  {
    infinitive: 'weggaan',
    translation: 'to leave / to go away',
    auxiliary: 'zijn',
    pastParticiple: 'weggegaan',
    separablePrefix: 'weg',
    isRegular: false,
    present: { ik: 'ga weg', jij: 'gaat weg', u: 'gaat weg', hijZijHet: 'gaat weg', wij: 'gaan weg', jullie: 'gaan weg', zij: 'gaan weg' },
    pastSimple: { ik: 'ging weg', jij: 'ging weg', u: 'ging weg', hijZijHet: 'ging weg', wij: 'gingen weg', jullie: 'gingen weg', zij: 'gingen weg' },
    imperative: 'ga weg!',
    examples: [
      { dutch: 'Hij gaat om drie uur weg.', english: 'He leaves at three o\'clock.' },
    ],
  },
  {
    infinitive: 'bijdragen',
    translation: 'to contribute',
    auxiliary: 'hebben',
    pastParticiple: 'bijgedragen',
    separablePrefix: 'bij',
    isRegular: false,
    present: { ik: 'draag bij', jij: 'draagt bij', u: 'draagt bij', hijZijHet: 'draagt bij', wij: 'dragen bij', jullie: 'dragen bij', zij: 'dragen bij' },
    pastSimple: { ik: 'droeg bij', jij: 'droeg bij', u: 'droeg bij', hijZijHet: 'droeg bij', wij: 'droegen bij', jullie: 'droegen bij', zij: 'droegen bij' },
    imperative: 'draag bij!',
    examples: [
      { dutch: 'Hij draagt veel bij.', english: 'He contributes a lot.' },
    ],
  },

  // ===== INSEPARABLE PREFIX VERBS (perfectum-regular topic) =====
  {
    infinitive: 'betalen',
    translation: 'to pay',
    auxiliary: 'hebben',
    pastParticiple: 'betaald',
    isRegular: true,
    present: { ik: 'betaal', jij: 'betaalt', u: 'betaalt', hijZijHet: 'betaalt', wij: 'betalen', jullie: 'betalen', zij: 'betalen' },
    pastSimple: { ik: 'betaalde', jij: 'betaalde', u: 'betaalde', hijZijHet: 'betaalde', wij: 'betaalden', jullie: 'betaalden', zij: 'betaalden' },
    imperative: 'betaal!',
    examples: [
      { dutch: 'Ik heb de rekening betaald.', english: 'I paid the bill.' },
    ],
    notes: 'Inseparable prefix be-. No ge- in past participle.',
  },
  {
    infinitive: 'vertellen',
    translation: 'to tell',
    auxiliary: 'hebben',
    pastParticiple: 'verteld',
    isRegular: true,
    present: { ik: 'vertel', jij: 'vertelt', u: 'vertelt', hijZijHet: 'vertelt', wij: 'vertellen', jullie: 'vertellen', zij: 'vertellen' },
    pastSimple: { ik: 'vertelde', jij: 'vertelde', u: 'vertelde', hijZijHet: 'vertelde', wij: 'vertelden', jullie: 'vertelden', zij: 'vertelden' },
    imperative: 'vertel!',
    examples: [
      { dutch: 'Zij heeft het verhaal verteld.', english: 'She told the story.' },
    ],
    notes: 'Inseparable prefix ver-. No ge- in past participle.',
  },
  {
    infinitive: 'gebruiken',
    translation: 'to use',
    auxiliary: 'hebben',
    pastParticiple: 'gebruikt',
    isRegular: true,
    present: { ik: 'gebruik', jij: 'gebruikt', u: 'gebruikt', hijZijHet: 'gebruikt', wij: 'gebruiken', jullie: 'gebruiken', zij: 'gebruiken' },
    pastSimple: { ik: 'gebruikte', jij: 'gebruikte', u: 'gebruikte', hijZijHet: 'gebruikte', wij: 'gebruikten', jullie: 'gebruikten', zij: 'gebruikten' },
    imperative: 'gebruik!',
    examples: [
      { dutch: 'Wij hebben de computer gebruikt.', english: 'We used the computer.' },
    ],
    notes: 'Inseparable prefix ge-. No extra ge- in past participle.',
  },
  {
    infinitive: 'verhuizen',
    translation: 'to move (house)',
    auxiliary: 'zijn',
    pastParticiple: 'verhuisd',
    isRegular: true,
    present: { ik: 'verhuis', jij: 'verhuist', u: 'verhuist', hijZijHet: 'verhuist', wij: 'verhuizen', jullie: 'verhuizen', zij: 'verhuizen' },
    pastSimple: { ik: 'verhuisde', jij: 'verhuisde', u: 'verhuisde', hijZijHet: 'verhuisde', wij: 'verhuisden', jullie: 'verhuisden', zij: 'verhuisden' },
    imperative: 'verhuis!',
    examples: [
      { dutch: 'Wij zijn vorig jaar verhuisd.', english: 'We moved last year.' },
    ],
    notes: 'Inseparable prefix ver-. No ge- in past participle. Uses "zijn".',
  },
  {
    infinitive: 'herhalen',
    translation: 'to repeat',
    auxiliary: 'hebben',
    pastParticiple: 'herhaald',
    isRegular: true,
    present: { ik: 'herhaal', jij: 'herhaalt', u: 'herhaalt', hijZijHet: 'herhaalt', wij: 'herhalen', jullie: 'herhalen', zij: 'herhalen' },
    pastSimple: { ik: 'herhaalde', jij: 'herhaalde', u: 'herhaalde', hijZijHet: 'herhaalde', wij: 'herhaalden', jullie: 'herhaalden', zij: 'herhaalden' },
    imperative: 'herhaal!',
    examples: [
      { dutch: 'De leraar heeft de les herhaald.', english: 'The teacher repeated the lesson.' },
    ],
    notes: 'Inseparable prefix her-. No ge- in past participle.',
  },
  {
    infinitive: 'ontdekken',
    translation: 'to discover',
    auxiliary: 'hebben',
    pastParticiple: 'ontdekt',
    isRegular: true,
    present: { ik: 'ontdek', jij: 'ontdekt', u: 'ontdekt', hijZijHet: 'ontdekt', wij: 'ontdekken', jullie: 'ontdekken', zij: 'ontdekken' },
    pastSimple: { ik: 'ontdekte', jij: 'ontdekte', u: 'ontdekte', hijZijHet: 'ontdekte', wij: 'ontdekten', jullie: 'ontdekten', zij: 'ontdekten' },
    imperative: 'ontdek!',
    examples: [
      { dutch: 'Ze hebben een fout ontdekt.', english: 'They discovered a mistake.' },
    ],
    notes: 'Inseparable prefix ont-. No ge- in past participle.',
  },

  // ===== REFLEXIVE VERBS (a sample — base verbs not already listed) =====
  {
    infinitive: 'voelen',
    translation: 'to feel',
    auxiliary: 'hebben',
    pastParticiple: 'gevoeld',
    reflexive: true,
    isRegular: true,
    present: { ik: 'voel', jij: 'voelt', u: 'voelt', hijZijHet: 'voelt', wij: 'voelen', jullie: 'voelen', zij: 'voelen' },
    pastSimple: { ik: 'voelde', jij: 'voelde', u: 'voelde', hijZijHet: 'voelde', wij: 'voelden', jullie: 'voelden', zij: 'voelden' },
    imperative: 'voel!',
    examples: [
      { dutch: 'Ik voel me goed.', english: 'I feel well.' },
    ],
    notes: 'Commonly used reflexively: zich voelen.',
  },
  {
    infinitive: 'voorstellen',
    translation: 'to introduce / to imagine',
    auxiliary: 'hebben',
    pastParticiple: 'voorgesteld',
    separablePrefix: 'voor',
    reflexive: true,
    isRegular: true,
    present: { ik: 'stel voor', jij: 'stelt voor', u: 'stelt voor', hijZijHet: 'stelt voor', wij: 'stellen voor', jullie: 'stellen voor', zij: 'stellen voor' },
    pastSimple: { ik: 'stelde voor', jij: 'stelde voor', u: 'stelde voor', hijZijHet: 'stelde voor', wij: 'stelden voor', jullie: 'stelden voor', zij: 'stelden voor' },
    imperative: 'stel voor!',
    examples: [
      { dutch: 'Mag ik mij voorstellen?', english: 'May I introduce myself?' },
    ],
    notes: 'Separable + reflexive: zich voorstellen.',
  },
  {
    infinitive: 'herinneren',
    translation: 'to remember',
    auxiliary: 'hebben',
    pastParticiple: 'herinnerd',
    reflexive: true,
    isRegular: true,
    present: { ik: 'herinner', jij: 'herinnert', u: 'herinnert', hijZijHet: 'herinnert', wij: 'herinneren', jullie: 'herinneren', zij: 'herinneren' },
    pastSimple: { ik: 'herinnerde', jij: 'herinnerde', u: 'herinnerde', hijZijHet: 'herinnerde', wij: 'herinnerden', jullie: 'herinnerden', zij: 'herinnerden' },
    imperative: 'herinner!',
    examples: [
      { dutch: 'Ik herinner me dat nog.', english: 'I still remember that.' },
    ],
    notes: 'Inseparable prefix her-. Reflexive: zich herinneren.',
  },
  {
    infinitive: 'aanmelden',
    translation: 'to register / to sign up',
    auxiliary: 'hebben',
    pastParticiple: 'aangemeld',
    separablePrefix: 'aan',
    reflexive: true,
    isRegular: true,
    present: { ik: 'meld aan', jij: 'meldt aan', u: 'meldt aan', hijZijHet: 'meldt aan', wij: 'melden aan', jullie: 'melden aan', zij: 'melden aan' },
    pastSimple: { ik: 'meldde aan', jij: 'meldde aan', u: 'meldde aan', hijZijHet: 'meldde aan', wij: 'meldden aan', jullie: 'meldden aan', zij: 'meldden aan' },
    imperative: 'meld aan!',
    examples: [
      { dutch: 'Ik heb me aangemeld voor de cursus.', english: 'I registered for the course.' },
    ],
    notes: 'Separable + reflexive: zich aanmelden.',
  },

  // ===== ADDITIONAL VERBS from perfectum-regular (inseparable prefix) =====
  {
    infinitive: 'beloven',
    translation: 'to promise',
    auxiliary: 'hebben',
    pastParticiple: 'beloofd',
    isRegular: true,
    present: { ik: 'beloof', jij: 'belooft', u: 'belooft', hijZijHet: 'belooft', wij: 'beloven', jullie: 'beloven', zij: 'beloven' },
    pastSimple: { ik: 'beloofde', jij: 'beloofde', u: 'beloofde', hijZijHet: 'beloofde', wij: 'beloofden', jullie: 'beloofden', zij: 'beloofden' },
    imperative: 'beloof!',
    examples: [
      { dutch: 'Hij heeft het beloofd.', english: 'He promised it.' },
    ],
    notes: 'Inseparable prefix be-. No ge- in past participle.',
  },
  {
    infinitive: 'erkennen',
    translation: 'to acknowledge / to recognize',
    auxiliary: 'hebben',
    pastParticiple: 'erkend',
    isRegular: true,
    present: { ik: 'erken', jij: 'erkent', u: 'erkent', hijZijHet: 'erkent', wij: 'erkennen', jullie: 'erkennen', zij: 'erkennen' },
    pastSimple: { ik: 'erkende', jij: 'erkende', u: 'erkende', hijZijHet: 'erkende', wij: 'erkenden', jullie: 'erkenden', zij: 'erkenden' },
    imperative: 'erken!',
    examples: [
      { dutch: 'Zij heeft het probleem erkend.', english: 'She acknowledged the problem.' },
    ],
    notes: 'Inseparable prefix er-. No ge- in past participle.',
  },
  {
    infinitive: 'geloven',
    translation: 'to believe',
    auxiliary: 'hebben',
    pastParticiple: 'geloofd',
    isRegular: true,
    present: { ik: 'geloof', jij: 'gelooft', u: 'gelooft', hijZijHet: 'gelooft', wij: 'geloven', jullie: 'geloven', zij: 'geloven' },
    pastSimple: { ik: 'geloofde', jij: 'geloofde', u: 'geloofde', hijZijHet: 'geloofde', wij: 'geloofden', jullie: 'geloofden', zij: 'geloofden' },
    imperative: 'geloof!',
    examples: [
      { dutch: 'Hij heeft mij geloofd.', english: 'He believed me.' },
    ],
    notes: 'Inseparable prefix ge-. No extra ge- in past participle.',
  },

  // ===== EXTRA VERBS appearing in tables =====
  {
    infinitive: 'straffen',
    translation: 'to punish',
    auxiliary: 'hebben',
    pastParticiple: 'gestraft',
    isRegular: true,
    present: { ik: 'straf', jij: 'straft', u: 'straft', hijZijHet: 'straft', wij: 'straffen', jullie: 'straffen', zij: 'straffen' },
    pastSimple: { ik: 'strafte', jij: 'strafte', u: 'strafte', hijZijHet: 'strafte', wij: 'straften', jullie: 'straften', zij: 'straften' },
    imperative: 'straf!',
    examples: [
      { dutch: 'De leraar heeft het kind gestraft.', english: 'The teacher punished the child.' },
    ],
  },
  {
    infinitive: 'lachen',
    translation: 'to laugh',
    auxiliary: 'hebben',
    pastParticiple: 'gelachen',
    isRegular: false,
    present: { ik: 'lach', jij: 'lacht', u: 'lacht', hijZijHet: 'lacht', wij: 'lachen', jullie: 'lachen', zij: 'lachen' },
    pastSimple: { ik: 'lachte', jij: 'lachte', u: 'lachte', hijZijHet: 'lachte', wij: 'lachten', jullie: 'lachten', zij: 'lachten' },
    imperative: 'lach!',
    examples: [
      { dutch: 'Wij hebben hard gelachen.', english: 'We laughed hard.' },
    ],
  },
  {
    infinitive: 'opruimen',
    translation: 'to tidy up',
    auxiliary: 'hebben',
    pastParticiple: 'opgeruimd',
    separablePrefix: 'op',
    isRegular: true,
    present: { ik: 'ruim op', jij: 'ruimt op', u: 'ruimt op', hijZijHet: 'ruimt op', wij: 'ruimen op', jullie: 'ruimen op', zij: 'ruimen op' },
    pastSimple: { ik: 'ruimde op', jij: 'ruimde op', u: 'ruimde op', hijZijHet: 'ruimde op', wij: 'ruimden op', jullie: 'ruimden op', zij: 'ruimden op' },
    imperative: 'ruim op!',
    examples: [
      { dutch: 'Hij heeft de kamer opgeruimd.', english: 'He tidied up the room.' },
    ],
  },
  {
    infinitive: 'aanmaken',
    translation: 'to create / to turn on',
    auxiliary: 'hebben',
    pastParticiple: 'aangemaakt',
    separablePrefix: 'aan',
    isRegular: true,
    present: { ik: 'maak aan', jij: 'maakt aan', u: 'maakt aan', hijZijHet: 'maakt aan', wij: 'maken aan', jullie: 'maken aan', zij: 'maken aan' },
    pastSimple: { ik: 'maakte aan', jij: 'maakte aan', u: 'maakte aan', hijZijHet: 'maakte aan', wij: 'maakten aan', jullie: 'maakten aan', zij: 'maakten aan' },
    imperative: 'maak aan!',
    examples: [
      { dutch: 'Zij heeft een account aangemaakt.', english: 'She created an account.' },
    ],
  },

  // ===== VOCABULARY PAGE: Everyday Verbs (additional) =====
  {
    infinitive: 'zeggen',
    translation: 'to say',
    auxiliary: 'hebben',
    pastParticiple: 'gezegd',
    isRegular: true,
    present: { ik: 'zeg', jij: 'zegt', u: 'zegt', hijZijHet: 'zegt', wij: 'zeggen', jullie: 'zeggen', zij: 'zeggen' },
    pastSimple: { ik: 'zei', jij: 'zei', u: 'zei', hijZijHet: 'zei', wij: 'zeiden', jullie: 'zeiden', zij: 'zeiden' },
    imperative: 'zeg!',
    examples: [
      { dutch: 'Wat zeg je?', english: 'What are you saying?' },
    ],
  },
  {
    infinitive: 'lopen',
    translation: 'to walk / to run',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gelopen',
    isRegular: false,
    present: { ik: 'loop', jij: 'loopt', u: 'loopt', hijZijHet: 'loopt', wij: 'lopen', jullie: 'lopen', zij: 'lopen' },
    pastSimple: { ik: 'liep', jij: 'liep', u: 'liep', hijZijHet: 'liep', wij: 'liepen', jullie: 'liepen', zij: 'liepen' },
    imperative: 'loop!',
    examples: [
      { dutch: 'Ik loop naar het station.', english: 'I walk to the station.' },
    ],
    notes: 'Uses "zijn" for movement from A to B; "hebben" otherwise.',
  },
  {
    infinitive: 'kopen',
    translation: 'to buy',
    auxiliary: 'hebben',
    pastParticiple: 'gekocht',
    isRegular: false,
    present: { ik: 'koop', jij: 'koopt', u: 'koopt', hijZijHet: 'koopt', wij: 'kopen', jullie: 'kopen', zij: 'kopen' },
    pastSimple: { ik: 'kocht', jij: 'kocht', u: 'kocht', hijZijHet: 'kocht', wij: 'kochten', jullie: 'kochten', zij: 'kochten' },
    imperative: 'koop!',
    examples: [
      { dutch: 'Ik koop brood bij de bakker.', english: 'I buy bread at the bakery.' },
    ],
  },
  {
    infinitive: 'luisteren',
    translation: 'to listen',
    auxiliary: 'hebben',
    pastParticiple: 'geluisterd',
    isRegular: true,
    present: { ik: 'luister', jij: 'luistert', u: 'luistert', hijZijHet: 'luistert', wij: 'luisteren', jullie: 'luisteren', zij: 'luisteren' },
    pastSimple: { ik: 'luisterde', jij: 'luisterde', u: 'luisterde', hijZijHet: 'luisterde', wij: 'luisterden', jullie: 'luisterden', zij: 'luisterden' },
    imperative: 'luister!',
    examples: [
      { dutch: 'Ik luister naar muziek.', english: 'I listen to music.' },
    ],
  },
  {
    infinitive: 'kijken',
    translation: 'to look / to watch',
    auxiliary: 'hebben',
    pastParticiple: 'gekeken',
    isRegular: false,
    present: { ik: 'kijk', jij: 'kijkt', u: 'kijkt', hijZijHet: 'kijkt', wij: 'kijken', jullie: 'kijken', zij: 'kijken' },
    pastSimple: { ik: 'keek', jij: 'keek', u: 'keek', hijZijHet: 'keek', wij: 'keken', jullie: 'keken', zij: 'keken' },
    imperative: 'kijk!',
    examples: [
      { dutch: 'Ik kijk televisie.', english: 'I watch television.' },
    ],
  },
  {
    infinitive: 'wachten',
    translation: 'to wait',
    auxiliary: 'hebben',
    pastParticiple: 'gewacht',
    isRegular: true,
    present: { ik: 'wacht', jij: 'wacht', u: 'wacht', hijZijHet: 'wacht', wij: 'wachten', jullie: 'wachten', zij: 'wachten' },
    pastSimple: { ik: 'wachtte', jij: 'wachtte', u: 'wachtte', hijZijHet: 'wachtte', wij: 'wachtten', jullie: 'wachtten', zij: 'wachtten' },
    imperative: 'wacht!',
    examples: [
      { dutch: 'Ik wacht op de bus.', english: 'I wait for the bus.' },
    ],
  },
  {
    infinitive: 'vragen',
    translation: 'to ask',
    auxiliary: 'hebben',
    pastParticiple: 'gevraagd',
    isRegular: true,
    present: { ik: 'vraag', jij: 'vraagt', u: 'vraagt', hijZijHet: 'vraagt', wij: 'vragen', jullie: 'vragen', zij: 'vragen' },
    pastSimple: { ik: 'vroeg', jij: 'vroeg', u: 'vroeg', hijZijHet: 'vroeg', wij: 'vroegen', jullie: 'vroegen', zij: 'vroegen' },
    imperative: 'vraag!',
    examples: [
      { dutch: 'Mag ik iets vragen?', english: 'May I ask something?' },
    ],
  },
  {
    infinitive: 'begrijpen',
    translation: 'to understand',
    auxiliary: 'hebben',
    pastParticiple: 'begrepen',
    isRegular: false,
    present: { ik: 'begrijp', jij: 'begrijpt', u: 'begrijpt', hijZijHet: 'begrijpt', wij: 'begrijpen', jullie: 'begrijpen', zij: 'begrijpen' },
    pastSimple: { ik: 'begreep', jij: 'begreep', u: 'begreep', hijZijHet: 'begreep', wij: 'begrepen', jullie: 'begrepen', zij: 'begrepen' },
    imperative: 'begrijp!',
    examples: [
      { dutch: 'Ik begrijp het niet.', english: "I don't understand it." },
    ],
    notes: 'Inseparable prefix be-. No ge- in past participle.',
  },
  {
    infinitive: 'helpen',
    translation: 'to help',
    auxiliary: 'hebben',
    pastParticiple: 'geholpen',
    isRegular: false,
    present: { ik: 'help', jij: 'helpt', u: 'helpt', hijZijHet: 'helpt', wij: 'helpen', jullie: 'helpen', zij: 'helpen' },
    pastSimple: { ik: 'hielp', jij: 'hielp', u: 'hielp', hijZijHet: 'hielp', wij: 'hielpen', jullie: 'hielpen', zij: 'hielpen' },
    imperative: 'help!',
    examples: [
      { dutch: 'Kunt u mij helpen?', english: 'Can you help me?' },
    ],
  },
  {
    infinitive: 'zoeken',
    translation: 'to search / to look for',
    auxiliary: 'hebben',
    pastParticiple: 'gezocht',
    isRegular: false,
    present: { ik: 'zoek', jij: 'zoekt', u: 'zoekt', hijZijHet: 'zoekt', wij: 'zoeken', jullie: 'zoeken', zij: 'zoeken' },
    pastSimple: { ik: 'zocht', jij: 'zocht', u: 'zocht', hijZijHet: 'zocht', wij: 'zochten', jullie: 'zochten', zij: 'zochten' },
    imperative: 'zoek!',
    examples: [
      { dutch: 'Ik zoek mijn sleutels.', english: "I'm looking for my keys." },
    ],
  },
  {
    infinitive: 'proberen',
    translation: 'to try',
    auxiliary: 'hebben',
    pastParticiple: 'geprobeerd',
    isRegular: true,
    present: { ik: 'probeer', jij: 'probeert', u: 'probeert', hijZijHet: 'probeert', wij: 'proberen', jullie: 'proberen', zij: 'proberen' },
    pastSimple: { ik: 'probeerde', jij: 'probeerde', u: 'probeerde', hijZijHet: 'probeerde', wij: 'probeerden', jullie: 'probeerden', zij: 'probeerden' },
    imperative: 'probeer!',
    examples: [
      { dutch: 'Ik probeer het nog een keer.', english: 'I try it one more time.' },
    ],
  },
  {
    infinitive: 'weten',
    translation: 'to know (a fact)',
    auxiliary: 'hebben',
    pastParticiple: 'geweten',
    isRegular: false,
    present: { ik: 'weet', jij: 'weet', u: 'weet', hijZijHet: 'weet', wij: 'weten', jullie: 'weten', zij: 'weten' },
    pastSimple: { ik: 'wist', jij: 'wist', u: 'wist', hijZijHet: 'wist', wij: 'wisten', jullie: 'wisten', zij: 'wisten' },
    imperative: 'weet!',
    examples: [
      { dutch: 'Ik weet het niet.', english: "I don't know." },
    ],
  },
  {
    infinitive: 'kennen',
    translation: 'to know (a person/place)',
    auxiliary: 'hebben',
    pastParticiple: 'gekend',
    isRegular: true,
    present: { ik: 'ken', jij: 'kent', u: 'kent', hijZijHet: 'kent', wij: 'kennen', jullie: 'kennen', zij: 'kennen' },
    pastSimple: { ik: 'kende', jij: 'kende', u: 'kende', hijZijHet: 'kende', wij: 'kenden', jullie: 'kenden', zij: 'kenden' },
    imperative: 'ken!',
    examples: [
      { dutch: 'Ken je die man?', english: 'Do you know that man?' },
    ],
  },
  {
    infinitive: 'denken',
    translation: 'to think',
    auxiliary: 'hebben',
    pastParticiple: 'gedacht',
    isRegular: false,
    present: { ik: 'denk', jij: 'denkt', u: 'denkt', hijZijHet: 'denkt', wij: 'denken', jullie: 'denken', zij: 'denken' },
    pastSimple: { ik: 'dacht', jij: 'dacht', u: 'dacht', hijZijHet: 'dacht', wij: 'dachten', jullie: 'dachten', zij: 'dachten' },
    imperative: 'denk!',
    examples: [
      { dutch: 'Ik denk dat het goed is.', english: "I think it's good." },
    ],
  },
  {
    infinitive: 'zitten',
    translation: 'to sit',
    auxiliary: 'hebben',
    pastParticiple: 'gezeten',
    isRegular: false,
    present: { ik: 'zit', jij: 'zit', u: 'zit', hijZijHet: 'zit', wij: 'zitten', jullie: 'zitten', zij: 'zitten' },
    pastSimple: { ik: 'zat', jij: 'zat', u: 'zat', hijZijHet: 'zat', wij: 'zaten', jullie: 'zaten', zij: 'zaten' },
    imperative: 'zit!',
    examples: [
      { dutch: 'Ik zit op de bank.', english: 'I sit on the couch.' },
    ],
  },
  {
    infinitive: 'staan',
    translation: 'to stand',
    auxiliary: 'hebben',
    pastParticiple: 'gestaan',
    isRegular: false,
    present: { ik: 'sta', jij: 'staat', u: 'staat', hijZijHet: 'staat', wij: 'staan', jullie: 'staan', zij: 'staan' },
    pastSimple: { ik: 'stond', jij: 'stond', u: 'stond', hijZijHet: 'stond', wij: 'stonden', jullie: 'stonden', zij: 'stonden' },
    imperative: 'sta!',
    examples: [
      { dutch: 'Ik sta bij de deur.', english: 'I stand at the door.' },
    ],
  },
  {
    infinitive: 'liggen',
    translation: 'to lie (down)',
    auxiliary: 'hebben',
    pastParticiple: 'gelegen',
    isRegular: false,
    present: { ik: 'lig', jij: 'ligt', u: 'ligt', hijZijHet: 'ligt', wij: 'liggen', jullie: 'liggen', zij: 'liggen' },
    pastSimple: { ik: 'lag', jij: 'lag', u: 'lag', hijZijHet: 'lag', wij: 'lagen', jullie: 'lagen', zij: 'lagen' },
    imperative: 'lig!',
    examples: [
      { dutch: 'De kat ligt op het bed.', english: 'The cat lies on the bed.' },
    ],
  },

  // ===== MOVEMENT & DIRECTION VERBS =====
  {
    infinitive: 'lopen',
    translation: 'to walk / to run',
    auxiliary: 'zijn',
    pastParticiple: 'gelopen',
    isRegular: false,
    present: { ik: 'loop', jij: 'loopt', u: 'loopt', hijZijHet: 'loopt', wij: 'lopen', jullie: 'lopen', zij: 'lopen' },
    pastSimple: { ik: 'liep', jij: 'liep', u: 'liep', hijZijHet: 'liep', wij: 'liepen', jullie: 'liepen', zij: 'liepen' },
    imperative: 'loop!',
    examples: [
      { dutch: 'Ik loop elke dag een uur.', english: 'I walk for an hour every day.' },
      { dutch: 'Ze is naar de winkel gelopen.', english: 'She walked to the shop.' },
    ],
    notes: 'Uses zijn as auxiliary for movement from A to B.',
  },
  {
    infinitive: 'vliegen',
    translation: 'to fly',
    auxiliary: 'zijn/hebben',
    pastParticiple: 'gevlogen',
    isRegular: false,
    present: { ik: 'vlieg', jij: 'vliegt', u: 'vliegt', hijZijHet: 'vliegt', wij: 'vliegen', jullie: 'vliegen', zij: 'vliegen' },
    pastSimple: { ik: 'vloog', jij: 'vloog', u: 'vloog', hijZijHet: 'vloog', wij: 'vlogen', jullie: 'vlogen', zij: 'vlogen' },
    imperative: 'vlieg!',
    examples: [
      { dutch: 'We vliegen naar Spanje.', english: 'We are flying to Spain.' },
      { dutch: 'De vogel vloog weg.', english: 'The bird flew away.' },
    ],
    notes: 'Uses zijn for movement to a destination; hebben for general activity.',
  },
  {
    infinitive: 'zwemmen',
    translation: 'to swim',
    auxiliary: 'hebben/zijn',
    pastParticiple: 'gezwommen',
    isRegular: false,
    present: { ik: 'zwem', jij: 'zwemt', u: 'zwemt', hijZijHet: 'zwemt', wij: 'zwemmen', jullie: 'zwemmen', zij: 'zwemmen' },
    pastSimple: { ik: 'zwom', jij: 'zwom', u: 'zwom', hijZijHet: 'zwom', wij: 'zwommen', jullie: 'zwommen', zij: 'zwommen' },
    imperative: 'zwem!',
    examples: [
      { dutch: 'Ik zwem graag in de zee.', english: 'I like swimming in the sea.' },
      { dutch: 'Ze heeft een kilometer gezwommen.', english: 'She swam a kilometre.' },
    ],
  },
  {
    infinitive: 'sturen',
    translation: 'to send / to steer',
    auxiliary: 'hebben',
    pastParticiple: 'gestuurd',
    isRegular: true,
    present: { ik: 'stuur', jij: 'stuurt', u: 'stuurt', hijZijHet: 'stuurt', wij: 'sturen', jullie: 'sturen', zij: 'sturen' },
    pastSimple: { ik: 'stuurde', jij: 'stuurde', u: 'stuurde', hijZijHet: 'stuurde', wij: 'stuurden', jullie: 'stuurden', zij: 'stuurden' },
    imperative: 'stuur!',
    examples: [
      { dutch: 'Stuur me het document.', english: 'Send me the document.' },
      { dutch: 'Ik heb een e-mail gestuurd.', english: 'I sent an email.' },
    ],
  },
  {
    infinitive: 'reizen',
    translation: 'to travel',
    auxiliary: 'hebben',
    pastParticiple: 'gereisd',
    isRegular: true,
    present: { ik: 'reis', jij: 'reist', u: 'reist', hijZijHet: 'reist', wij: 'reizen', jullie: 'reizen', zij: 'reizen' },
    pastSimple: { ik: 'reisde', jij: 'reisde', u: 'reisde', hijZijHet: 'reisde', wij: 'reisden', jullie: 'reisden', zij: 'reisden' },
    imperative: 'reis!',
    examples: [
      { dutch: 'Hij reist veel voor zijn werk.', english: 'He travels a lot for work.' },
      { dutch: 'We hebben door Europa gereisd.', english: 'We travelled through Europe.' },
    ],
  },
  {
    infinitive: 'klimmen',
    translation: 'to climb',
    auxiliary: 'zijn/hebben',
    pastParticiple: 'geklommen',
    isRegular: false,
    present: { ik: 'klim', jij: 'klimt', u: 'klimt', hijZijHet: 'klimt', wij: 'klimmen', jullie: 'klimmen', zij: 'klimmen' },
    pastSimple: { ik: 'klom', jij: 'klom', u: 'klom', hijZijHet: 'klom', wij: 'klommen', jullie: 'klommen', zij: 'klommen' },
    imperative: 'klim!',
    examples: [
      { dutch: 'De kinderen klimmen in de boom.', english: 'The children climb the tree.' },
      { dutch: 'Ze zijn de berg opgeklommen.', english: 'They climbed the mountain.' },
    ],
  },

  // ===== COMMUNICATION & THINKING VERBS =====
  {
    infinitive: 'uitleggen',
    translation: 'to explain',
    auxiliary: 'hebben',
    pastParticiple: 'uitgelegd',
    separablePrefix: 'uit',
    isRegular: true,
    present: { ik: 'leg uit', jij: 'legt uit', u: 'legt uit', hijZijHet: 'legt uit', wij: 'leggen uit', jullie: 'leggen uit', zij: 'leggen uit' },
    pastSimple: { ik: 'legde uit', jij: 'legde uit', u: 'legde uit', hijZijHet: 'legde uit', wij: 'legden uit', jullie: 'legden uit', zij: 'legden uit' },
    imperative: 'leg uit!',
    examples: [
      { dutch: 'Kun je dat uitleggen?', english: 'Can you explain that?' },
      { dutch: 'De leraar heeft de regel uitgelegd.', english: 'The teacher explained the rule.' },
    ],
    notes: 'Separable verb: prefix "uit" separates in main clauses.',
  },
  {
    infinitive: 'bedoelen',
    translation: 'to mean / to intend',
    auxiliary: 'hebben',
    pastParticiple: 'bedoeld',
    isRegular: true,
    present: { ik: 'bedoel', jij: 'bedoelt', u: 'bedoelt', hijZijHet: 'bedoelt', wij: 'bedoelen', jullie: 'bedoelen', zij: 'bedoelen' },
    pastSimple: { ik: 'bedoelde', jij: 'bedoelde', u: 'bedoelde', hijZijHet: 'bedoelde', wij: 'bedoelden', jullie: 'bedoelden', zij: 'bedoelden' },
    imperative: 'bedoel!',
    examples: [
      { dutch: 'Wat bedoel je?', english: 'What do you mean?' },
      { dutch: 'Ik bedoel het goed.', english: 'I mean well.' },
    ],
  },
  {
    infinitive: 'beslissen',
    translation: 'to decide',
    auxiliary: 'hebben',
    pastParticiple: 'beslist',
    isRegular: true,
    present: { ik: 'beslis', jij: 'beslist', u: 'beslist', hijZijHet: 'beslist', wij: 'beslissen', jullie: 'beslissen', zij: 'beslissen' },
    pastSimple: { ik: 'besliste', jij: 'besliste', u: 'besliste', hijZijHet: 'besliste', wij: 'beslisten', jullie: 'beslisten', zij: 'beslisten' },
    imperative: 'beslis!',
    examples: [
      { dutch: 'We moeten snel beslissen.', english: 'We need to decide quickly.' },
      { dutch: 'Ze heeft besloten te stoppen.', english: 'She decided to stop.' },
    ],
    notes: 'Also commonly used: besloten (past participle of besluiten, a synonym).',
  },
  {
    infinitive: 'vergeten',
    translation: 'to forget',
    auxiliary: 'hebben',
    pastParticiple: 'vergeten',
    isRegular: false,
    present: { ik: 'vergeet', jij: 'vergeet', u: 'vergeet', hijZijHet: 'vergeet', wij: 'vergeten', jullie: 'vergeten', zij: 'vergeten' },
    pastSimple: { ik: 'vergat', jij: 'vergat', u: 'vergat', hijZijHet: 'vergat', wij: 'vergaten', jullie: 'vergaten', zij: 'vergaten' },
    imperative: 'vergeet!',
    examples: [
      { dutch: 'Vergeet je sleutels niet!', english: 'Don\'t forget your keys!' },
      { dutch: 'Ik ben zijn naam vergeten.', english: 'I forgot his name.' },
    ],
    notes: 'Past participle is the same as the infinitive: vergeten.',
  },
  {
    infinitive: 'herinneren',
    translation: 'to remember / to remind',
    auxiliary: 'hebben',
    pastParticiple: 'herinnerd',
    isRegular: true,
    present: { ik: 'herinner', jij: 'herinnert', u: 'herinnert', hijZijHet: 'herinnert', wij: 'herinneren', jullie: 'herinneren', zij: 'herinneren' },
    pastSimple: { ik: 'herinnerde', jij: 'herinnerde', u: 'herinnerde', hijZijHet: 'herinnerde', wij: 'herinnerden', jullie: 'herinnerden', zij: 'herinnerden' },
    imperative: 'herinner!',
    examples: [
      { dutch: 'Ik herinner me dat moment.', english: 'I remember that moment.' },
      { dutch: 'Kun jij me eraan herinneren?', english: 'Can you remind me of it?' },
    ],
    notes: 'Reflexive: zich herinneren (to remember); herinneren aan (to remind someone of).',
  },
  {
    infinitive: 'overleggen',
    translation: 'to consult / to discuss',
    auxiliary: 'hebben',
    pastParticiple: 'overlegd',
    isRegular: true,
    present: { ik: 'overleg', jij: 'overlegt', u: 'overlegt', hijZijHet: 'overlegt', wij: 'overleggen', jullie: 'overleggen', zij: 'overleggen' },
    pastSimple: { ik: 'overlegde', jij: 'overlegde', u: 'overlegde', hijZijHet: 'overlegde', wij: 'overlegden', jullie: 'overlegden', zij: 'overlegden' },
    imperative: 'overleg!',
    examples: [
      { dutch: 'Ik moet even overleggen met mijn collega.', english: 'I need to consult with my colleague.' },
      { dutch: 'We hebben het gisteren overlegd.', english: 'We discussed it yesterday.' },
    ],
  },

  // ===== EMOTION & STATE VERBS =====
  {
    infinitive: 'hopen',
    translation: 'to hope',
    auxiliary: 'hebben',
    pastParticiple: 'gehoopt',
    isRegular: true,
    present: { ik: 'hoop', jij: 'hoopt', u: 'hoopt', hijZijHet: 'hoopt', wij: 'hopen', jullie: 'hopen', zij: 'hopen' },
    pastSimple: { ik: 'hoopte', jij: 'hoopte', u: 'hoopte', hijZijHet: 'hoopte', wij: 'hoopten', jullie: 'hoopten', zij: 'hoopten' },
    imperative: 'hoop!',
    examples: [
      { dutch: 'Ik hoop dat het goed gaat.', english: 'I hope things go well.' },
      { dutch: 'Ze hoopt op een beter resultaat.', english: 'She is hoping for a better result.' },
    ],
  },
  {
    infinitive: 'vrezen',
    translation: 'to fear / to be afraid',
    auxiliary: 'hebben',
    pastParticiple: 'gevreesd',
    isRegular: true,
    present: { ik: 'vrees', jij: 'vreest', u: 'vreest', hijZijHet: 'vreest', wij: 'vrezen', jullie: 'vrezen', zij: 'vrezen' },
    pastSimple: { ik: 'vreesde', jij: 'vreesde', u: 'vreesde', hijZijHet: 'vreesde', wij: 'vreesden', jullie: 'vreesden', zij: 'vreesden' },
    imperative: 'vrees!',
    examples: [
      { dutch: 'Ik vrees dat het te laat is.', english: 'I fear it is too late.' },
      { dutch: 'Hij vreest het ergste.', english: 'He fears the worst.' },
    ],
    notes: 'More formal than "bang zijn voor".',
  },
  {
    infinitive: 'genieten',
    translation: 'to enjoy',
    auxiliary: 'hebben',
    pastParticiple: 'genoten',
    isRegular: false,
    present: { ik: 'geniet', jij: 'geniet', u: 'geniet', hijZijHet: 'geniet', wij: 'genieten', jullie: 'genieten', zij: 'genieten' },
    pastSimple: { ik: 'genoot', jij: 'genoot', u: 'genoot', hijZijHet: 'genoot', wij: 'genoten', jullie: 'genoten', zij: 'genoten' },
    imperative: 'geniet!',
    examples: [
      { dutch: 'Ik geniet van de zomer.', english: 'I enjoy the summer.' },
      { dutch: 'We hebben enorm genoten.', english: 'We enjoyed it enormously.' },
    ],
    notes: 'Always followed by "van": genieten van iets.',
  },
  {
    infinitive: 'storen',
    translation: 'to disturb / to bother',
    auxiliary: 'hebben',
    pastParticiple: 'gestoord',
    isRegular: true,
    present: { ik: 'stoor', jij: 'stoort', u: 'stoort', hijZijHet: 'stoort', wij: 'storen', jullie: 'storen', zij: 'storen' },
    pastSimple: { ik: 'stoorde', jij: 'stoorde', u: 'stoorde', hijZijHet: 'stoorde', wij: 'stoorden', jullie: 'stoorden', zij: 'stoorden' },
    imperative: 'stoor!',
    examples: [
      { dutch: 'Mag ik je even storen?', english: 'May I disturb you for a moment?' },
      { dutch: 'Het lawaai stoort me.', english: 'The noise bothers me.' },
    ],
    notes: 'Reflexive: zich storen aan (to be bothered by).',
  },
  {
    infinitive: 'schamen',
    translation: 'to be ashamed',
    auxiliary: 'hebben',
    pastParticiple: 'geschaamd',
    isRegular: true,
    isReflexive: true,
    present: { ik: 'schaam me', jij: 'schaamt je', u: 'schaamt u', hijZijHet: 'schaamt zich', wij: 'schamen ons', jullie: 'schamen je', zij: 'schamen zich' },
    pastSimple: { ik: 'schaamde me', jij: 'schaamde je', u: 'schaamde u', hijZijHet: 'schaamde zich', wij: 'schaamden ons', jullie: 'schaamden je', zij: 'schaamden zich' },
    imperative: 'schaam je!',
    examples: [
      { dutch: 'Hij schaamt zich voor zijn gedrag.', english: 'He is ashamed of his behaviour.' },
      { dutch: 'Je hoeft je niet te schamen.', english: 'You don\'t need to be ashamed.' },
    ],
    notes: 'Always reflexive: zich schamen voor.',
  },
  {
    infinitive: 'missen',
    translation: 'to miss',
    auxiliary: 'hebben',
    pastParticiple: 'gemist',
    isRegular: true,
    present: { ik: 'mis', jij: 'mist', u: 'mist', hijZijHet: 'mist', wij: 'missen', jullie: 'missen', zij: 'missen' },
    pastSimple: { ik: 'miste', jij: 'miste', u: 'miste', hijZijHet: 'miste', wij: 'misten', jullie: 'misten', zij: 'misten' },
    imperative: 'mis!',
    examples: [
      { dutch: 'Ik mis mijn familie.', english: 'I miss my family.' },
      { dutch: 'Ze heeft de trein gemist.', english: 'She missed the train.' },
    ],
  },

  // ===== WORK & PROFESSIONAL VERBS =====
  {
    infinitive: 'plannen',
    translation: 'to plan / to schedule',
    auxiliary: 'hebben',
    pastParticiple: 'gepland',
    isRegular: true,
    present: { ik: 'plan', jij: 'plant', u: 'plant', hijZijHet: 'plant', wij: 'plannen', jullie: 'plannen', zij: 'plannen' },
    pastSimple: { ik: 'plande', jij: 'plande', u: 'plande', hijZijHet: 'plande', wij: 'planden', jullie: 'planden', zij: 'planden' },
    imperative: 'plan!',
    examples: [
      { dutch: 'Ik plan de vergadering voor maandag.', english: 'I am scheduling the meeting for Monday.' },
      { dutch: 'Heb je het al gepland?', english: 'Have you planned it already?' },
    ],
  },
  {
    infinitive: 'organiseren',
    translation: 'to organise',
    auxiliary: 'hebben',
    pastParticiple: 'georganiseerd',
    isRegular: true,
    present: { ik: 'organiseer', jij: 'organiseert', u: 'organiseert', hijZijHet: 'organiseert', wij: 'organiseren', jullie: 'organiseren', zij: 'organiseren' },
    pastSimple: { ik: 'organiseerde', jij: 'organiseerde', u: 'organiseerde', hijZijHet: 'organiseerde', wij: 'organiseerden', jullie: 'organiseerden', zij: 'organiseerden' },
    imperative: 'organiseer!',
    examples: [
      { dutch: 'Wie organiseert het evenement?', english: 'Who is organising the event?' },
      { dutch: 'We hebben alles goed georganiseerd.', english: 'We organised everything well.' },
    ],
  },
  {
    infinitive: 'controleren',
    translation: 'to check / to control',
    auxiliary: 'hebben',
    pastParticiple: 'gecontroleerd',
    isRegular: true,
    present: { ik: 'controleer', jij: 'controleert', u: 'controleert', hijZijHet: 'controleert', wij: 'controleren', jullie: 'controleren', zij: 'controleren' },
    pastSimple: { ik: 'controleerde', jij: 'controleerde', u: 'controleerde', hijZijHet: 'controleerde', wij: 'controleerden', jullie: 'controleerden', zij: 'controleerden' },
    imperative: 'controleer!',
    examples: [
      { dutch: 'Controleer je e-mails regelmatig.', english: 'Check your emails regularly.' },
      { dutch: 'De manager heeft het rapport gecontroleerd.', english: 'The manager checked the report.' },
    ],
  },
  {
    infinitive: 'presenteren',
    translation: 'to present',
    auxiliary: 'hebben',
    pastParticiple: 'gepresenteerd',
    isRegular: true,
    present: { ik: 'presenteer', jij: 'presenteert', u: 'presenteert', hijZijHet: 'presenteert', wij: 'presenteren', jullie: 'presenteren', zij: 'presenteren' },
    pastSimple: { ik: 'presenteerde', jij: 'presenteerde', u: 'presenteerde', hijZijHet: 'presenteerde', wij: 'presenteerden', jullie: 'presenteerden', zij: 'presenteerden' },
    imperative: 'presenteer!',
    examples: [
      { dutch: 'Ze presenteert de resultaten aan het team.', english: 'She presents the results to the team.' },
      { dutch: 'Hij heeft het project gepresenteerd.', english: 'He presented the project.' },
    ],
  },
  {
    infinitive: 'oplossen',
    translation: 'to solve / to resolve',
    auxiliary: 'hebben',
    pastParticiple: 'opgelost',
    separablePrefix: 'op',
    isRegular: true,
    present: { ik: 'los op', jij: 'lost op', u: 'lost op', hijZijHet: 'lost op', wij: 'lossen op', jullie: 'lossen op', zij: 'lossen op' },
    pastSimple: { ik: 'loste op', jij: 'loste op', u: 'loste op', hijZijHet: 'loste op', wij: 'losten op', jullie: 'losten op', zij: 'losten op' },
    imperative: 'los op!',
    examples: [
      { dutch: 'We moeten dit probleem oplossen.', english: 'We need to solve this problem.' },
      { dutch: 'Heb jij het al opgelost?', english: 'Have you solved it already?' },
    ],
    notes: 'Separable verb: "op" separates in main clauses.',
  },
  {
    infinitive: 'verdienen',
    translation: 'to earn / to deserve',
    auxiliary: 'hebben',
    pastParticiple: 'verdiend',
    isRegular: true,
    present: { ik: 'verdien', jij: 'verdient', u: 'verdient', hijZijHet: 'verdient', wij: 'verdienen', jullie: 'verdienen', zij: 'verdienen' },
    pastSimple: { ik: 'verdiende', jij: 'verdiende', u: 'verdiende', hijZijHet: 'verdiende', wij: 'verdienden', jullie: 'verdienden', zij: 'verdienden' },
    imperative: 'verdien!',
    examples: [
      { dutch: 'Hij verdient een goed salaris.', english: 'He earns a good salary.' },
      { dutch: 'Je verdient een pauze.', english: 'You deserve a break.' },
    ],
  },

  // ===== DAILY LIFE VERBS =====
  {
    infinitive: 'koken',
    translation: 'to cook',
    auxiliary: 'hebben',
    pastParticiple: 'gekookt',
    isRegular: true,
    present: { ik: 'kook', jij: 'kookt', u: 'kookt', hijZijHet: 'kookt', wij: 'koken', jullie: 'koken', zij: 'koken' },
    pastSimple: { ik: 'kookte', jij: 'kookte', u: 'kookte', hijZijHet: 'kookte', wij: 'kookten', jullie: 'kookten', zij: 'kookten' },
    imperative: 'kook!',
    examples: [
      { dutch: 'Vanavond kook ik voor iedereen.', english: 'Tonight I am cooking for everyone.' },
      { dutch: 'Ze heeft een heerlijk gerecht gekookt.', english: 'She cooked a delicious dish.' },
    ],
  },
  {
    infinitive: 'wassen',
    translation: 'to wash',
    auxiliary: 'hebben',
    pastParticiple: 'gewassen',
    isRegular: false,
    present: { ik: 'was', jij: 'wast', u: 'wast', hijZijHet: 'wast', wij: 'wassen', jullie: 'wassen', zij: 'wassen' },
    pastSimple: { ik: 'waste', jij: 'waste', u: 'waste', hijZijHet: 'waste', wij: 'wasten', jullie: 'wasten', zij: 'wasten' },
    imperative: 'was!',
    examples: [
      { dutch: 'Was je handen voor het eten.', english: 'Wash your hands before eating.' },
      { dutch: 'Ik heb de kleren gewassen.', english: 'I washed the clothes.' },
    ],
  },
  {
    infinitive: 'schoonmaken',
    translation: 'to clean',
    auxiliary: 'hebben',
    pastParticiple: 'schoongemaakt',
    separablePrefix: 'schoon',
    isRegular: true,
    present: { ik: 'maak schoon', jij: 'maakt schoon', u: 'maakt schoon', hijZijHet: 'maakt schoon', wij: 'maken schoon', jullie: 'maken schoon', zij: 'maken schoon' },
    pastSimple: { ik: 'maakte schoon', jij: 'maakte schoon', u: 'maakte schoon', hijZijHet: 'maakte schoon', wij: 'maakten schoon', jullie: 'maakten schoon', zij: 'maakten schoon' },
    imperative: 'maak schoon!',
    examples: [
      { dutch: 'Ik maak zaterdag het huis schoon.', english: 'I clean the house on Saturday.' },
      { dutch: 'Heb jij de keuken schoongemaakt?', english: 'Did you clean the kitchen?' },
    ],
  },
  {
    infinitive: 'slapen',
    translation: 'to sleep',
    auxiliary: 'hebben',
    pastParticiple: 'geslapen',
    isRegular: false,
    present: { ik: 'slaap', jij: 'slaapt', u: 'slaapt', hijZijHet: 'slaapt', wij: 'slapen', jullie: 'slapen', zij: 'slapen' },
    pastSimple: { ik: 'sliep', jij: 'sliep', u: 'sliep', hijZijHet: 'sliep', wij: 'sliepen', jullie: 'sliepen', zij: 'sliepen' },
    imperative: 'slaap!',
    examples: [
      { dutch: 'Ik slaap elke nacht acht uur.', english: 'I sleep eight hours every night.' },
      { dutch: 'De baby heeft goed geslapen.', english: 'The baby slept well.' },
    ],
  },
  {
    infinitive: 'eten',
    translation: 'to eat',
    auxiliary: 'hebben',
    pastParticiple: 'gegeten',
    isRegular: false,
    present: { ik: 'eet', jij: 'eet', u: 'eet', hijZijHet: 'eet', wij: 'eten', jullie: 'eten', zij: 'eten' },
    pastSimple: { ik: 'at', jij: 'at', u: 'at', hijZijHet: 'at', wij: 'aten', jullie: 'aten', zij: 'aten' },
    imperative: 'eet!',
    examples: [
      { dutch: 'Ik eet elke ochtend ontbijt.', english: 'I eat breakfast every morning.' },
      { dutch: 'We hebben heerlijk gegeten.', english: 'We ate wonderfully.' },
    ],
  },
  {
    infinitive: 'brengen',
    translation: 'to bring',
    auxiliary: 'hebben',
    pastParticiple: 'gebracht',
    isRegular: false,
    present: { ik: 'breng', jij: 'brengt', u: 'brengt', hijZijHet: 'brengt', wij: 'brengen', jullie: 'brengen', zij: 'brengen' },
    pastSimple: { ik: 'bracht', jij: 'bracht', u: 'bracht', hijZijHet: 'bracht', wij: 'brachten', jullie: 'brachten', zij: 'brachten' },
    imperative: 'breng!',
    examples: [
      { dutch: 'Kun je de kinderen naar school brengen?', english: 'Can you bring the children to school?' },
      { dutch: 'Hij heeft een cadeau gebracht.', english: 'He brought a gift.' },
    ],
  },
  {
    infinitive: 'halen',
    translation: 'to fetch / to get / to pass (exam)',
    auxiliary: 'hebben',
    pastParticiple: 'gehaald',
    isRegular: true,
    present: { ik: 'haal', jij: 'haalt', u: 'haalt', hijZijHet: 'haalt', wij: 'halen', jullie: 'halen', zij: 'halen' },
    pastSimple: { ik: 'haalde', jij: 'haalde', u: 'haalde', hijZijHet: 'haalde', wij: 'haalden', jullie: 'haalden', zij: 'haalden' },
    imperative: 'haal!',
    examples: [
      { dutch: 'Kun jij brood halen?', english: 'Can you fetch some bread?' },
      { dutch: 'Ze heeft haar rijbewijs gehaald.', english: 'She passed her driving test.' },
    ],
  },
  {
    infinitive: 'zetten',
    translation: 'to put / to place (upright)',
    auxiliary: 'hebben',
    pastParticiple: 'gezet',
    isRegular: true,
    present: { ik: 'zet', jij: 'zet', u: 'zet', hijZijHet: 'zet', wij: 'zetten', jullie: 'zetten', zij: 'zetten' },
    pastSimple: { ik: 'zette', jij: 'zette', u: 'zette', hijZijHet: 'zette', wij: 'zetten', jullie: 'zetten', zij: 'zetten' },
    imperative: 'zet!',
    examples: [
      { dutch: 'Zet de melk in de koelkast.', english: 'Put the milk in the fridge.' },
      { dutch: 'Ik heb de stoel in de hoek gezet.', english: 'I put the chair in the corner.' },
    ],
    notes: 'Use "zetten" for upright objects; "leggen" for horizontal objects.',
  },
  {
    infinitive: 'leggen',
    translation: 'to lay / to put (flat)',
    auxiliary: 'hebben',
    pastParticiple: 'gelegd',
    isRegular: true,
    present: { ik: 'leg', jij: 'legt', u: 'legt', hijZijHet: 'legt', wij: 'leggen', jullie: 'leggen', zij: 'leggen' },
    pastSimple: { ik: 'legde', jij: 'legde', u: 'legde', hijZijHet: 'legde', wij: 'legden', jullie: 'legden', zij: 'legden' },
    imperative: 'leg!',
    examples: [
      { dutch: 'Leg het boek op tafel.', english: 'Put the book on the table.' },
      { dutch: 'Ze heeft het kind in bed gelegd.', english: 'She put the child to bed.' },
    ],
    notes: 'Use "leggen" for flat/horizontal placement; "zetten" for upright placement.',
  },

  // ===== IRREGULAR VERBS (ADVANCED) =====
  {
    infinitive: 'blijven',
    translation: 'to stay / to remain',
    auxiliary: 'zijn',
    pastParticiple: 'gebleven',
    isRegular: false,
    present: { ik: 'blijf', jij: 'blijft', u: 'blijft', hijZijHet: 'blijft', wij: 'blijven', jullie: 'blijven', zij: 'blijven' },
    pastSimple: { ik: 'bleef', jij: 'bleef', u: 'bleef', hijZijHet: 'bleef', wij: 'bleven', jullie: 'bleven', zij: 'bleven' },
    imperative: 'blijf!',
    examples: [
      { dutch: 'Ik blijf thuis vandaag.', english: 'I am staying home today.' },
      { dutch: 'Ze is lang gebleven.', english: 'She stayed for a long time.' },
    ],
    notes: 'Uses zijn as auxiliary. Also used as aspectual verb: blijven + infinitive (to keep doing).',
  },
  {
    infinitive: 'worden',
    translation: 'to become / to get',
    auxiliary: 'zijn',
    pastParticiple: 'geworden',
    isRegular: false,
    present: { ik: 'word', jij: 'wordt', u: 'wordt', hijZijHet: 'wordt', wij: 'worden', jullie: 'worden', zij: 'worden' },
    pastSimple: { ik: 'werd', jij: 'werd', u: 'werd', hijZijHet: 'werd', wij: 'werden', jullie: 'werden', zij: 'werden' },
    imperative: 'word!',
    examples: [
      { dutch: 'Ze wordt binnenkort arts.', english: 'She will soon become a doctor.' },
      { dutch: 'Het werd donker.', english: 'It got dark.' },
    ],
    notes: 'Also the passive auxiliary: "Het rapport wordt geschreven." (The report is being written.)',
  },
  {
    infinitive: 'vallen',
    translation: 'to fall',
    auxiliary: 'zijn',
    pastParticiple: 'gevallen',
    isRegular: false,
    present: { ik: 'val', jij: 'valt', u: 'valt', hijZijHet: 'valt', wij: 'vallen', jullie: 'vallen', zij: 'vallen' },
    pastSimple: { ik: 'viel', jij: 'viel', u: 'viel', hijZijHet: 'viel', wij: 'vielen', jullie: 'vielen', zij: 'vielen' },
    imperative: 'val!',
    examples: [
      { dutch: 'Hij is van de fiets gevallen.', english: 'He fell off the bike.' },
      { dutch: 'De bladeren vallen in de herfst.', english: 'The leaves fall in autumn.' },
    ],
    notes: 'Uses zijn as auxiliary (change of state/position).',
  },
  {
    infinitive: 'groeien',
    translation: 'to grow',
    auxiliary: 'zijn',
    pastParticiple: 'gegroeid',
    isRegular: true,
    present: { ik: 'groei', jij: 'groeit', u: 'groeit', hijZijHet: 'groeit', wij: 'groeien', jullie: 'groeien', zij: 'groeien' },
    pastSimple: { ik: 'groeide', jij: 'groeide', u: 'groeide', hijZijHet: 'groeide', wij: 'groeiden', jullie: 'groeiden', zij: 'groeiden' },
    imperative: 'groei!',
    examples: [
      { dutch: 'De kinderen groeien snel.', english: 'The children grow quickly.' },
      { dutch: 'Het bedrijf is sterk gegroeid.', english: 'The company has grown strongly.' },
    ],
    notes: 'Uses zijn as auxiliary (change of state).',
  },
  {
    infinitive: 'sterven',
    translation: 'to die',
    auxiliary: 'zijn',
    pastParticiple: 'gestorven',
    isRegular: false,
    present: { ik: 'sterf', jij: 'sterft', u: 'sterft', hijZijHet: 'sterft', wij: 'sterven', jullie: 'sterven', zij: 'sterven' },
    pastSimple: { ik: 'stierf', jij: 'stierf', u: 'stierf', hijZijHet: 'stierf', wij: 'stierven', jullie: 'stierven', zij: 'stierven' },
    imperative: 'sterf!',
    examples: [
      { dutch: 'Hij is op hoge leeftijd gestorven.', english: 'He died at an old age.' },
    ],
    notes: 'Uses zijn as auxiliary (change of state). Formal; everyday alternative: overlijden.',
  },
  {
    infinitive: 'kiezen',
    translation: 'to choose',
    auxiliary: 'hebben',
    pastParticiple: 'gekozen',
    isRegular: false,
    present: { ik: 'kies', jij: 'kiest', u: 'kiest', hijZijHet: 'kiest', wij: 'kiezen', jullie: 'kiezen', zij: 'kiezen' },
    pastSimple: { ik: 'koos', jij: 'koos', u: 'koos', hijZijHet: 'koos', wij: 'kozen', jullie: 'kozen', zij: 'kozen' },
    imperative: 'kies!',
    examples: [
      { dutch: 'Kies maar wat je wilt.', english: 'Just choose what you want.' },
      { dutch: 'Ze heeft voor de baan gekozen.', english: 'She chose the job.' },
    ],
  },
  {
    infinitive: 'bieden',
    translation: 'to offer / to provide',
    auxiliary: 'hebben',
    pastParticiple: 'geboden',
    isRegular: false,
    present: { ik: 'bied', jij: 'biedt', u: 'biedt', hijZijHet: 'biedt', wij: 'bieden', jullie: 'bieden', zij: 'bieden' },
    pastSimple: { ik: 'bood', jij: 'bood', u: 'bood', hijZijHet: 'bood', wij: 'boden', jullie: 'boden', zij: 'boden' },
    imperative: 'bied!',
    examples: [
      { dutch: 'Het bedrijf biedt goede arbeidsvoorwaarden.', english: 'The company offers good employment conditions.' },
      { dutch: 'Hij heeft hulp geboden.', english: 'He offered help.' },
    ],
  },
  {
    infinitive: 'trekken',
    translation: 'to pull / to draw',
    auxiliary: 'hebben',
    pastParticiple: 'getrokken',
    isRegular: false,
    present: { ik: 'trek', jij: 'trekt', u: 'trekt', hijZijHet: 'trekt', wij: 'trekken', jullie: 'trekken', zij: 'trekken' },
    pastSimple: { ik: 'trok', jij: 'trok', u: 'trok', hijZijHet: 'trok', wij: 'trokken', jullie: 'trokken', zij: 'trokken' },
    imperative: 'trek!',
    examples: [
      { dutch: 'Trek de deur dicht.', english: 'Pull the door shut.' },
      { dutch: 'Ze heeft veel toeristen getrokken.', english: 'It attracted many tourists.' },
    ],
  },
  {
    infinitive: 'dragen',
    translation: 'to carry / to wear',
    auxiliary: 'hebben',
    pastParticiple: 'gedragen',
    isRegular: false,
    present: { ik: 'draag', jij: 'draagt', u: 'draagt', hijZijHet: 'draagt', wij: 'dragen', jullie: 'dragen', zij: 'dragen' },
    pastSimple: { ik: 'droeg', jij: 'droeg', u: 'droeg', hijZijHet: 'droeg', wij: 'droegen', jullie: 'droegen', zij: 'droegen' },
    imperative: 'draag!',
    examples: [
      { dutch: 'Ze draagt een mooie jurk.', english: 'She is wearing a beautiful dress.' },
      { dutch: 'Kun jij de tassen dragen?', english: 'Can you carry the bags?' },
    ],
  },
  {
    infinitive: 'slagen',
    translation: 'to succeed / to pass (exam)',
    auxiliary: 'zijn',
    pastParticiple: 'geslaagd',
    isRegular: true,
    present: { ik: 'slaag', jij: 'slaagt', u: 'slaagt', hijZijHet: 'slaagt', wij: 'slagen', jullie: 'slagen', zij: 'slagen' },
    pastSimple: { ik: 'slaagde', jij: 'slaagde', u: 'slaagde', hijZijHet: 'slaagde', wij: 'slaagden', jullie: 'slaagden', zij: 'slaagden' },
    imperative: 'slaag!',
    examples: [
      { dutch: 'Ze is geslaagd voor haar examen.', english: 'She passed her exam.' },
      { dutch: 'Ik hoop dat je slaagt.', english: 'I hope you succeed.' },
    ],
    notes: 'Uses zijn as auxiliary. "Slagen voor" = to pass; "slagen erin" = to manage/succeed in.',
  },
  {
    infinitive: 'mislukken',
    translation: 'to fail / to go wrong',
    auxiliary: 'zijn',
    pastParticiple: 'mislukt',
    isRegular: true,
    present: { ik: 'mislukt', jij: 'mislukt', u: 'mislukt', hijZijHet: 'mislukt', wij: 'mislukken', jullie: 'mislukken', zij: 'mislukken' },
    pastSimple: { ik: 'mislukte', jij: 'mislukte', u: 'mislukte', hijZijHet: 'mislukte', wij: 'mislukten', jullie: 'mislukten', zij: 'mislukten' },
    imperative: 'mislukt!',
    examples: [
      { dutch: 'Het experiment is mislukt.', english: 'The experiment failed.' },
      { dutch: 'Het plan mislukte volledig.', english: 'The plan failed completely.' },
    ],
    notes: 'Uses zijn as auxiliary. Impersonal verb — mostly used in third person.',
  },

  // ===== SEPARABLE VERBS (ADDITIONAL) =====
  {
    infinitive: 'afmaken',
    translation: 'to finish / to complete',
    auxiliary: 'hebben',
    pastParticiple: 'afgemaakt',
    separablePrefix: 'af',
    isRegular: true,
    present: { ik: 'maak af', jij: 'maakt af', u: 'maakt af', hijZijHet: 'maakt af', wij: 'maken af', jullie: 'maken af', zij: 'maken af' },
    pastSimple: { ik: 'maakte af', jij: 'maakte af', u: 'maakte af', hijZijHet: 'maakte af', wij: 'maakten af', jullie: 'maakten af', zij: 'maakten af' },
    imperative: 'maak af!',
    examples: [
      { dutch: 'Maak je huiswerk af!', english: 'Finish your homework!' },
      { dutch: 'Ik heb het rapport afgemaakt.', english: 'I finished the report.' },
    ],
    notes: 'Separable: "af" goes to end in main clause.',
  },
  {
    infinitive: 'aanzetten',
    translation: 'to turn on / to switch on',
    auxiliary: 'hebben',
    pastParticiple: 'aangezet',
    separablePrefix: 'aan',
    isRegular: true,
    present: { ik: 'zet aan', jij: 'zet aan', u: 'zet aan', hijZijHet: 'zet aan', wij: 'zetten aan', jullie: 'zetten aan', zij: 'zetten aan' },
    pastSimple: { ik: 'zette aan', jij: 'zette aan', u: 'zette aan', hijZijHet: 'zette aan', wij: 'zetten aan', jullie: 'zetten aan', zij: 'zetten aan' },
    imperative: 'zet aan!',
    examples: [
      { dutch: 'Zet de tv aan.', english: 'Turn on the TV.' },
      { dutch: 'Wie heeft de verwarming aangezet?', english: 'Who turned on the heating?' },
    ],
  },
  {
    infinitive: 'uitzetten',
    translation: 'to turn off / to switch off',
    auxiliary: 'hebben',
    pastParticiple: 'uitgezet',
    separablePrefix: 'uit',
    isRegular: true,
    present: { ik: 'zet uit', jij: 'zet uit', u: 'zet uit', hijZijHet: 'zet uit', wij: 'zetten uit', jullie: 'zetten uit', zij: 'zetten uit' },
    pastSimple: { ik: 'zette uit', jij: 'zette uit', u: 'zette uit', hijZijHet: 'zette uit', wij: 'zetten uit', jullie: 'zetten uit', zij: 'zetten uit' },
    imperative: 'zet uit!',
    examples: [
      { dutch: 'Zet het licht uit.', english: 'Turn off the light.' },
      { dutch: 'Heb jij de computer uitgezet?', english: 'Did you turn off the computer?' },
    ],
  },
  {
    infinitive: 'opstaan',
    translation: 'to get up / to stand up',
    auxiliary: 'zijn',
    pastParticiple: 'opgestaan',
    separablePrefix: 'op',
    isRegular: false,
    present: { ik: 'sta op', jij: 'staat op', u: 'staat op', hijZijHet: 'staat op', wij: 'staan op', jullie: 'staan op', zij: 'staan op' },
    pastSimple: { ik: 'stond op', jij: 'stond op', u: 'stond op', hijZijHet: 'stond op', wij: 'stonden op', jullie: 'stonden op', zij: 'stonden op' },
    imperative: 'sta op!',
    examples: [
      { dutch: 'Ik sta elke dag om 7 uur op.', english: 'I get up at 7 every day.' },
      { dutch: 'Ze is vroeg opgestaan.', english: 'She got up early.' },
    ],
    notes: 'Uses zijn as auxiliary (change of position/state).',
  },
  {
    infinitive: 'aangeven',
    translation: 'to indicate / to report / to hand over',
    auxiliary: 'hebben',
    pastParticiple: 'aangegeven',
    separablePrefix: 'aan',
    isRegular: false,
    present: { ik: 'geef aan', jij: 'geeft aan', u: 'geeft aan', hijZijHet: 'geeft aan', wij: 'geven aan', jullie: 'geven aan', zij: 'geven aan' },
    pastSimple: { ik: 'gaf aan', jij: 'gaf aan', u: 'gaf aan', hijZijHet: 'gaf aan', wij: 'gaven aan', jullie: 'gaven aan', zij: 'gaven aan' },
    imperative: 'geef aan!',
    examples: [
      { dutch: 'Geef aan als je problemen hebt.', english: 'Let us know if you have problems.' },
      { dutch: 'Ze heeft aangifte aangegeven bij de politie.', english: 'She reported it to the police.' },
    ],
  },
  {
    infinitive: 'opzoeken',
    translation: 'to look up / to look for',
    auxiliary: 'hebben',
    pastParticiple: 'opgezocht',
    separablePrefix: 'op',
    isRegular: false,
    present: { ik: 'zoek op', jij: 'zoekt op', u: 'zoekt op', hijZijHet: 'zoekt op', wij: 'zoeken op', jullie: 'zoeken op', zij: 'zoeken op' },
    pastSimple: { ik: 'zocht op', jij: 'zocht op', u: 'zocht op', hijZijHet: 'zocht op', wij: 'zochten op', jullie: 'zochten op', zij: 'zochten op' },
    imperative: 'zoek op!',
    examples: [
      { dutch: 'Zoek het woord op in het woordenboek.', english: 'Look up the word in the dictionary.' },
      { dutch: 'Ik heb het opgezocht op internet.', english: 'I looked it up on the internet.' },
    ],
  },

  // ===== SOCIAL & INTERACTION VERBS =====
  {
    infinitive: 'ontmoeten',
    translation: 'to meet',
    auxiliary: 'hebben',
    pastParticiple: 'ontmoet',
    isRegular: true,
    present: { ik: 'ontmoet', jij: 'ontmoet', u: 'ontmoet', hijZijHet: 'ontmoet', wij: 'ontmoeten', jullie: 'ontmoeten', zij: 'ontmoeten' },
    pastSimple: { ik: 'ontmoette', jij: 'ontmoette', u: 'ontmoette', hijZijHet: 'ontmoette', wij: 'ontmoetten', jullie: 'ontmoetten', zij: 'ontmoetten' },
    imperative: 'ontmoet!',
    examples: [
      { dutch: 'Wanneer heb je hem ontmoet?', english: 'When did you meet him?' },
      { dutch: 'We ontmoeten elkaar bij de ingang.', english: 'We meet at the entrance.' },
    ],
  },
  {
    infinitive: 'feliciteren',
    translation: 'to congratulate',
    auxiliary: 'hebben',
    pastParticiple: 'gefeliciteerd',
    isRegular: true,
    present: { ik: 'feliciteer', jij: 'feliciteert', u: 'feliciteert', hijZijHet: 'feliciteert', wij: 'feliciteren', jullie: 'feliciteren', zij: 'feliciteren' },
    pastSimple: { ik: 'feliciteerde', jij: 'feliciteerde', u: 'feliciteerde', hijZijHet: 'feliciteerde', wij: 'feliciteerden', jullie: 'feliciteerden', zij: 'feliciteerden' },
    imperative: 'feliciteer!',
    examples: [
      { dutch: 'Ik feliciteer je met je verjaardag!', english: 'I congratulate you on your birthday!' },
      { dutch: 'Ze heeft hem gefeliciteerd met zijn promotie.', english: 'She congratulated him on his promotion.' },
    ],
  },
  {
    infinitive: 'bedanken',
    translation: 'to thank',
    auxiliary: 'hebben',
    pastParticiple: 'bedankt',
    isRegular: true,
    present: { ik: 'bedank', jij: 'bedankt', u: 'bedankt', hijZijHet: 'bedankt', wij: 'bedanken', jullie: 'bedanken', zij: 'bedanken' },
    pastSimple: { ik: 'bedankte', jij: 'bedankte', u: 'bedankte', hijZijHet: 'bedankte', wij: 'bedankten', jullie: 'bedankten', zij: 'bedankten' },
    imperative: 'bedank!',
    examples: [
      { dutch: 'Ik wil je bedanken voor je hulp.', english: 'I want to thank you for your help.' },
      { dutch: 'Ze heeft iedereen bedankt.', english: 'She thanked everyone.' },
    ],
  },
  {
    infinitive: 'excuseren',
    translation: 'to excuse / to apologise',
    auxiliary: 'hebben',
    pastParticiple: 'geëxcuseerd',
    isRegular: true,
    present: { ik: 'excuseer', jij: 'excuseert', u: 'excuseert', hijZijHet: 'excuseert', wij: 'excuseren', jullie: 'excuseren', zij: 'excuseren' },
    pastSimple: { ik: 'excuseerde', jij: 'excuseerde', u: 'excuseerde', hijZijHet: 'excuseerde', wij: 'excuseerden', jullie: 'excuseerden', zij: 'excuseerden' },
    imperative: 'excuseer!',
    examples: [
      { dutch: 'Excuseer me, maar mag ik even langs?', english: 'Excuse me, may I get past?' },
      { dutch: 'Hij heeft zich geëxcuseerd voor zijn gedrag.', english: 'He apologised for his behaviour.' },
    ],
    notes: 'Reflexive: zich excuseren (to apologise).',
  },
  {
    infinitive: 'uitnodigen',
    translation: 'to invite',
    auxiliary: 'hebben',
    pastParticiple: 'uitgenodigd',
    separablePrefix: 'uit',
    isRegular: true,
    present: { ik: 'nodig uit', jij: 'nodigt uit', u: 'nodigt uit', hijZijHet: 'nodigt uit', wij: 'nodigen uit', jullie: 'nodigen uit', zij: 'nodigen uit' },
    pastSimple: { ik: 'nodigde uit', jij: 'nodigde uit', u: 'nodigde uit', hijZijHet: 'nodigde uit', wij: 'nodigden uit', jullie: 'nodigden uit', zij: 'nodigden uit' },
    imperative: 'nodig uit!',
    examples: [
      { dutch: 'Ik nodig je uit voor mijn feestje.', english: 'I invite you to my party.' },
      { dutch: 'Ze zijn uitgenodigd voor de bruiloft.', english: 'They were invited to the wedding.' },
    ],
  },

  // ===== NATURE & WEATHER VERBS =====
  {
    infinitive: 'regenen',
    translation: 'to rain',
    auxiliary: 'hebben',
    pastParticiple: 'geregend',
    isRegular: true,
    present: { ik: '-', jij: '-', u: '-', hijZijHet: 'regent', wij: '-', jullie: '-', zij: '-' },
    pastSimple: { ik: '-', jij: '-', u: '-', hijZijHet: 'regende', wij: '-', jullie: '-', zij: '-' },
    imperative: '-',
    examples: [
      { dutch: 'Het regent buiten.', english: 'It is raining outside.' },
      { dutch: 'Gisteren heeft het de hele dag geregend.', english: 'Yesterday it rained all day.' },
    ],
    notes: 'Impersonal verb — only used with "het" as subject.',
  },
  {
    infinitive: 'sneeuwen',
    translation: 'to snow',
    auxiliary: 'hebben',
    pastParticiple: 'gesneeuwd',
    isRegular: true,
    present: { ik: '-', jij: '-', u: '-', hijZijHet: 'sneeuwt', wij: '-', jullie: '-', zij: '-' },
    pastSimple: { ik: '-', jij: '-', u: '-', hijZijHet: 'sneeuwde', wij: '-', jullie: '-', zij: '-' },
    imperative: '-',
    examples: [
      { dutch: 'Het sneeuwt vandaag.', english: 'It is snowing today.' },
      { dutch: 'Vorige week heeft het gesneeuwd.', english: 'Last week it snowed.' },
    ],
    notes: 'Impersonal verb — only used with "het" as subject.',
  },
  {
    infinitive: 'waaien',
    translation: 'to blow (wind)',
    auxiliary: 'hebben',
    pastParticiple: 'gewaaid',
    isRegular: true,
    present: { ik: 'waai', jij: 'waait', u: 'waait', hijZijHet: 'waait', wij: 'waaien', jullie: 'waaien', zij: 'waaien' },
    pastSimple: { ik: 'waaide', jij: 'waaide', u: 'waaide', hijZijHet: 'waaide', wij: 'waaiden', jullie: 'waaiden', zij: 'waaiden' },
    imperative: 'waai!',
    examples: [
      { dutch: 'Het waait hard vandaag.', english: 'It is very windy today.' },
      { dutch: 'Het heeft de hele nacht gewaaid.', english: 'It was windy all night.' },
    ],
  },

  // ===== ACADEMIC & LEARNING VERBS =====
  {
    infinitive: 'oefenen',
    translation: 'to practise / to exercise',
    auxiliary: 'hebben',
    pastParticiple: 'geoefend',
    isRegular: true,
    present: { ik: 'oefen', jij: 'oefent', u: 'oefent', hijZijHet: 'oefent', wij: 'oefenen', jullie: 'oefenen', zij: 'oefenen' },
    pastSimple: { ik: 'oefende', jij: 'oefende', u: 'oefende', hijZijHet: 'oefende', wij: 'oefenden', jullie: 'oefenden', zij: 'oefenden' },
    imperative: 'oefen!',
    examples: [
      { dutch: 'Je moet elke dag oefenen.', english: 'You need to practise every day.' },
      { dutch: 'We hebben de uitspraak geoefend.', english: 'We practised the pronunciation.' },
    ],
  },
  {
    infinitive: 'begrijpen',
    translation: 'to understand',
    auxiliary: 'hebben',
    pastParticiple: 'begrepen',
    isRegular: false,
    present: { ik: 'begrijp', jij: 'begrijpt', u: 'begrijpt', hijZijHet: 'begrijpt', wij: 'begrijpen', jullie: 'begrijpen', zij: 'begrijpen' },
    pastSimple: { ik: 'begreep', jij: 'begreep', u: 'begreep', hijZijHet: 'begreep', wij: 'begrepen', jullie: 'begrepen', zij: 'begrepen' },
    imperative: 'begrijp!',
    examples: [
      { dutch: 'Begrijp je de vraag?', english: 'Do you understand the question?' },
      { dutch: 'Ik heb het eindelijk begrepen.', english: 'I finally understood it.' },
    ],
  },
  {
    infinitive: 'uitspreken',
    translation: 'to pronounce / to express',
    auxiliary: 'hebben',
    pastParticiple: 'uitgesproken',
    separablePrefix: 'uit',
    isRegular: false,
    present: { ik: 'spreek uit', jij: 'spreekt uit', u: 'spreekt uit', hijZijHet: 'spreekt uit', wij: 'spreken uit', jullie: 'spreken uit', zij: 'spreken uit' },
    pastSimple: { ik: 'sprak uit', jij: 'sprak uit', u: 'sprak uit', hijZijHet: 'sprak uit', wij: 'spraken uit', jullie: 'spraken uit', zij: 'spraken uit' },
    imperative: 'spreek uit!',
    examples: [
      { dutch: 'Hoe spreek je dit woord uit?', english: 'How do you pronounce this word?' },
      { dutch: 'Ze heeft haar mening uitgesproken.', english: 'She expressed her opinion.' },
    ],
  },
  {
    infinitive: 'vertalen',
    translation: 'to translate',
    auxiliary: 'hebben',
    pastParticiple: 'vertaald',
    isRegular: true,
    present: { ik: 'vertaal', jij: 'vertaalt', u: 'vertaalt', hijZijHet: 'vertaalt', wij: 'vertalen', jullie: 'vertalen', zij: 'vertalen' },
    pastSimple: { ik: 'vertaalde', jij: 'vertaalde', u: 'vertaalde', hijZijHet: 'vertaalde', wij: 'vertaalden', jullie: 'vertaalden', zij: 'vertaalden' },
    imperative: 'vertaal!',
    examples: [
      { dutch: 'Kun je dit voor me vertalen?', english: 'Can you translate this for me?' },
      { dutch: 'Het boek is vertaald in twintig talen.', english: 'The book has been translated into twenty languages.' },
    ],
  },
];

// ---------------------------------------------------------------------------
// Build lookup index: maps every known form to its VerbConjugation entry
// ---------------------------------------------------------------------------

const formIndex = new Map<string, VerbConjugation>();

function normalize(text: string): string {
  return text.toLowerCase().trim();
}

function addForm(form: string, verb: VerbConjugation) {
  // Handle forms like "hebt / heeft" → add both "hebt" and "heeft"
  for (const part of form.split('/')) {
    const key = normalize(part);
    if (key && key !== '-') {
      formIndex.set(key, verb);
    }
  }
}

for (const verb of verbs) {
  // Infinitive
  addForm(verb.infinitive, verb);

  // Past participle
  addForm(verb.pastParticiple, verb);

  // All present-tense forms
  for (const form of Object.values(verb.present)) {
    // Handle separated forms like "kom aan" — index both the full form and the base verb
    addForm(form, verb);
    if (form.includes(' ')) {
      addForm(form.split(' ')[0], verb);
    }
  }

  // All past-simple forms
  for (const form of Object.values(verb.pastSimple)) {
    addForm(form, verb);
    if (form.includes(' ')) {
      addForm(form.split(' ')[0], verb);
    }
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up a verb by any known form (infinitive, conjugated form, past participle).
 * Returns the full VerbConjugation object or null if not found.
 *
 * The cell text from a grammar table is checked as-is against the index.
 * Phrases like "ik werk" are NOT matched — only bare verb forms.
 */
export function lookupVerb(cellText: string): VerbConjugation | null {
  const key = normalize(cellText);
  return formIndex.get(key) ?? null;
}

/** Get all verb entries (useful for listing / searching) */
export function getAllVerbs(): VerbConjugation[] {
  return verbs;
}
