import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IListening1: ExamPracticeTest = {
  id: 'staatsexamen-nt2-i-listening-1',
  examType: 'staatsexamen-nt2-i',
  skill: 'listening',
  title: 'Staatsexamen NT2 Programma I – Luisteren (Oefening 1)',
  description:
    'Practice exam for the Luisteren (listening) component of the Staatsexamen NT2 Programma I (B1 level). Listen to spoken Dutch fragments — radio items, interviews, conversations, and presentations — and answer comprehension questions. Each fragment can be played up to 2 times. All passages are read aloud using Dutch text-to-speech.',
  timeLimitMinutes: 50,
  passingScore: 60,
  totalQuestions: 25,
  sections: [
    // ── Fragment 1: Radioprogramma over gezondheid ──
    {
      id: 'nt2-i-l1-s1',
      passageTitle: 'Fragment 1: Radioprogramma – Bewegen op het werk',
      passage:
        'Veel Nederlanders zitten de hele dag achter een bureau. Onderzoek wijst uit dat lang zitten ongezond is, ook als je na het werk sport. Bedrijfsarts Miriam Koster legt uit wat je kunt doen. Zij adviseert om elk uur even op te staan en een paar minuten te bewegen. Een wandeling van vijf minuten door het kantoor is al voldoende. Sommige bedrijven experimenteren met sta-bureaus, waarbij werknemers ook staand kunnen werken. Uit onderzoek blijkt dat mensen die regelmatig opstaan productiever zijn en minder rugklachten hebben. Koster benadrukt dat kleine aanpassingen in je dagelijkse routine al een groot verschil kunnen maken.',
      instructions: 'Luister naar het radiofragment en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l1-q1',
          type: 'multiple-choice',
          question: 'Wat is het probleem dat in dit fragment wordt besproken?',
          options: [
            'Nederlanders bewegen te weinig in hun vrije tijd.',
            'Lang zitten is ongezond, ook voor mensen die sporten.',
            'Kantoren hebben te weinig ruimte voor werknemers.',
            'Bedrijfsartsen zijn moeilijk bereikbaar.',
          ],
          correctIndex: 1,
          explanation: '"Onderzoek wijst uit dat lang zitten ongezond is, ook als je na het werk sport."',
          topicArea: 'health-work',
        },
        {
          id: 'nt2-i-l1-q2',
          type: 'multiple-choice',
          question: 'Wat adviseert bedrijfsarts Koster?',
          options: [
            'Elke dag een uur sporten voor het werk.',
            'Elk uur even opstaan en een paar minuten bewegen.',
            'Staand werken de hele dag.',
            'Minder uren werken om gezonder te leven.',
          ],
          correctIndex: 1,
          explanation: '"Zij adviseert om elk uur even op te staan en een paar minuten te bewegen."',
          topicArea: 'health-work',
        },
        {
          id: 'nt2-i-l1-q3',
          type: 'multiple-choice',
          question: 'Wat blijkt uit het onderzoek over mensen die regelmatig opstaan?',
          options: [
            'Ze verdienen meer.',
            'Ze zijn productiever en hebben minder rugklachten.',
            'Ze slapen beter.',
            'Ze zijn minder gestrest.',
          ],
          correctIndex: 1,
          explanation: '"mensen die regelmatig opstaan productiever zijn en minder rugklachten hebben."',
          topicArea: 'health-work',
        },
        {
          id: 'nt2-i-l1-q4',
          type: 'true-false',
          question: 'Sta-bureaus zijn al in alle Nederlandse kantoren aanwezig.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Sommige bedrijven experimenteren met sta-bureaus" — only some companies are trying them.',
          topicArea: 'health-work',
        },
        {
          id: 'nt2-i-l1-q5',
          type: 'multiple-choice',
          question: 'Hoe lang moet de wandeling door het kantoor minimaal zijn?',
          options: ['Twee minuten', 'Vijf minuten', 'Tien minuten', 'Een kwartier'],
          correctIndex: 1,
          explanation: '"Een wandeling van vijf minuten door het kantoor is al voldoende."',
          topicArea: 'health-work',
        },
      ],
    },

    // ── Fragment 2: Interview over vrijwilligerswerk ──
    {
      id: 'nt2-i-l1-s2',
      passageTitle: 'Fragment 2: Interview – Vrijwilligerswerk in Nederland',
      passage:
        'Interviewer: Goedemiddag. Vandaag spreek ik met Fatima, die al drie jaar vrijwilligerswerk doet bij een voedselbank. Fatima, waarom ben je begonnen? Fatima: Ik wilde iets teruggeven aan de samenleving. Ik ben zelf nieuwkomer geweest en weet hoe moeilijk het kan zijn. Bij de voedselbank help ik met het sorteren en uitdelen van eten aan gezinnen die het financieel moeilijk hebben. Interviewer: Hoe vaak doe je dit? Fatima: Elke zaterdagochtend van negen tot één. Interviewer: Wat vind je er het mooiste aan? Fatima: De contacten met de mensen. Je ziet hoe blij ze zijn met de hulp. Dat geeft mij veel voldoening. Het heeft me ook geholpen om sneller Nederlands te leren en vrienden te maken.',
      instructions: 'Luister naar het interview en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l1-q6',
          type: 'multiple-choice',
          question: 'Waar doet Fatima vrijwilligerswerk?',
          options: [
            'Bij een ziekenhuis',
            'Bij een voedselbank',
            'Bij een bibliotheek',
            'Bij een inburgeringscursus',
          ],
          correctIndex: 1,
          explanation: '"die al drie jaar vrijwilligerswerk doet bij een voedselbank."',
          topicArea: 'volunteering',
        },
        {
          id: 'nt2-i-l1-q7',
          type: 'multiple-choice',
          question: 'Waarom is Fatima begonnen met vrijwilligerswerk?',
          options: [
            'Omdat ze verplicht was vanuit haar inburgeringscursus.',
            'Omdat ze iets wilde teruggeven aan de samenleving.',
            'Omdat ze een baan zocht bij de voedselbank.',
            'Omdat haar vrienden er ook werkten.',
          ],
          correctIndex: 1,
          explanation: '"Ik wilde iets teruggeven aan de samenleving."',
          topicArea: 'volunteering',
        },
        {
          id: 'nt2-i-l1-q8',
          type: 'multiple-choice',
          question: 'Op welk moment doet Fatima vrijwilligerswerk?',
          options: [
            'Elke vrijdagmiddag',
            'Elke zaterdagochtend van negen tot één',
            'Elke zondag de hele dag',
            'Twee avonden per week',
          ],
          correctIndex: 1,
          explanation: '"Elke zaterdagochtend van negen tot één."',
          topicArea: 'volunteering',
        },
        {
          id: 'nt2-i-l1-q9',
          type: 'multiple-choice',
          question: 'Welk extra voordeel heeft vrijwilligerswerk Fatima gebracht?',
          options: [
            'Ze heeft een vaste baan gevonden.',
            'Ze heeft een subsidie gekregen.',
            'Ze heeft sneller Nederlands geleerd en vrienden gemaakt.',
            'Ze heeft een woning gevonden.',
          ],
          correctIndex: 2,
          explanation: '"Het heeft me ook geholpen om sneller Nederlands te leren en vrienden te maken."',
          topicArea: 'volunteering',
        },
        {
          id: 'nt2-i-l1-q10',
          type: 'true-false',
          question: 'Fatima heeft zelf nooit hulp nodig gehad in Nederland.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Ik ben zelf nieuwkomer geweest en weet hoe moeilijk het kan zijn."',
          topicArea: 'volunteering',
        },
      ],
    },

    // ── Fragment 3: Informatiegesprek over huurwoning ──
    {
      id: 'nt2-i-l1-s3',
      passageTitle: 'Fragment 3: Gesprek bij een woningbouwvereniging',
      passage:
        'Medewerker: Welkom bij WoonPlus. Waarmee kan ik u helpen? Klant: Ik wil graag informatie over het huren van een sociale huurwoning. Medewerker: Natuurlijk. Om in aanmerking te komen voor een sociale huurwoning moet uw inkomen onder een bepaalde grens liggen. Die grens is dit jaar vierenveertigduizend euro per jaar voor een eenpersoonshuishouden. Klant: En hoe lang moet ik wachten? Medewerker: Dat verschilt per regio. In Utrecht is de gemiddelde wachttijd momenteel zeven jaar. Klant: Zeven jaar? Dat is lang. Medewerker: Ja, de vraag naar sociale huurwoningen is groot. U kunt zich alvast inschrijven om wachttijd op te bouwen. Inschrijven is gratis. Klant: Wat moet ik daarvoor meenemen? Medewerker: Een geldig identiteitsbewijs en een bewijs van uw inkomen, zoals een loonstrook of een uitkeringsspecificatie.',
      instructions: 'Luister naar het gesprek en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l1-q11',
          type: 'multiple-choice',
          question: 'Wat is de inkomensgrens voor een sociale huurwoning voor één persoon dit jaar?',
          options: [
            'Veertigduizend euro',
            'Tweeënveertigduizend euro',
            'Vierenveertigduizend euro',
            'Vijftigduizend euro',
          ],
          correctIndex: 2,
          explanation: '"Die grens is dit jaar vierenveertigduizend euro per jaar voor een eenpersoonshuishouden."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-i-l1-q12',
          type: 'multiple-choice',
          question: 'Hoe lang is de gemiddelde wachttijd in Utrecht?',
          options: ['Twee jaar', 'Vier jaar', 'Zeven jaar', 'Tien jaar'],
          correctIndex: 2,
          explanation: '"In Utrecht is de gemiddelde wachttijd momenteel zeven jaar."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-i-l1-q13',
          type: 'true-false',
          question: 'Inschrijven bij WoonPlus kost geld.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Inschrijven is gratis."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-i-l1-q14',
          type: 'multiple-choice',
          question: 'Wat moet de klant meenemen om zich in te schrijven?',
          options: [
            'Paspoort en huurcontract',
            'Identiteitsbewijs en bewijs van inkomen',
            'BSN-nummer en bankafschrift',
            'Werkgeversverklaring en geboorteakte',
          ],
          correctIndex: 1,
          explanation: '"Een geldig identiteitsbewijs en een bewijs van uw inkomen, zoals een loonstrook of een uitkeringsspecificatie."',
          topicArea: 'housing',
        },
        {
          id: 'nt2-i-l1-q15',
          type: 'multiple-choice',
          question: 'Waarom is de wachttijd zo lang?',
          options: [
            'Omdat WoonPlus te weinig medewerkers heeft.',
            'Omdat de regels zijn veranderd.',
            'Omdat de vraag naar sociale huurwoningen groot is.',
            'Omdat de woningen eerst gerenoveerd moeten worden.',
          ],
          correctIndex: 2,
          explanation: '"de vraag naar sociale huurwoningen is groot."',
          topicArea: 'housing',
        },
      ],
    },

    // ── Fragment 4: Presentatie over inburgering ──
    {
      id: 'nt2-i-l1-s4',
      passageTitle: 'Fragment 4: Presentatie over het nieuwe inburgeringsstelsel',
      passage:
        'Goedemiddag iedereen. Vandaag geef ik een korte presentatie over het nieuwe inburgeringsstelsel dat in 2022 is ingegaan. Vroeger waren nieuwkomers zelf verantwoordelijk voor hun inburgering. Dat leidde tot veel problemen: cursussen van wisselende kwaliteit en mensen die hun examen niet haalden. Het nieuwe stelsel werkt anders. De gemeente is nu verantwoordelijk voor de begeleiding van nieuwkomers. Elke nieuwkomer krijgt een persoonlijk Plan Inburgering en Participatie, ook wel het PIP genoemd. In dit plan staat welke cursussen u moet volgen en wat uw leerdoelen zijn. De inburgeringstermijn is drie jaar. Als u uw examen niet haalt, kunt u in sommige gevallen verlenging aanvragen. DUO, de Dienst Uitvoering Onderwijs, organiseert de examens. U kunt bij het DUO-loket meer informatie opvragen.',
      instructions: 'Luister naar de presentatie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l1-q16',
          type: 'multiple-choice',
          question: 'Wat was een probleem met het oude inburgeringsstelsel?',
          options: [
            'Het was te duur voor de overheid.',
            'Cursussen hadden wisselende kwaliteit en mensen haalden hun examen niet.',
            'De examens waren te moeilijk.',
            'Nieuwkomers hadden geen tijd om te studeren.',
          ],
          correctIndex: 1,
          explanation: '"cursussen van wisselende kwaliteit en mensen die hun examen niet haalden."',
          topicArea: 'civic-integration',
        },
        {
          id: 'nt2-i-l1-q17',
          type: 'multiple-choice',
          question: 'Wie is in het nieuwe stelsel verantwoordelijk voor de begeleiding van nieuwkomers?',
          options: ['De rijksoverheid', 'DUO', 'De gemeente', 'De werkgever'],
          correctIndex: 2,
          explanation: '"De gemeente is nu verantwoordelijk voor de begeleiding van nieuwkomers."',
          topicArea: 'civic-integration',
        },
        {
          id: 'nt2-i-l1-q18',
          type: 'multiple-choice',
          question: 'Wat staat er in het PIP?',
          options: [
            'De regels voor het krijgen van een verblijfsvergunning.',
            'Welke cursussen u moet volgen en wat uw leerdoelen zijn.',
            'Uw rechten als huurder.',
            'Een overzicht van uw inkomsten en uitgaven.',
          ],
          correctIndex: 1,
          explanation: '"In dit plan staat welke cursussen u moet volgen en wat uw leerdoelen zijn."',
          topicArea: 'civic-integration',
        },
        {
          id: 'nt2-i-l1-q19',
          type: 'multiple-choice',
          question: 'Hoe lang is de inburgeringstermijn?',
          options: ['Één jaar', 'Twee jaar', 'Drie jaar', 'Vijf jaar'],
          correctIndex: 2,
          explanation: '"De inburgeringstermijn is drie jaar."',
          topicArea: 'civic-integration',
        },
        {
          id: 'nt2-i-l1-q20',
          type: 'true-false',
          question: 'Als u uw examen niet haalt, kunt u nooit verlenging aanvragen.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"kunt u in sommige gevallen verlenging aanvragen" — in some cases an extension is possible.',
          topicArea: 'civic-integration',
        },
      ],
    },

    // ── Fragment 5: Nieuwsbericht over de arbeidsmarkt ──
    {
      id: 'nt2-i-l1-s5',
      passageTitle: 'Fragment 5: Nieuwsbericht – Krapte op de arbeidsmarkt',
      passage:
        'Het CBS, het Centraal Bureau voor de Statistiek, heeft nieuwe cijfers gepubliceerd over de arbeidsmarkt. De werkloosheid in Nederland is gedaald naar drie komma vijf procent. Dat is het laagste niveau in twintig jaar. Tegelijkertijd zijn er meer dan vierhonderdduizend openstaande vacatures. Werkgevers hebben grote moeite om personeel te vinden, vooral in de zorg, het onderwijs en de technische sector. Economen waarschuwen dat de krapte op de arbeidsmarkt kan leiden tot hogere lonen, maar ook tot hogere prijzen voor consumenten. De overheid onderzoekt hoe meer mensen, waaronder nieuwkomers en mensen met een arbeidsbeperking, aan het werk kunnen worden geholpen.',
      instructions: 'Luister naar het nieuwsbericht en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l1-q21',
          type: 'multiple-choice',
          question: 'Hoeveel procent is de werkloosheid in Nederland momenteel?',
          options: ['Twee procent', 'Drie komma vijf procent', 'Vijf procent', 'Zeven procent'],
          correctIndex: 1,
          explanation: '"De werkloosheid in Nederland is gedaald naar drie komma vijf procent."',
          topicArea: 'labour-market',
        },
        {
          id: 'nt2-i-l1-q22',
          type: 'multiple-choice',
          question: 'In welke sectoren hebben werkgevers de meeste moeite om personeel te vinden?',
          options: [
            'De horeca, de bouw en de detailhandel',
            'De zorg, het onderwijs en de technische sector',
            'De overheid, de juridische sector en de financiën',
            'De landbouw, de visserij en het transport',
          ],
          correctIndex: 1,
          explanation: '"vooral in de zorg, het onderwijs en de technische sector."',
          topicArea: 'labour-market',
        },
        {
          id: 'nt2-i-l1-q23',
          type: 'true-false',
          question: 'De huidige werkloosheid is het laagste niveau in twintig jaar.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 0,
          explanation: '"Dat is het laagste niveau in twintig jaar."',
          topicArea: 'labour-market',
        },
        {
          id: 'nt2-i-l1-q24',
          type: 'multiple-choice',
          question: 'Hoeveel openstaande vacatures zijn er momenteel?',
          options: [
            'Meer dan honderdduizend',
            'Meer dan tweehonderdduizend',
            'Meer dan driehonderdduizend',
            'Meer dan vierhonderdduizend',
          ],
          correctIndex: 3,
          explanation: '"zijn er meer dan vierhonderdduizend openstaande vacatures."',
          topicArea: 'labour-market',
        },
        {
          id: 'nt2-i-l1-q25',
          type: 'multiple-choice',
          question: 'Welke groepen noemt de overheid als mogelijke oplossing voor de krapte?',
          options: [
            'Studenten en gepensioneerden',
            'Nieuwkomers en mensen met een arbeidsbeperking',
            'Vrouwen en jongeren',
            'Zelfstandigen en zzp\'ers',
          ],
          correctIndex: 1,
          explanation: '"hoe meer mensen, waaronder nieuwkomers en mensen met een arbeidsbeperking, aan het werk kunnen worden geholpen."',
          topicArea: 'labour-market',
        },
      ],
    },
  ],
};
