import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IListening2: ExamPracticeTest = {
  id: 'staatsexamen-nt2-i-listening-2',
  examType: 'staatsexamen-nt2-i',
  skill: 'listening',
  title: 'Staatsexamen NT2 Programma I – Luisteren (Oefening 2)',
  description:
    'Practice exam for the Luisteren (listening) component of the Staatsexamen NT2 Programma I (B1 level). Listen to spoken Dutch fragments — radio items, interviews, conversations, and presentations — and answer comprehension questions. Each fragment can be played up to 2 times. All passages are read aloud using Dutch text-to-speech.',
  timeLimitMinutes: 50,
  passingScore: 60,
  totalQuestions: 25,
  sections: [
    // ── Fragment 1: Radioprogramma over onderwijs ──
    {
      id: 'nt2-i-l2-s1',
      passageTitle: 'Fragment 1: Radioprogramma – Bijles en kansenongelijkheid',
      passage:
        'Steeds meer ouders betalen voor bijles voor hun kinderen. Volgens onderzoek van de Universiteit van Amsterdam heeft inmiddels één op de drie middelbare scholieren bijles. Onderwijsdeskundige Pieter Vos legt uit dat dit een probleem is voor de gelijke kansen in het onderwijs. Kinderen van rijke ouders kunnen dure bijles betalen, terwijl kinderen uit armere gezinnen dat niet kunnen. Hierdoor krijgen kinderen met vergelijkbare capaciteiten toch ongelijke kansen. Vos pleit voor meer gratis ondersteuning op school zelf, zodat bijles niet nodig is. Sommige scholen bieden al huiswerkbegeleiding aan na schooltijd. Het ministerie van Onderwijs onderzoekt of dit breder ingevoerd kan worden.',
      instructions: 'Luister naar het radiofragment en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l2-q1',
          type: 'multiple-choice',
          question: 'Hoeveel middelbare scholieren heeft bijles volgens het onderzoek?',
          options: [
            'Één op de vijf',
            'Één op de vier',
            'Één op de drie',
            'Één op de twee',
          ],
          correctIndex: 2,
          explanation: '"heeft inmiddels één op de drie middelbare scholieren bijles."',
          topicArea: 'education',
        },
        {
          id: 'nt2-i-l2-q2',
          type: 'multiple-choice',
          question: 'Wat is het probleem dat Pieter Vos beschrijft?',
          options: [
            'Bijles is te duur voor scholen om aan te bieden.',
            'Rijke kinderen kunnen bijles betalen, arme kinderen niet, wat leidt tot ongelijke kansen.',
            'Leraren zijn tegen bijles omdat het hun werk overneemt.',
            'Bijles helpt niet en is tijdverspilling.',
          ],
          correctIndex: 1,
          explanation: '"Kinderen van rijke ouders kunnen dure bijles betalen, terwijl kinderen uit armere gezinnen dat niet kunnen."',
          topicArea: 'education',
        },
        {
          id: 'nt2-i-l2-q3',
          type: 'multiple-choice',
          question: 'Wat stelt Vos voor als oplossing?',
          options: [
            'Bijles verbieden.',
            'Meer gratis ondersteuning op school zelf.',
            'Subsidie geven voor bijles aan arme gezinnen.',
            'Scholen langer open houden.',
          ],
          correctIndex: 1,
          explanation: '"Vos pleit voor meer gratis ondersteuning op school zelf, zodat bijles niet nodig is."',
          topicArea: 'education',
        },
        {
          id: 'nt2-i-l2-q4',
          type: 'true-false',
          question: 'Alle scholen bieden al huiswerkbegeleiding aan na schooltijd.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Sommige scholen bieden al huiswerkbegeleiding aan" — only some, not all.',
          topicArea: 'education',
        },
        {
          id: 'nt2-i-l2-q5',
          type: 'multiple-choice',
          question: 'Wat onderzoekt het ministerie van Onderwijs?',
          options: [
            'Of bijles verplicht moet worden.',
            'Of huiswerkbegeleiding op school breder ingevoerd kan worden.',
            'Of de lestijden verlengd moeten worden.',
            'Of het eindexamen moeilijker moet worden.',
          ],
          correctIndex: 1,
          explanation: '"Het ministerie van Onderwijs onderzoekt of dit breder ingevoerd kan worden."',
          topicArea: 'education',
        },
      ],
    },

    // ── Fragment 2: Interview over mantelzorg ──
    {
      id: 'nt2-i-l2-s2',
      passageTitle: 'Fragment 2: Interview – Mantelzorg in Nederland',
      passage:
        'Interviewer: Vandaag spreek ik met Khalid, die voor zijn zieke moeder zorgt. Khalid, hoe lang doe je dit al? Khalid: Al twee jaar. Mijn moeder heeft een herseninfarct gehad en kan niet meer zelfstandig wonen. Interviewer: Hoe combineer je dat met je werk? Khalid: Dat is moeilijk. Ik werk vier dagen per week en zorg drie dagen voor mijn moeder. Gelukkig heeft mijn werkgever begrip en mag ik soms thuis werken. Interviewer: Krijg je hulp van de gemeente? Khalid: Ja, een thuiszorgmedewerker komt twee keer per week. Maar ik voel me soms erg moe en eenzaam. Er zijn weinig voorzieningen voor mantelzorgers zelf. Ik zou graag meer respijtzorg willen, zodat ik af en toe even vrij kan nemen. Interviewer: Wat is respijtzorg precies? Khalid: Dat is tijdelijke opvang voor de persoon die zorg nodig heeft, zodat de mantelzorger even op adem kan komen.',
      instructions: 'Luister naar het interview en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l2-q6',
          type: 'multiple-choice',
          question: 'Waarom kan Khalids moeder niet meer zelfstandig wonen?',
          options: [
            'Ze is te oud.',
            'Ze heeft een herseninfarct gehad.',
            'Ze heeft financiële problemen.',
            'Ze woont te ver weg.',
          ],
          correctIndex: 1,
          explanation: '"Mijn moeder heeft een herseninfarct gehad en kan niet meer zelfstandig wonen."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-i-l2-q7',
          type: 'multiple-choice',
          question: 'Hoeveel dagen per week werkt Khalid?',
          options: ['Twee dagen', 'Drie dagen', 'Vier dagen', 'Vijf dagen'],
          correctIndex: 2,
          explanation: '"Ik werk vier dagen per week en zorg drie dagen voor mijn moeder."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-i-l2-q8',
          type: 'multiple-choice',
          question: 'Hoe vaak komt de thuiszorgmedewerker?',
          options: [
            'Elke dag',
            'Eén keer per week',
            'Twee keer per week',
            'Drie keer per week',
          ],
          correctIndex: 2,
          explanation: '"een thuiszorgmedewerker komt twee keer per week."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-i-l2-q9',
          type: 'multiple-choice',
          question: 'Wat is respijtzorg?',
          options: [
            'Extra geld voor mantelzorgers.',
            'Tijdelijke opvang voor de zorgbehoevende, zodat de mantelzorger even vrij heeft.',
            'Professionele hulp bij het invullen van formulieren.',
            'Een cursus voor mantelzorgers.',
          ],
          correctIndex: 1,
          explanation: '"Dat is tijdelijke opvang voor de persoon die zorg nodig heeft, zodat de mantelzorger even op adem kan komen."',
          topicArea: 'healthcare',
        },
        {
          id: 'nt2-i-l2-q10',
          type: 'true-false',
          question: 'Khalids werkgever heeft geen begrip voor zijn situatie.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Gelukkig heeft mijn werkgever begrip en mag ik soms thuis werken."',
          topicArea: 'healthcare',
        },
      ],
    },

    // ── Fragment 3: Gesprek over een klacht bij een gemeente ──
    {
      id: 'nt2-i-l2-s3',
      passageTitle: 'Fragment 3: Telefoongesprek – Klacht over overlast',
      passage:
        'Medewerker: Gemeente Rotterdam, goedenmiddag. Beller: Goedenmiddag, ik wil een klacht indienen over geluidsoverlast in mijn straat. Medewerker: Kunt u mij meer informatie geven? Beller: Ja, er is al drie weken een bouwproject naast mijn huis. Ze beginnen elke ochtend om zeven uur met boren en slaan. Maar de vergunning zegt dat ze pas om acht uur mogen beginnen. Medewerker: Begrijpt u het. Heeft u al contact opgenomen met de aannemer? Beller: Ja, maar die zegt dat ze de regels wel volgen. Dat klopt niet. Medewerker: Dan kunt u een formele klacht indienen. Ik kan nu uw gegevens noteren en een handhaver sturen om de situatie te controleren. Beller: Graag. Medewerker: Wat is uw naam en adres? Beller: Reza Ahmadi, Maasstraat veertien. Medewerker: Ik registreer uw klacht. U ontvangt binnen drie werkdagen een bevestiging per e-mail.',
      instructions: 'Luister naar het gesprek en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l2-q11',
          type: 'multiple-choice',
          question: 'Waar belt Reza over?',
          options: [
            'Over een kapotte stoep voor zijn huis.',
            'Over geluidsoverlast van een bouwproject.',
            'Over een parkeerprobleem in zijn straat.',
            'Over een conflict met een buurman.',
          ],
          correctIndex: 1,
          explanation: '"ik wil een klacht indienen over geluidsoverlast in mijn straat."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q12',
          type: 'multiple-choice',
          question: 'Hoe laat mag het bouwproject volgens de vergunning beginnen?',
          options: ['Om zes uur', 'Om zeven uur', 'Om acht uur', 'Om negen uur'],
          correctIndex: 2,
          explanation: '"de vergunning zegt dat ze pas om acht uur mogen beginnen."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q13',
          type: 'true-false',
          question: 'Reza heeft de aannemer nog niet gecontacteerd.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Ja, maar die zegt dat ze de regels wel volgen." — he already contacted the contractor.',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q14',
          type: 'multiple-choice',
          question: 'Wat gaat de gemeente doen?',
          options: [
            'De vergunning intrekken.',
            'Een brief sturen naar de aannemer.',
            'Een handhaver sturen om de situatie te controleren.',
            'De politie inschakelen.',
          ],
          correctIndex: 2,
          explanation: '"een handhaver sturen om de situatie te controleren."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q15',
          type: 'multiple-choice',
          question: 'Wanneer ontvangt Reza een bevestiging?',
          options: [
            'Dezelfde dag nog',
            'Binnen één werkdag',
            'Binnen drie werkdagen',
            'Binnen een week',
          ],
          correctIndex: 2,
          explanation: '"U ontvangt binnen drie werkdagen een bevestiging per e-mail."',
          topicArea: 'government-services',
        },
      ],
    },

    // ── Fragment 4: Presentatie over duurzaamheid ──
    {
      id: 'nt2-i-l2-s4',
      passageTitle: 'Fragment 4: Presentatie over duurzaam leven',
      passage:
        'Goedemorgen iedereen. Vandaag geef ik een korte presentatie over hoe je duurzamer kunt leven zonder veel geld uit te geven. Veel mensen denken dat duurzaamheid duur is, maar dat is niet altijd zo. Ten eerste: koop minder en koop bewust. Tweedehands winkels en online marktplaatsen zijn goede alternatieven voor nieuwe producten. Ten tweede: bespaar energie thuis. Zet de verwarming een paar graden lager en gebruik energiezuinige lampen. Dat scheelt gemiddeld honderd euro per jaar op je energierekening. Ten derde: eet minder vlees. De vleesindustrie is verantwoordelijk voor een groot deel van de CO2-uitstoot. Één vleesloze dag per week maakt al een verschil. Ten vierde: gebruik het openbaar vervoer of de fiets voor korte afstanden. En tot slot: repareer spullen in plaats van ze weg te gooien. Er zijn steeds meer repair cafés in Nederland waar je gratis hulp krijgt.',
      instructions: 'Luister naar de presentatie en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l2-q16',
          type: 'multiple-choice',
          question: 'Hoeveel kan men gemiddeld besparen door energiezuinige maatregelen thuis?',
          options: [
            'Vijftig euro per jaar',
            'Honderd euro per jaar',
            'Tweehonderd euro per jaar',
            'Driehonderd euro per jaar',
          ],
          correctIndex: 1,
          explanation: '"Dat scheelt gemiddeld honderd euro per jaar op je energierekening."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-l2-q17',
          type: 'multiple-choice',
          question: 'Wat wordt bedoeld met "repair cafés"?',
          options: [
            'Cafés waar je tweedehands spullen kunt kopen.',
            'Plekken waar je gratis hulp krijgt om spullen te repareren.',
            'Workshops over duurzame voeding.',
            'Winkels die energie-efficiënte producten verkopen.',
          ],
          correctIndex: 1,
          explanation: '"Er zijn steeds meer repair cafés in Nederland waar je gratis hulp krijgt."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-l2-q18',
          type: 'true-false',
          question: 'Volgens de presentatie is duurzaam leven altijd duur.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"Veel mensen denken dat duurzaamheid duur is, maar dat is niet altijd zo."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-l2-q19',
          type: 'multiple-choice',
          question: 'Hoeveel vleesloze dagen per week worden er aanbevolen?',
          options: ['Één dag', 'Twee dagen', 'Drie dagen', 'Elke dag'],
          correctIndex: 0,
          explanation: '"Één vleesloze dag per week maakt al een verschil."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-l2-q20',
          type: 'multiple-choice',
          question: 'Welke van de volgende tips wordt NIET genoemd in de presentatie?',
          options: [
            'Tweedehands producten kopen.',
            'Minder vlees eten.',
            'Zonnepanelen installeren.',
            'Het openbaar vervoer gebruiken.',
          ],
          correctIndex: 2,
          explanation: 'Solar panels are not mentioned — the tips are: buy secondhand, save energy, eat less meat, use public transport, and repair instead of throw away.',
          topicArea: 'sustainability',
        },
      ],
    },

    // ── Fragment 5: Nieuwsbericht over digitalisering ──
    {
      id: 'nt2-i-l2-s5',
      passageTitle: 'Fragment 5: Nieuwsbericht – Digitale overheid',
      passage:
        'De Nederlandse overheid digitaliseert steeds meer diensten. Burgers kunnen nu voor veel zaken terecht op MijnOverheid.nl, een persoonlijk digitaal loket. Denk aan het doorgeven van een adreswijziging, het aanvragen van een uittreksel uit de basisregistratie of het inzien van belastingaanslagen. Toch zijn er zorgen. Een recent onderzoek van de Nationale ombudsman wijst uit dat ruim één miljoen Nederlanders moeite heeft met digitale dienstverlening. Het gaat vooral om ouderen, laaggeletterden en mensen met een beperking. De ombudsman pleit ervoor dat de overheid altijd ook een niet-digitale optie blijft aanbieden, zoals een telefonisch loket of balie. Sommige gemeenten bieden al digitale hulpklassen aan om burgers te helpen met de overheidswebsites.',
      instructions: 'Luister naar het nieuwsbericht en beantwoord de vragen.',
      questions: [
        {
          id: 'nt2-i-l2-q21',
          type: 'multiple-choice',
          question: 'Wat kun je doen op MijnOverheid.nl?',
          options: [
            'Belasting betalen en een rijbewijs aanvragen.',
            'Een adreswijziging doorgeven, een uittreksel aanvragen en belastingaanslagen inzien.',
            'Een paspoort aanvragen en stemmen bij verkiezingen.',
            'Subsidies aanvragen en huurtoeslagen berekenen.',
          ],
          correctIndex: 1,
          explanation: '"het doorgeven van een adreswijziging, het aanvragen van een uittreksel uit de basisregistratie of het inzien van belastingaanslagen."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q22',
          type: 'multiple-choice',
          question: 'Hoeveel Nederlanders heeft moeite met digitale dienstverlening?',
          options: [
            'Ruim vijfhonderdduizend',
            'Ruim één miljoen',
            'Ruim twee miljoen',
            'Ruim drie miljoen',
          ],
          correctIndex: 1,
          explanation: '"ruim één miljoen Nederlanders moeite heeft met digitale dienstverlening."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q23',
          type: 'multiple-choice',
          question: 'Welke groepen worden speciaal genoemd als mensen die moeite hebben met digitale diensten?',
          options: [
            'Jongeren, studenten en werklozen',
            'Ouderen, laaggeletterden en mensen met een beperking',
            'Ondernemers, zzp\'ers en boeren',
            'Nieuwkomers en mensen zonder bankrekening',
          ],
          correctIndex: 1,
          explanation: '"Het gaat vooral om ouderen, laaggeletterden en mensen met een beperking."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q24',
          type: 'true-false',
          question: 'De Nationale ombudsman vindt dat de overheid alleen digitaal moet werken.',
          options: ['Juist', 'Onjuist'],
          correctIndex: 1,
          explanation: '"De ombudsman pleit ervoor dat de overheid altijd ook een niet-digitale optie blijft aanbieden."',
          topicArea: 'government-services',
        },
        {
          id: 'nt2-i-l2-q25',
          type: 'multiple-choice',
          question: 'Hoe helpen sommige gemeenten burgers met de overheidswebsites?',
          options: [
            'Door gratis internet aan te bieden.',
            'Door digitale hulpklassen aan te bieden.',
            'Door medewerkers aan huis te sturen.',
            'Door een speciale app te ontwikkelen.',
          ],
          correctIndex: 1,
          explanation: '"Sommige gemeenten bieden al digitale hulpklassen aan om burgers te helpen met de overheidswebsites."',
          topicArea: 'government-services',
        },
      ],
    },
  ],
};
