import { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IReading3: ExamPracticeTest = {
  id: 'staatsexamen-nt2-i-reading-3',
  examType: 'staatsexamen-nt2-i',
  skill: 'reading',
  title: 'Staatsexamen NT2 Programma I – Lezen (Oefening 3)',
  description:
    'Practice reading exam at B1 level. Read longer Dutch texts and answer questions. Topics: consumer rights, immigration procedures, work and benefits, community participation.',
  timeLimitMinutes: 75,
  passingScore: 60,
  totalQuestions: 30,
  sections: [
    {
      id: 'nt2-i-r3-s1',
      passageTitle: 'Consumentenrechten: wat zijn uw rechten bij online aankopen?',
      passage:
        'Steeds meer Nederlanders kopen producten online. Maar wat zijn uw rechten als u iets online koopt?\n\nAls u iets online koopt bij een webwinkel in Nederland of Europa, heeft u het recht om de aankoop binnen 14 dagen te annuleren. U hoeft daarvoor geen reden op te geven. Dit heet het herroepingsrecht. U stuurt het product terug en krijgt het betaalde bedrag terug.\n\nLet op: sommige producten vallen niet onder het herroepingsrecht. Dit geldt voor op maat gemaakte producten, digitale downloads die al zijn gestart, en verse levensmiddelen.\n\nAls een product kapot is bij aankomst, heeft u recht op reparatie, vervanging of terugbetaling. U heeft wettelijk twee jaar garantie op producten.\n\nBij een probleem met een webwinkel kunt u eerst zelf contact opnemen. Lost dit niets op, dan kunt u een klacht indienen bij de Geschillencommissie of de Autoriteit Consument & Markt (ACM).',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s1-q1',
          type: 'multiple-choice',
          question: 'What is the "herroepingsrecht"?',
          options: [
            'The right to get a discount on a second purchase.',
            'The right to cancel an online purchase within 14 days without giving a reason.',
            'The right to a two-year guarantee on all products.',
            'The right to complain about a webshop to the government.',
          ],
          correctIndex: 1,
          explanation: '"Het recht om de aankoop binnen 14 dagen te annuleren. U hoeft daarvoor geen reden op te geven."',
          topicArea: 'consumer-rights',
        },
        {
          id: 'nt2-i-r3-s1-q2',
          type: 'multiple-choice',
          question: 'Which of the following is NOT covered by the herroepingsrecht?',
          options: ['A book ordered online.', 'A pair of shoes ordered online.', 'A digital download that has already started.', 'A laptop ordered online.'],
          correctIndex: 2,
          explanation: '"Digitale downloads die al zijn gestart" are excluded from the herroepingsrecht.',
          topicArea: 'consumer-rights',
        },
        {
          id: 'nt2-i-r3-s1-q3',
          type: 'multiple-choice',
          question: 'How long is the legal guarantee on products?',
          options: ['6 months.', '1 year.', '2 years.', '5 years.'],
          correctIndex: 2,
          explanation: '"U heeft wettelijk twee jaar garantie op producten."',
          topicArea: 'consumer-rights',
        },
        {
          id: 'nt2-i-r3-s1-q4',
          type: 'multiple-choice',
          question: 'If you have a problem with an online shop that you cannot resolve directly, what can you do?',
          options: [
            'Go to the police.',
            'Contact your bank.',
            'File a complaint with the Geschillencommissie or the ACM.',
            'Return the product at a physical store.',
          ],
          correctIndex: 2,
          explanation: '"Dan kunt u een klacht indienen bij de Geschillencommissie of de Autoriteit Consument & Markt (ACM)."',
          topicArea: 'consumer-rights',
        },
        {
          id: 'nt2-i-r3-s1-q5',
          type: 'multiple-choice',
          question: 'What should you do first if you receive a broken product from a webshop?',
          options: [
            'Immediately go to the Geschillencommissie.',
            'Contact the webshop directly.',
            'Ask your local municipality for help.',
            'Report it to the police.',
          ],
          correctIndex: 1,
          explanation: '"Bij een probleem met een webwinkel kunt u eerst zelf contact opnemen."',
          topicArea: 'consumer-rights',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s2',
      passageTitle: 'Brief van de gemeente: verblijfsvergunning verlengd',
      passage:
        'Geachte mevrouw Osei,\n\nWij schrijven u naar aanleiding van uw aanvraag voor verlenging van uw verblijfsvergunning. Wij zijn blij u te informeren dat uw verblijfsvergunning is verlengd tot 1 maart 2027.\n\nUw nieuwe verblijfsdocument (verblijfspas) kunt u ophalen bij het Gemeenteloket. Neem hiervoor een geldig identiteitsbewijs mee. Het document is beschikbaar vanaf 1 maart 2025 en dient binnen zes weken te worden opgehaald.\n\nLet op: na het ophalen dient u uw verblijfspas altijd bij u te dragen.\n\nAls uw adres of gezinssituatie verandert, bent u verplicht dit binnen 5 dagen te melden bij de gemeente.\n\nVoor vragen kunt u bellen met het Gemeenteloket: 14 020 (maandag–vrijdag 08:00–17:00).',
      instructions: 'Read the letter and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s2-q1',
          type: 'multiple-choice',
          question: 'What is the purpose of this letter?',
          options: [
            'To inform about a rejected residence permit application.',
            'To inform that the residence permit has been renewed.',
            'To request additional documents for the application.',
            'To notify about a change in immigration rules.',
          ],
          correctIndex: 1,
          explanation: '"Uw verblijfsvergunning is verlengd tot 1 maart 2027."',
          topicArea: 'immigration',
        },
        {
          id: 'nt2-i-r3-s2-q2',
          type: 'multiple-choice',
          question: 'Where can the recipient collect the new residence document?',
          options: ['At the IND office.', 'At the municipality counter (Gemeenteloket).', 'By post — it will be mailed.', 'At the police station.'],
          correctIndex: 1,
          explanation: '"U kunt ophalen bij het Gemeenteloket."',
          topicArea: 'immigration',
        },
        {
          id: 'nt2-i-r3-s2-q3',
          type: 'multiple-choice',
          question: 'How long does the recipient have to collect the document?',
          options: ['Two weeks.', 'Four weeks.', 'Six weeks.', 'Three months.'],
          correctIndex: 2,
          explanation: '"Dient binnen zes weken te worden opgehaald."',
          topicArea: 'immigration',
        },
        {
          id: 'nt2-i-r3-s2-q4',
          type: 'multiple-choice',
          question: 'What must the recipient report to the municipality within 5 days?',
          options: [
            'Any travel abroad.',
            'Any change of address or family situation.',
            'Any change in employment.',
            'Any illness or hospital stay.',
          ],
          correctIndex: 1,
          explanation: '"Als uw adres of gezinssituatie verandert, bent u verplicht dit binnen 5 dagen te melden."',
          topicArea: 'immigration',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s3',
      passageTitle: 'Artikel: Werken met een tijdelijk contract',
      passage:
        'In Nederland werken veel mensen met een tijdelijk contract, ook wel een "contract voor bepaalde tijd" genoemd. Dit is een contract dat eindigt op een vastgestelde datum.\n\nEen werkgever mag maximaal drie tijdelijke contracten geven in een periode van drie jaar. Daarna moet de werknemer een vast contract krijgen, of het dienstverband eindigt. Dit heet de ketenregeling.\n\nBij het einde van een tijdelijk contract van zes maanden of langer, heeft u recht op een transitievergoeding. Deze vergoeding is bedoeld als compensatie voor het verlies van werk.\n\nAls uw tijdelijke contract niet verlengd wordt, kunt u WW aanvragen. WW staat voor Werkloosheidswet. U ontvangt dan tijdelijk een uitkering van het UWV. Hiervoor gelden voorwaarden: u moet minstens 26 weken van de afgelopen 36 weken gewerkt hebben.\n\nHeeft u vragen over uw rechten? De vakbond of het UWV kan u meer informatie geven.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s3-q1',
          type: 'multiple-choice',
          question: 'What is the "ketenregeling"?',
          options: [
            'A rule that temporary contracts cannot be longer than 6 months.',
            'A rule that after 3 temporary contracts in 3 years, a permanent contract must follow or the employment ends.',
            'A rule requiring the employer to pay a transition fee after each contract.',
            'A rule allowing employers to give unlimited temporary contracts.',
          ],
          correctIndex: 1,
          explanation: '"Een werkgever mag maximaal drie tijdelijke contracten geven in een periode van drie jaar. Daarna moet de werknemer een vast contract krijgen…"',
          topicArea: 'work',
        },
        {
          id: 'nt2-i-r3-s3-q2',
          type: 'multiple-choice',
          question: 'What is a "transitievergoeding"?',
          options: [
            'A bonus for long-term employees.',
            'A subsidy from the government for new employees.',
            'Compensation paid when a contract of 6 months or longer ends.',
            'A fine the employer must pay for late payment.',
          ],
          correctIndex: 2,
          explanation: '"Bij het einde van een tijdelijk contract van zes maanden of langer, heeft u recht op een transitievergoeding … als compensatie voor het verlies van werk."',
          topicArea: 'work',
        },
        {
          id: 'nt2-i-r3-s3-q3',
          type: 'multiple-choice',
          question: 'What does WW stand for and who pays it?',
          options: [
            'Wet Werk — paid by the employer.',
            'Werkloosheidswet — paid by the UWV.',
            'Werktijdverkorting — paid by the government.',
            'Werkgeversvergoeding — paid by the municipality.',
          ],
          correctIndex: 1,
          explanation: '"WW staat voor Werkloosheidswet. U ontvangt dan tijdelijk een uitkering van het UWV."',
          topicArea: 'benefits',
        },
        {
          id: 'nt2-i-r3-s3-q4',
          type: 'multiple-choice',
          question: 'What is the minimum work requirement to be eligible for WW?',
          options: [
            'At least 12 weeks in the past 6 months.',
            'At least 26 weeks in the past 36 weeks.',
            'At least 52 weeks in the past 2 years.',
            'Any amount of work — there is no minimum.',
          ],
          correctIndex: 1,
          explanation: '"U moet minstens 26 weken van de afgelopen 36 weken gewerkt hebben."',
          topicArea: 'benefits',
        },
        {
          id: 'nt2-i-r3-s3-q5',
          type: 'multiple-choice',
          question: 'Where can you get information about your rights as an employee?',
          options: [
            'Only at the municipality.',
            'From the vakbond (trade union) or the UWV.',
            'From the landlord.',
            'There is no organisation that helps with this.',
          ],
          correctIndex: 1,
          explanation: '"De vakbond of het UWV kan u meer informatie geven."',
          topicArea: 'work',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s4',
      passageTitle: 'Memo van de werkgever: veranderingen in de pensioenregeling',
      passage:
        'Aan: alle medewerkers\nVan: afdeling HR\nBetreft: wijzigingen in de pensioenregeling per 1 januari 2026\n\nVanaf 1 januari 2026 verandert de pensioenregeling van ons bedrijf. De belangrijkste wijzigingen zijn:\n\n1. De pensioenpremie die u zelf betaalt, gaat omhoog van 4% naar 5% van uw brutosalaris.\n2. De pensioenleeftijd blijft 67 jaar, maar u kunt eerder met pensioen gaan als u dat wilt — met verlaging van het maandelijkse bedrag.\n3. Medewerkers die deeltijd werken, bouwen pensioen op naar rato van hun arbeidsuren.\n\nU ontvangt een persoonlijk overzicht van uw opgebouwd pensioen in december. Heeft u vragen? Neem contact op met uw pensioenadviseur via pensioen@bedrijf.nl.\n\nDe OR (ondernemingsraad) heeft ingestemd met deze wijzigingen.',
      instructions: 'Read the memo and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s4-q1',
          type: 'multiple-choice',
          question: 'What change is happening to the employee pension contribution?',
          options: [
            'It is decreasing from 5% to 4%.',
            'It is increasing from 4% to 5% of gross salary.',
            'It is being replaced by a government payment.',
            'There is no change to the contribution.',
          ],
          correctIndex: 1,
          explanation: '"De pensioenpremie … gaat omhoog van 4% naar 5% van uw brutosalaris."',
          topicArea: 'work',
        },
        {
          id: 'nt2-i-r3-s4-q2',
          type: 'multiple-choice',
          question: 'What is the retirement age?',
          options: ['65 years.', '66 years.', '67 years.', '68 years.'],
          correctIndex: 2,
          explanation: '"De pensioenleeftijd blijft 67 jaar."',
          topicArea: 'work',
        },
        {
          id: 'nt2-i-r3-s4-q3',
          type: 'multiple-choice',
          question: 'What happens if an employee retires earlier than the standard age?',
          options: [
            'They receive a bonus payment.',
            'They receive a higher monthly amount.',
            'Their monthly pension amount is reduced.',
            'They lose all pension rights.',
          ],
          correctIndex: 2,
          explanation: '"U kunt eerder met pensioen gaan als u dat wilt — met verlaging van het maandelijkse bedrag."',
          topicArea: 'work',
        },
        {
          id: 'nt2-i-r3-s4-q4',
          type: 'multiple-choice',
          question: 'How do part-time workers accrue pension?',
          options: [
            'They receive the same as full-time workers.',
            'They do not build up pension.',
            'Proportionally, based on their working hours.',
            'At a higher rate to compensate.',
          ],
          correctIndex: 2,
          explanation: '"Medewerkers die deeltijd werken, bouwen pensioen op naar rato van hun arbeidsuren."',
          topicArea: 'work',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s5',
      passageTitle: 'Artikel: Vrijwilligerswerk in Nederland',
      passage:
        'Meer dan 5 miljoen Nederlanders doen vrijwilligerswerk. Vrijwilligerswerk is werk dat u doet zonder betaling, voor een organisatie of instelling. Voorbeelden zijn: helpen bij een voedselbank, coachen bij een sportclub, of ondersteunen bij een buurtvereniging.\n\nVrijwilligerswerk is goed voor u en voor de samenleving. U leert nieuwe vaardigheden, bouwt een sociaal netwerk op en verbetert uw Nederlands.\n\nBent u een nieuwkomer in Nederland? Vrijwilligerswerk kan u helpen om de Nederlandse taal en cultuur beter te leren kennen. Veel gemeenten en vluchtelingenorganisaties koppelen nieuwkomers aan vrijwilligersplekken.\n\nTips voor beginnen:\n– Zoek via de website NLvoorelkaar.nl naar vrijwilligersfuncties bij u in de buurt.\n– Praat met uw inburgeringscoach of maatschappelijk werker.\n– Begin klein: probeer een dagdeel per week.\n\nLet op: vrijwilligerswerk is niet hetzelfde als een stage of betaald werk. U heeft geen arbeidscontract en betaalt geen belasting over ontvangen vergoedingen tot €190 per maand.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s5-q1',
          type: 'multiple-choice',
          question: 'What is "vrijwilligerswerk"?',
          options: [
            'Paid part-time work regulated by the government.',
            'Work done without payment for an organisation or institution.',
            'A mandatory community service for new residents.',
            'A type of internship that can lead to a job.',
          ],
          correctIndex: 1,
          explanation: '"Vrijwilligerswerk is werk dat u doet zonder betaling, voor een organisatie of instelling."',
          topicArea: 'society',
        },
        {
          id: 'nt2-i-r3-s5-q2',
          type: 'multiple-choice',
          question: 'What is the tax rule for volunteer compensation?',
          options: [
            'All compensation must be reported to the tax office.',
            'Compensation up to €190 per month is tax-free.',
            'Compensation is always tax-free, regardless of amount.',
            'Volunteers may not receive any compensation.',
          ],
          correctIndex: 1,
          explanation: '"U betaalt geen belasting over ontvangen vergoedingen tot €190 per maand."',
          topicArea: 'society',
        },
        {
          id: 'nt2-i-r3-s5-q3',
          type: 'multiple-choice',
          question: 'How can a newcomer find a volunteer position?',
          options: [
            'Only through the municipality\'s social services.',
            'By contacting a trade union.',
            'Via NLvoorelkaar.nl, through a civic integration coach, or social worker.',
            'By visiting the Chamber of Commerce.',
          ],
          correctIndex: 2,
          explanation: '"Zoek via NLvoorelkaar.nl … Praat met uw inburgeringscoach of maatschappelijk werker."',
          topicArea: 'society',
        },
        {
          id: 'nt2-i-r3-s5-q4',
          type: 'multiple-choice',
          question: 'According to the article, what is one benefit of volunteering for newcomers?',
          options: [
            'They receive financial compensation from the government.',
            'It leads directly to a paid job.',
            'It helps them learn the Dutch language and culture.',
            'They are exempt from civic integration requirements.',
          ],
          correctIndex: 2,
          explanation: '"Vrijwilligerswerk kan u helpen om de Nederlandse taal en cultuur beter te leren kennen."',
          topicArea: 'society',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s6',
      passageTitle: 'Brief: kinderopvangtoeslag wijzigingen',
      passage:
        'Geachte ouder/verzorger,\n\nU ontvangt momenteel kinderopvangtoeslag van de Belastingdienst/Toeslagen. Wij schrijven u om u te informeren over wijzigingen per 1 september 2025.\n\nWat verandert er?\n– Het maximale uurtarief waarover toeslag wordt berekend, stijgt naar €10,25 per uur.\n– Ouders die meer dan 40 uur per week werken, kunnen voor maximaal 230 uur opvang per maand toeslag ontvangen.\n– U dient uw inkomensgegevens uiterlijk 1 augustus 2025 door te geven via Mijn Toeslagen.\n\nWat blijft hetzelfde?\n– Uw kind moet op een geregistreerde opvang zitten.\n– Uw BSN en dat van uw kind moeten bekend zijn bij ons.\n\nBent u niet meer werkzaam of verandert uw situatie? Geef dit direct door om te hoge toeslagen te voorkomen.\n\nVoor meer informatie: www.belastingdienst.nl/toeslagen of bel 0800-0543 (gratis).',
      instructions: 'Read the letter and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s6-q1',
          type: 'multiple-choice',
          question: 'What is changing for parents working more than 40 hours per week?',
          options: [
            'They will receive less childcare allowance.',
            'They can receive allowance for up to 230 hours of childcare per month.',
            'They must now use only registered childcare.',
            'They are no longer eligible for kinderopvangtoeslag.',
          ],
          correctIndex: 1,
          explanation: '"Ouders die meer dan 40 uur per week werken, kunnen voor maximaal 230 uur opvang per maand toeslag ontvangen."',
          topicArea: 'benefits',
        },
        {
          id: 'nt2-i-r3-s6-q2',
          type: 'multiple-choice',
          question: 'What must parents do before 1 August 2025?',
          options: [
            'Apply for a new childcare allowance.',
            'Move their child to a registered childcare centre.',
            'Submit their income details via Mijn Toeslagen.',
            'Pay back any previously received allowance.',
          ],
          correctIndex: 2,
          explanation: '"U dient uw inkomensgegevens uiterlijk 1 augustus 2025 door te geven via Mijn Toeslagen."',
          topicArea: 'benefits',
        },
        {
          id: 'nt2-i-r3-s6-q3',
          type: 'multiple-choice',
          question: 'Why should parents immediately report if they are no longer working?',
          options: [
            'To receive a higher allowance.',
            'To avoid receiving too much allowance (which must be repaid).',
            'Because working is mandatory to keep a residency permit.',
            'To register for unemployment benefits.',
          ],
          correctIndex: 1,
          explanation: '"Geef dit direct door om te hoge toeslagen te voorkomen." = to prevent receiving too much allowance.',
          topicArea: 'benefits',
        },
      ],
    },
    {
      id: 'nt2-i-r3-s7',
      passageTitle: 'Artikel: Rijbewijs halen in Nederland',
      passage:
        'Als u in Nederland een rijbewijs wilt halen, zijn er verschillende stappen. Allereerst moet u een theorieexamen afleggen bij het CBR (Centraal Bureau voor de Rijvaardigheidsbewijzen). Dit examen bestaat uit meerdere vragen over verkeersregels en gevaarherkenning.\n\nNa het slagen voor het theorie-examen kunt u rijlessen nemen bij een erkende rijschool. Daarna volgt het praktijkexamen, ook bij het CBR.\n\nBent u al in het bezit van een rijbewijs uit uw land van herkomst? Dan is het mogelijk dit om te wisselen voor een Nederlands rijbewijs, afhankelijk van uw land van herkomst en het soort rijbewijs. Kijk hiervoor op de website van het CBR of bij het RDW.\n\nEen rijbewijs is 10 jaar geldig en kost om te verlengen €41,10. Dit doet u bij uw gemeente.\n\nBelangrijk: rijden zonder rijbewijs is strafbaar en kan leiden tot een boete of zelfs gevangenisstraf.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r3-s7-q1',
          type: 'multiple-choice',
          question: 'What is the CBR?',
          options: [
            'A government office where you register your vehicle.',
            'The central bureau for driving licence examinations.',
            'A driving school.',
            'An organisation that provides road tax.',
          ],
          correctIndex: 1,
          explanation: '"CBR (Centraal Bureau voor de Rijvaardigheidsbewijzen)" — the body that administers driving tests.',
          topicArea: 'driving',
        },
        {
          id: 'nt2-i-r3-s7-q2',
          type: 'multiple-choice',
          question: 'How long is a driving licence valid?',
          options: ['5 years.', '10 years.', '15 years.', 'It never expires.'],
          correctIndex: 1,
          explanation: '"Een rijbewijs is 10 jaar geldig."',
          topicArea: 'driving',
        },
        {
          id: 'nt2-i-r3-s7-q3',
          type: 'multiple-choice',
          question: 'Where do you renew your driving licence?',
          options: ['At the CBR.', 'At the RDW.', 'At your municipality (gemeente).', 'At a driving school.'],
          correctIndex: 2,
          explanation: '"Dit doet u bij uw gemeente."',
          topicArea: 'driving',
        },
        {
          id: 'nt2-i-r3-s7-q4',
          type: 'multiple-choice',
          question: 'Can someone with a foreign driving licence automatically drive in the Netherlands?',
          options: [
            'Yes, all foreign licences are accepted.',
            'It depends on the country and type of licence; exchange may be possible.',
            'No, everyone must take all tests again.',
            'Only EU citizens can exchange their licence.',
          ],
          correctIndex: 1,
          explanation: '"Dan is het mogelijk dit om te wisselen voor een Nederlands rijbewijs, afhankelijk van uw land van herkomst en het soort rijbewijs."',
          topicArea: 'driving',
        },
      ],
    },
  ],
};
