import type { ExamPracticeTest } from '../../types';

export const staatsexamenNt2IReading4: ExamPracticeTest = {
  id: 'staatsexamen-nt2-i-reading-4',
  examType: 'staatsexamen-nt2-i',
  skill: 'reading',
  title: 'Staatsexamen NT2 Programma I – Lezen (Oefening 4)',
  description:
    'Practice reading exam at B1 level. Read longer Dutch texts and answer comprehension questions. Topics: digital privacy, sustainable living, neighbourhood watch, healthcare costs, pension reform, and Dutch civic life.',
  timeLimitMinutes: 75,
  passingScore: 60,
  totalQuestions: 30,
  sections: [
    {
      id: 'nt2-i-r4-s1',
      passageTitle: 'Artikel: Uw privacy online – wat kunt u zelf doen?',
      passage:
        'Elke dag laten we sporen achter op het internet. Websites slaan cookies op, apps bewaren uw locatie en zoekmachines onthouden wat u zoekt. Maar wat kunt u zelf doen om uw privacy te beschermen?\n\nTen eerste kunt u uw browserinstellingen aanpassen. De meeste browsers laten u toe om cookies te weigeren of automatisch te verwijderen. Ten tweede kunt u een sterk wachtwoord gebruiken — minimaal twaalf tekens, met letters, cijfers en symbolen. Gebruik voor elk account een ander wachtwoord.\n\nDaarnaast kunt u twee-stapsverificatie activeren. Dit betekent dat u naast uw wachtwoord ook een code invult die u via sms of een app ontvangt. Zo is uw account veel veiliger.\n\nDe Autoriteit Persoonsgegevens (AP) is de Nederlandse organisatie die toezicht houdt op het gebruik van persoonsgegevens. Als een bedrijf uw gegevens misbruikt, kunt u een klacht indienen bij de AP.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s1-q1',
          type: 'multiple-choice',
          question: 'What is one way the article recommends to protect your privacy online?',
          options: [
            'Never use the internet.',
            'Adjust your browser settings to refuse or delete cookies.',
            'Only use the internet on a public computer.',
            'Ask the government to delete your data.',
          ],
          correctIndex: 1,
          explanation: '"U kunt uw browserinstellingen aanpassen … cookies te weigeren of automatisch te verwijderen."',
          topicArea: 'digital-privacy',
        },
        {
          id: 'nt2-i-r4-s1-q2',
          type: 'multiple-choice',
          question: 'What is "twee-stapsverificatie"?',
          options: [
            'Using the same password for two accounts.',
            'A system where you enter your password plus a code received by SMS or app.',
            'A double check on the quality of your password.',
            'Logging in with your fingerprint and a password.',
          ],
          correctIndex: 1,
          explanation: '"U naast uw wachtwoord ook een code invult die u via sms of een app ontvangt."',
          topicArea: 'digital-privacy',
        },
        {
          id: 'nt2-i-r4-s1-q3',
          type: 'multiple-choice',
          question: 'What is the minimum length of a strong password according to the article?',
          options: ['6 characters', '8 characters', '10 characters', '12 characters'],
          correctIndex: 3,
          explanation: '"Minimaal twaalf tekens, met letters, cijfers en symbolen."',
          topicArea: 'digital-privacy',
        },
        {
          id: 'nt2-i-r4-s1-q4',
          type: 'multiple-choice',
          question: 'Where can you file a complaint if a company misuses your personal data?',
          options: [
            'At the police station.',
            'At the Autoriteit Persoonsgegevens (AP).',
            'At your municipality.',
            'At the Chamber of Commerce.',
          ],
          correctIndex: 1,
          explanation: '"Als een bedrijf uw gegevens misbruikt, kunt u een klacht indienen bij de AP."',
          topicArea: 'digital-privacy',
        },
        {
          id: 'nt2-i-r4-s1-q5',
          type: 'multiple-choice',
          question: 'What does the article say about passwords for different accounts?',
          options: [
            'Use the same strong password for all accounts.',
            'Change your password every day.',
            'Use a different password for each account.',
            'Only use numbers in your password.',
          ],
          correctIndex: 2,
          explanation: '"Gebruik voor elk account een ander wachtwoord."',
          topicArea: 'digital-privacy',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s2',
      passageTitle: 'Informatiebrochure: Duurzaam wonen — kleine stappen, groot verschil',
      passage:
        'Wilt u duurzamer leven maar weet u niet waar te beginnen? Kleine aanpassingen thuis kunnen al een groot verschil maken voor het milieu en uw energierekening.\n\nEnergie besparen:\n– Zet de verwarming één graad lager. Dit scheelt ongeveer 7% op uw gasrekening.\n– Gebruik LED-lampen. Ze verbruiken 80% minder energie dan gewone gloeilampen.\n– Zet apparaten volledig uit in plaats van op standby.\n\nWater besparen:\n– Douche maximaal 5 minuten.\n– Gebruik een waterbesparende douchekop.\n\nAfval verminderen:\n– Koop minder verpakt voedsel.\n– Gebruik een herbruikbare tas en waterfles.\n\nSubsidies: de gemeente en het Rijk bieden subsidies voor isolatie, zonnepanelen en warmtepompen. Kijk op www.milieucentraal.nl voor meer informatie.',
      instructions: 'Read the information brochure and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s2-q1',
          type: 'multiple-choice',
          question: 'How much can you save on your gas bill by lowering the thermostat by one degree?',
          options: ['About 3%', 'About 5%', 'About 7%', 'About 10%'],
          correctIndex: 2,
          explanation: '"Dit scheelt ongeveer 7% op uw gasrekening."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-r4-s2-q2',
          type: 'multiple-choice',
          question: 'How much less energy do LED lights use compared to regular bulbs?',
          options: ['40%', '60%', '80%', '100%'],
          correctIndex: 2,
          explanation: '"Ze verbruiken 80% minder energie dan gewone gloeilampen."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-r4-s2-q3',
          type: 'multiple-choice',
          question: 'What does the brochure say about standby mode?',
          options: [
            'Standby mode uses no energy.',
            'Turn devices fully off instead of leaving them on standby.',
            'Standby mode is fine for small devices.',
            'Only TVs should be switched off fully.',
          ],
          correctIndex: 1,
          explanation: '"Zet apparaten volledig uit in plaats van op standby."',
          topicArea: 'sustainability',
        },
        {
          id: 'nt2-i-r4-s2-q4',
          type: 'multiple-choice',
          question: 'Where can you find information about subsidies for insulation and solar panels?',
          options: ['At the tax office.', 'On www.milieucentraal.nl', 'At a DIY store.', 'On the website of your energy provider.'],
          correctIndex: 1,
          explanation: '"Kijk op www.milieucentraal.nl voor meer informatie."',
          topicArea: 'sustainability',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s3',
      passageTitle: 'Nieuwsbericht: Buurtpreventieteam zoekt nieuwe leden',
      passage:
        'De buurtpreventie van wijk Nieuw-West zoekt vrijwilligers. Het team doet regelmatig avondrondes in de wijk om verdachte situaties te signaleren en te melden bij de politie.\n\nAls vrijwilliger loop je twee keer per maand mee op een avondronde van ongeveer twee uur. Je werkt altijd met een ander teamlid samen. Er is een training van één dag voor nieuwe leden.\n\nWat vragen wij? Je bent minimaal 18 jaar oud, woont in de wijk en hebt geen strafblad.\n\nWat bieden wij? Je leert je buren beter kennen, draagt bij aan een veilige wijk en krijgt een certificaat na de training.\n\nInteresse? Meld je aan via buurtpreventie@nieuwwest.nl of bel 020-555 44 33.',
      instructions: 'Read the news item and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s3-q1',
          type: 'multiple-choice',
          question: 'What do volunteers in the buurtpreventieteam do?',
          options: [
            'They patrol during the day and hand out fines.',
            'They do evening rounds to spot and report suspicious situations to the police.',
            'They organise neighbourhood events and parties.',
            'They manage parking in the neighbourhood.',
          ],
          correctIndex: 1,
          explanation: '"Het team doet regelmatig avondrondes … om verdachte situaties te signaleren en te melden bij de politie."',
          topicArea: 'community',
        },
        {
          id: 'nt2-i-r4-s3-q2',
          type: 'multiple-choice',
          question: 'How often do volunteers go on an evening round?',
          options: ['Once a week.', 'Once a month.', 'Twice a month.', 'Every two weeks, full day.'],
          correctIndex: 2,
          explanation: '"Twee keer per maand mee op een avondronde."',
          topicArea: 'community',
        },
        {
          id: 'nt2-i-r4-s3-q3',
          type: 'multiple-choice',
          question: 'What is one of the requirements to join?',
          options: [
            'You must be at least 21 years old.',
            'You must live in the neighbourhood and have no criminal record.',
            'You must already know the neighbourhood police officer.',
            'You must have previous security experience.',
          ],
          correctIndex: 1,
          explanation: '"Je bent minimaal 18 jaar oud, woont in de wijk en hebt geen strafblad."',
          topicArea: 'community',
        },
        {
          id: 'nt2-i-r4-s3-q4',
          type: 'multiple-choice',
          question: 'What do volunteers receive after the training?',
          options: ['A monthly payment.', 'A free transport card.', 'A certificate.', 'A discount at local shops.'],
          correctIndex: 2,
          explanation: '"Je krijgt een certificaat na de training."',
          topicArea: 'community',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s4',
      passageTitle: 'Folder: Begrijp uw zorgkosten',
      passage:
        'De kosten van de gezondheidszorg in Nederland kunnen verwarrend zijn. Hier is een overzicht:\n\nZorgpremie: u betaalt elke maand een premie aan uw zorgverzekeraar. De hoogte verschilt per verzekering.\n\nEigen risico: in 2025 is het verplichte eigen risico €385 per jaar. U betaalt dit zelf voordat de verzekering meebetaalt. Huisartsbezoeken vallen buiten het eigen risico.\n\nZorgtoeslag: heeft u een laag inkomen? Dan kunt u zorgtoeslag aanvragen bij de Belastingdienst. Dit is een tegemoetkoming in de premiekosten.\n\nAanvullende verzekering: de basisverzekering dekt niet alles. Fysiotherapie, tandarts en brillen zijn vaak niet gedekt. U kunt een aanvullende verzekering afsluiten als u meer wilt vergoeden krijgen.\n\nJaarlijks kunt u in november en december van verzekeraar wisselen voor het volgende jaar.',
      instructions: 'Read the leaflet and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s4-q1',
          type: 'multiple-choice',
          question: 'What is the mandatory eigen risico in 2025?',
          options: ['€285', '€335', '€385', '€435'],
          correctIndex: 2,
          explanation: '"In 2025 is het verplichte eigen risico €385 per jaar."',
          topicArea: 'healthcare-costs',
        },
        {
          id: 'nt2-i-r4-s4-q2',
          type: 'multiple-choice',
          question: 'Are GP visits covered under the eigen risico?',
          options: [
            'Yes, they are the first thing counted toward the eigen risico.',
            'No, GP visits fall outside the eigen risico.',
            'Only the first visit per year falls under the eigen risico.',
            'Only specialist visits are excluded.',
          ],
          correctIndex: 1,
          explanation: '"Huisartsbezoeken vallen buiten het eigen risico."',
          topicArea: 'healthcare-costs',
        },
        {
          id: 'nt2-i-r4-s4-q3',
          type: 'multiple-choice',
          question: 'What is zorgtoeslag?',
          options: [
            'A fine for not having health insurance.',
            'An allowance from the government to help people with low income pay their insurance premium.',
            'Extra coverage for dental care.',
            'A refund for expensive medical treatments.',
          ],
          correctIndex: 1,
          explanation: '"Zorgtoeslag … is een tegemoetkoming in de premiekosten" for people with low income.',
          topicArea: 'healthcare-costs',
        },
        {
          id: 'nt2-i-r4-s4-q4',
          type: 'multiple-choice',
          question: 'Which of the following is typically NOT covered by the basic health insurance?',
          options: ['A visit to the hospital specialist.', 'A blood test ordered by your GP.', 'Physiotherapy and dental care.', 'Emergency room treatment.'],
          correctIndex: 2,
          explanation: '"Fysiotherapie, tandarts en brillen zijn vaak niet gedekt."',
          topicArea: 'healthcare-costs',
        },
        {
          id: 'nt2-i-r4-s4-q5',
          type: 'multiple-choice',
          question: 'When can you switch health insurer?',
          options: ['At any time during the year.', 'Only in January.', 'In November and December for the following year.', 'Only when you move to a new city.'],
          correctIndex: 2,
          explanation: '"Jaarlijks kunt u in november en december van verzekeraar wisselen voor het volgende jaar."',
          topicArea: 'healthcare-costs',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s5',
      passageTitle: 'Artikel: Pensioenhervorming — wat verandert er voor u?',
      passage:
        'In 2023 is er een nieuwe pensioenwet ingegaan in Nederland. Dit heeft gevolgen voor alle werknemers en gepensioneerden. Maar wat verandert er precies?\n\nEerder was het pensioenstelsel gebaseerd op een gemiddeld loon over alle jaren. In het nieuwe systeem bouwt iedereen een persoonlijk pensioenvermogen op. Het bedrag dat u later ontvangt, hangt af van hoeveel er in uw persoonlijke pot is gespaard.\n\nEen voordeel is dat jongere werknemers eerder profiteren van goede beleggingsresultaten. Een nadeel is dat het pensioen minder voorspelbaar is — het kan meevallen, maar ook tegenvallen als de economie slecht is.\n\nDe pensioenfondsen hebben tot 2028 de tijd om over te stappen op het nieuwe systeem. U ontvangt van uw pensioenfonds informatie over hoe dit voor u persoonlijk uitpakt.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s5-q1',
          type: 'multiple-choice',
          question: 'What is the main change in the new pension system?',
          options: [
            'Everyone receives the same pension, regardless of their salary.',
            'Each person builds up their own personal pension pot instead of an average wage-based system.',
            'The pension age has been lowered to 65.',
            'The government now pays all pensions directly.',
          ],
          correctIndex: 1,
          explanation: '"In het nieuwe systeem bouwt iedereen een persoonlijk pensioenvermogen op."',
          topicArea: 'pension',
        },
        {
          id: 'nt2-i-r4-s5-q2',
          type: 'multiple-choice',
          question: 'What is a disadvantage of the new pension system mentioned in the article?',
          options: [
            'Young workers can no longer build up a pension.',
            'The pension is less predictable and can be lower if the economy performs badly.',
            'Pension funds can keep your money without paying it out.',
            'You must pay a higher premium every month.',
          ],
          correctIndex: 1,
          explanation: '"Het pensioen minder voorspelbaar is — het kan meevallen, maar ook tegenvallen als de economie slecht is."',
          topicArea: 'pension',
        },
        {
          id: 'nt2-i-r4-s5-q3',
          type: 'multiple-choice',
          question: 'Until when do pension funds have time to switch to the new system?',
          options: ['2025', '2026', '2027', '2028'],
          correctIndex: 3,
          explanation: '"De pensioenfondsen hebben tot 2028 de tijd om over te stappen op het nieuwe systeem."',
          topicArea: 'pension',
        },
        {
          id: 'nt2-i-r4-s5-q4',
          type: 'multiple-choice',
          question: 'How will you find out how the new pension system affects you personally?',
          options: [
            'You will receive a letter from the government.',
            'Your employer will organise a meeting.',
            'Your pension fund will send you information.',
            'You must register on a special government website.',
          ],
          correctIndex: 2,
          explanation: '"U ontvangt van uw pensioenfonds informatie over hoe dit voor u persoonlijk uitpakt."',
          topicArea: 'pension',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s6',
      passageTitle: 'Brief: aankondiging werkzaamheden in de straat',
      passage:
        'Geachte bewoner,\n\nIn de week van maandag 2 juni tot en met vrijdag 6 juni vinden er werkzaamheden plaats in uw straat. Wij vervangen de oude waterleiding.\n\nWat kunt u verwachten?\n– De straat is gedeeltelijk afgesloten voor auto\'s. Voetgangers kunnen gewoon doorlopen.\n– Op woensdag 4 juni is er geen waterlevering tussen 09:00 en 14:00. Zorg dat u voldoende water in huis heeft.\n– Uw vuilnis wordt die week opgehaald op donderdag in plaats van dinsdag.\n\nExcuses voor het ongemak. Voor vragen: 0800-123 45 67 (gratis).',
      instructions: 'Read the letter and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s6-q1',
          type: 'multiple-choice',
          question: 'What work is being done in the street?',
          options: ['Laying new electricity cables.', 'Replacing the old water pipes.', 'Repaving the road surface.', 'Installing new street lighting.'],
          correctIndex: 1,
          explanation: '"Wij vervangen de oude waterleiding."',
          topicArea: 'civic-life',
        },
        {
          id: 'nt2-i-r4-s6-q2',
          type: 'multiple-choice',
          question: 'On which day will there be no water supply, and during what hours?',
          options: [
            'Monday 2 June, 08:00–12:00.',
            'Wednesday 4 June, 09:00–14:00.',
            'Thursday 5 June, all day.',
            'Friday 6 June, 07:00–15:00.',
          ],
          correctIndex: 1,
          explanation: '"Op woensdag 4 juni is er geen waterlevering tussen 09:00 en 14:00."',
          topicArea: 'civic-life',
        },
        {
          id: 'nt2-i-r4-s6-q3',
          type: 'multiple-choice',
          question: 'When will the rubbish be collected that week?',
          options: ['On Tuesday as usual.', 'On Wednesday.', 'On Thursday instead of Tuesday.', 'On Friday.'],
          correctIndex: 2,
          explanation: '"Uw vuilnis wordt die week opgehaald op donderdag in plaats van dinsdag."',
          topicArea: 'civic-life',
        },
      ],
    },
    {
      id: 'nt2-i-r4-s7',
      passageTitle: 'Artikel: Inburgeren — hoe werkt het in de praktijk?',
      passage:
        'Nieuwkomers in Nederland moeten inburgeren. Dit betekent dat u de Nederlandse taal leert en kennis opdoet over de Nederlandse samenleving. Na de inburgering kunt u zelfstandiger deelnemen aan het dagelijks leven.\n\nDe gemeente begeleidt u bij uw inburgering. U krijgt een persoonlijk Plan Inburgering en Participatie (PIP). In dit plan staat welke cursussen u volgt en welke stappen u zet richting werk of opleiding.\n\nHet inburgeringsexamen bestaat uit meerdere onderdelen: lezen, schrijven, luisteren, spreken, en de toets Kennis van de Nederlandse Maatschappij (KNM). De examens worden afgenomen door DUO.\n\nDe inburgeringstermijn is drie jaar. Als u uw examen niet haalt, kunt u in sommige gevallen verlenging aanvragen. Haalt u uw examen binnen de termijn? Dan ontvangt u het inburgeringsdiploma.',
      instructions: 'Read the article and answer the questions.',
      questions: [
        {
          id: 'nt2-i-r4-s7-q1',
          type: 'multiple-choice',
          question: 'What does the PIP stand for and what does it contain?',
          options: [
            'Persoonlijk Inkomen Plan — an overview of your benefits.',
            'Persoonlijk Inburgerings- en Participatieplan — which courses you follow and steps toward work or education.',
            'Plan Integratie en Participatie — a housing allocation plan.',
            'Persoonlijk Informatie Pakket — documents about living in the Netherlands.',
          ],
          correctIndex: 1,
          explanation: '"Plan Inburgering en Participatie (PIP) … welke cursussen u volgt en welke stappen u zet richting werk of opleiding."',
          topicArea: 'integration',
        },
        {
          id: 'nt2-i-r4-s7-q2',
          type: 'multiple-choice',
          question: 'Which organisation administers the inburgering exams?',
          options: ['The municipality (gemeente).', 'The UWV.', 'DUO (Dienst Uitvoering Onderwijs).', 'The IND.'],
          correctIndex: 2,
          explanation: '"De examens worden afgenomen door DUO."',
          topicArea: 'integration',
        },
        {
          id: 'nt2-i-r4-s7-q3',
          type: 'multiple-choice',
          question: 'What happens when you successfully complete the inburgering within the time limit?',
          options: [
            'You receive a permanent residence permit automatically.',
            'You receive the inburgeringsdiploma.',
            'You are immediately eligible for a Dutch passport.',
            'You receive a financial bonus from the municipality.',
          ],
          correctIndex: 1,
          explanation: '"Haalt u uw examen binnen de termijn? Dan ontvangt u het inburgeringsdiploma."',
          topicArea: 'integration',
        },
        {
          id: 'nt2-i-r4-s7-q4',
          type: 'multiple-choice',
          question: 'How long is the standard inburgering period?',
          options: ['1 year', '2 years', '3 years', '5 years'],
          correctIndex: 2,
          explanation: '"De inburgeringstermijn is drie jaar."',
          topicArea: 'integration',
        },
      ],
    },
  ],
};
